var nP="3",oP="Any",pP="Aromatic",qP="Nonring",rP="Reset",sP="Ring";function AP(){AP=r;BP=new $o(cd,new CP)}function CP(){}q(210,207,{},CP);_.Pc=function(a){rx();OL(this,a.b,DP(a.a.a,a.a.a.ob.selectedIndex))};_.Sc=function(){return BP};var BP;function EP(a,b){if(0>b||b>=a.ob.options.length)throw new tu;}function DP(a,b){EP(a,b);return a.ob.options[b].value}function FP(){this.ob=$doc.createElement("select");this.ob[ed]="gwt-ListBox"}q(356,334,Vh,FP);function GP(){GP=r}
function HP(a,b){if(null==b)throw new Sq("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(pf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function IP(){GP();qx.call(this);new Ai;this.mc=new JP((rx(),this))}q(421,408,{90:1,92:1,99:1,111:1,117:1},IP);_.ae=function(){return vx(this.mc,this)};
_.pe=function(){return(null==this.jc&&(this.jc=cx(this)),this.jc)+xa+this.uc+xa+this.vc+xa+this.rc+Mg+this.hc+(this.qc?l:",hidden")+",current="+DP(this.mc.a,this.mc.a.ob.selectedIndex)};function KP(){lL.call(this,7)}q(434,1,Uh,KP);function LP(a){nL.call(this,a,0)}q(439,408,wh,LP);q(576,574,Wh);_.Lc=function(){!this.a.Ib?this.a.Ib=new MP(this.a):this.a.Ib.mc.c.gb?CM(this.a.Ib.mc.c):JL(this.a.Ib)};function NP(a,b){xK(b)==a.a?Z(b,(by(),ky)):Z(b,a.a)}
function OP(a){var b,c,d,e;e=l;d=!1;xK(PP)!=a.a?(e=va,d=!0):xK(QP)!=a.a?(e="!#6",d=!0):xK(RP)!=a.a?(Z(SP,(by(),ky)),Z(TP,ky),Z(UP,ky),Z(VP,ky),e="F,Cl,Br,I"):(b=xK(WP)!=a.a,c=xK(XP)!=a.a,xK(YP)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),xK(ZP)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),xK($P)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),xK(aQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),xK(bQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),xK(SP)!=a.a&&(e+="F,"),xK(TP)!=a.a&&(e+="Cl,"),xK(UP)!=a.a&&(e+="Br,"),xK(VP)!=a.a&&(e+="I,"),
sE(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=oc:c?e=pb:(Z(PP,(by(),ky)),e=va)));b=l;d&&xK(WP)!=a.a&&(b+=";a");d&&xK(XP)!=a.a&&(b+=";A");xK(cQ)!=a.a&&(b+=";R");xK(dQ)!=a.a&&(b+=";!R");xK(PP)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=eQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=fQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);xK(gQ)!=a.a&&(e="~");xK(hQ)!=a.a&&(e=fb);xK(iQ)!=a.a&&(e=ob);xK(jQ)!=a.a&&(e="!@");qL(a.e,e)}
function kQ(a){lQ(a);mQ(a);var b=eQ.mc.a;EP(b,0);b.ob.options[0].selected=!0;b=fQ.mc.a;EP(b,0);b.ob.options[0].selected=!0;Z(WP,a.a);Z(XP,a.a);Z(cQ,a.a);Z(dQ,a.a);Z(eQ,a.a);Z(fQ,a.a);nQ(a)}function lQ(a){Z(YP,a.a);Z(ZP,a.a);Z($P,a.a);Z(aQ,a.a);Z(bQ,a.a);Z(SP,a.a);Z(TP,a.a);Z(UP,a.a);Z(VP,a.a)}function mQ(a){Z(PP,a.a);Z(QP,a.a);Z(RP,a.a)}function nQ(a){Z(gQ,a.a);Z(hQ,a.a);Z(iQ,a.a);Z(jQ,a.a);a.b=!1}
function MP(a){eL.call(this,"Atom/Bond Query");this.i=new YK(this.jg());Vx(this.q,new ML(this));this.a=(xA(),zA);this.c=a;this.d||(a=fx(a),this.d=new pL(a),IL(this.d,-150,10));this.j=this.d;Ex(this,new KP);Z(this,this.a);a=new Jx;Ex(a,new By(0,3,1));$(a,new LP("Atom type :"),null);PP=new YK(oP);QP=new YK("Any except C");RP=new YK("Halogen");$(a,PP,null);$(a,QP,null);$(a,RP,null);$(this,a,null);a=new Jx;Ex(a,new By(0,3,1));$(a,new nL("Or select one or more from the list :",0),null);$(this,a,null);
a=new Jx;Ex(a,new By(0,3,1));YP=new YK(sb);ZP=new YK(Pb);$P=new YK(Tb);aQ=new YK($b);bQ=new YK(Ub);SP=new YK(Ab);TP=new YK(wb);UP=new YK(rb);VP=new YK(Ib);$(a,YP,null);$(a,ZP,null);$(a,$P,null);$(a,aQ,null);$(a,bQ,null);$(a,SP,null);$(a,TP,null);$(a,UP,null);$(a,VP,null);$(this,a,null);a=new Jx;Ex(a,new By(0,3,1));eQ=new IP;HP(eQ,oP);HP(eQ,$a);HP(eQ,cb);HP(eQ,eb);HP(eQ,nP);$(a,new LP("Number of hydrogens :  "),null);$(a,eQ,null);$(this,a,null);a=new Jx;Ex(a,new By(0,3,1));fQ=new IP;HP(fQ,oP);HP(fQ,
$a);HP(fQ,cb);HP(fQ,eb);HP(fQ,nP);HP(fQ,"4");HP(fQ,"5");HP(fQ,"6");$(a,new nL("Number of connections :",0),null);$(a,fQ,null);$(a,new nL(" (H's don't count.)",0),null);$(this,a,null);a=new Jx;Ex(a,new By(0,3,1));$(a,new LP("Atom is :"),null);WP=new YK(pP);$(a,WP,null);XP=new YK("Nonaromatic");$(a,XP,null);cQ=new YK(sP);$(a,cQ,null);dQ=new YK(qP);$(a,dQ,null);$(this,a,null);a=new Jx;Z(a,ry(xK(this)));Ex(a,new By(0,3,1));$(a,new LP("Bond is :"),null);gQ=new YK(oP);$(a,gQ,null);hQ=new YK(pP);$(a,hQ,
null);iQ=new YK(sP);$(a,iQ,null);jQ=new YK(qP);$(a,jQ,null);$(this,a,null);a=new Jx;Ex(a,new By(1,3,1));this.e=new gz(va,20);$(a,this.e,null);$(a,new YK(rP),null);$(a,this.i,null);$(this,a,null);this.mc&&gL(this.mc.c,!1);dL(this,!1);lQ(this);mQ(this);nQ(this);Z(WP,this.a);Z(XP,this.a);Z(cQ,this.a);Z(dQ,this.a);Z(eQ,this.a);Z(fQ,this.a);NP(this,PP);cL(this);a=this.j;KL(this.mc.c,a.a,a.b);!ex(this)&&GK(this);BK(this)}q(586,568,wH,MP);
_.kg=function(a,b){var c;H(b,rP)?(kQ(this),NP(this,PP),OP(this)):D(a.f,89)?(nQ(this),zr(a.f)===zr(PP)?(lQ(this),mQ(this)):zr(a.f)===zr(QP)?(lQ(this),mQ(this)):zr(a.f)===zr(RP)?(lQ(this),mQ(this)):zr(a.f)===zr(cQ)?Z(dQ,this.a):zr(a.f)===zr(dQ)?(Z(cQ,this.a),Z(WP,this.a)):zr(a.f)===zr(WP)?(Z(XP,this.a),Z(dQ,this.a)):zr(a.f)===zr(XP)?Z(WP,this.a):zr(a.f)===zr(gQ)||zr(a.f)===zr(hQ)||zr(a.f)===zr(iQ)||zr(a.f)===zr(jQ)?(kQ(this),this.b=!0):mQ(this),NP(this,a.f),OP(this)):D(a.f,90)&&(nQ(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(by(),ky)),OP(this));107!=this.c.e&&(this.c.e=107,Ox(this.c));return!0};_.lg=function(){return Jm(this.e.mc.a.ob,Dg)};_.mg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var PP=_.e=null,gQ=null,QP=null,WP=null,hQ=null,UP=null,YP=null,fQ=null,eQ=null,TP=null,SP=null,RP=null,VP=null,ZP=null,XP=null,dQ=null,jQ=null,$P=null,bQ=null,cQ=null,iQ=null,aQ=null;function JP(a){BG();DG.call(this);this.a=new FP;au(this.a,new oQ(this,a),(AP(),AP(),BP))}q(632,630,{},JP);_.Je=function(){return this.a};
_.a=null;function oQ(a,b){this.a=a;this.b=b}q(633,1,{},oQ);_.a=null;_.b=null;W(586);W(421);W(632);W(633);W(356);W(210);x(sH)(3);