language: php

sudo: false

servics:
  - mysql

addons:
 firefox: "47.0.1"
 apt:
  packages:
   - openjdk-8-jre-headless

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - IGNORE_PATHS=db/upgrade.php,classes/form/duration.php,classes/form/itemspertime.php
  matrix:
    - MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_38_STABLE DB=mysqli
    - MOODLE_BRANCH=MOODLE_39_STABLE DB=mysqli
    - MOODLE_BRANCH=master DB=mysqli
# Ignore PHP 7.4 with MOODLE_36_STABLE & MOODLE_37_STABLE since they contain deprecated code when using PHP 7.4 or higher
matrix:
  exclude:
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_36_STABLE DB=mysqli
    - php: 7.4
      env: MOODLE_BRANCH=MOODLE_37_STABLE DB=mysqli
  allow_failures:
    - env: MOODLE_BRANCH=master DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini
  - |
    if [ "${MOODLE_BRANCH}" = "MOODLE_36_STABLE" ]; then
      nvm install 8.9
      nvm use 8.9
    else
      nvm install 14.6.0
      nvm use 14.6.0
    fi
  - cd ../..
  - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phpunit