language: php

os: linux
dist: xenial

services:
  - mysql
  - postgresql

addons:
  firefox: "47.0.1"
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

jobs:
  include:
    - php: 7.3
      env:
        - MOODLE_BRANCH=master
        - DB=pgsql

    - php: 7.4
      env:
        - MOODLE_BRANCH=MOODLE_39_STABLE
        - DB=mysqli

    - php: 7.3
      env:
        - MOODLE_BRANCH=MOODLE_38_STABLE
        - DB=pgsql
        - CHECK_GRUNT=yes

    - php: 7.2
      env:
        - MOODLE_BRANCH=MOODLE_37_STABLE
        - DB=mysqli

    - php: 7.1
      env:
        - MOODLE_BRANCH=MOODLE_36_STABLE
        - DB=pgsql
        - NODE=8.9

    - php: 7.0
      env:
        - MOODLE_BRANCH=MOODLE_35_STABLE
        - DB=mysqli

before_install:
  - phpenv config-rm xdebug.ini

  - if [ -z $CHECK_GRUNT ]; then
    export CHECK_GRUNT=no;
    fi

  - if [ -z $NODE ]; then
    export NODE=14;
    fi
  - nvm install $NODE
  - nvm use $NODE

  - cd ../..
  - composer create-project -n --no-dev --prefer-dist moodlerooms/moodle-plugin-ci ci ^2
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache
  - moodle-plugin-ci grunt
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
