language: php

dist: bionic
sudo: required

services:
  - mysql

addons:
  firefox: "47.0.1"
  postgresql: "9.6"
  apt:
    packages:
      - openjdk-8-jre-headless
      - chromium-chromedriver

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

matrix:
  include:
    - php: 7.3
      env:
        - MOODLE_BRANCH=master
        - DB=mysqli

    - php: 7.3
      env:
        - MOODLE_BRANCH=MOODLE_38_STABLE
        - DB=pgsql

    - php: 7.2
      env:
        - MOODLE_BRANCH=MOODLE_37_STABLE
        - DB=mysqli


before_install:
    - phpenv config-rm xdebug.ini
    - nvm install 14.2.0
    - nvm use 14.2.0
    - cd ../..
    - composer create-project -n --no-dev --prefer-dist blackboard-open-source/moodle-plugin-ci ci ^2
    - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"
    - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//') JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd || true
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints
  - moodle-plugin-ci mustache || true
  - moodle-plugin-ci grunt || [ "$MOODLE_BRANCH" = 'master' ] || [ "$MOODLE_BRANCH" = 'MOODLE_38_STABLE' ] || [ "$MOODLE_BRANCH" = 'MOODLE_37_STABLE' ]
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat || true # Behat seems to be broken at the moment :-(