var YF="runCallbacks",ZF="end";function $F(a,b,c){return a.indexOf(b,c)}function aG(a){var b=Sl,c,d,e;e=a==b.f?te:td+a;$stats&&(e=Xl(e,ZF,a),$stats(e));a<b.i.length&&dm(b.i,a,null);Vl(b,a)&&b.j.b++;b.b=-1;b.d[a]=!0;bm(b);e=b.a[a];if(null!=e){$stats&&(c=Xl(YF+a,Dc,-1),$stats(c));dm(b.a,a,null);for(c=0,d=e.length;c<d;++c)b=e[c],b.Pc();$stats&&(a=Xl(YF+a,ZF,-1),$stats(a))}}
var bG={55:1,117:1},cG={14:1,21:1,22:1,23:1,24:1,25:1,26:1,27:1,28:1,29:1,48:1,50:1,59:1,71:1,72:1,74:1,82:1,84:1},dG={48:1,50:1,59:1,71:1,72:1,74:1,77:1,82:1,84:1,142:1,149:1},eG={8:1,10:1,117:1,121:1,123:1},fG={92:1,93:1,99:1,104:1,111:1,117:1},gG={113:1},hG={48:1,50:1,59:1,63:1,71:1,73:1,74:1,82:1,84:1},iG="&",jG="&nbsp;",kG="'",lG="--",mG="//",nG="1em",oG="1ex",pG="1in",qG="After",rG="Before",sG="East",tG="First",uG="GBVTBU-BB",vG="Incorrect URL: ",wG="North",xG="Resize-",yG="South",zG="West",
AG="__uiObjectID",BG="backgroundColor",CG="col",DG="cssFloat",EG="dir",FG="dragdrop-handle",GG="dragdrop-selected",HG="filter",IG="float",JG="ltr",KG="px;";r(1,-1,qh);_.gC=function(){return this.cZ};function LG(){LG=s;MG=new xl}function NG(a){for(var b,a=new vq(a.j.k);a.b<a.d.Qe();)b=wq(a),Fs(b.ud(),GG,!1),nD(a)}
function OG(a,b,c){var a=a.n,d;try{d=new PG(b,c.Zc(a),c.ad(a),(c.$c(a),c._c(a))),D(a.c,c,d)}catch(e){e=nm(e);if(E(e,124))throw new Fl("dragHandle must implement HasMouseDownHandlers, HasMouseUpHandlers, HasMouseMoveHandlers and HasMouseOutHandlers to be draggable",e);throw e;}Fs(b.ud(),uG,!0);Fs(c.ud(),FG,!0);D(MG,b,c)}function QG(a){var b;a.o=!1;for(a=new vq(a.j.k);a.b<a.d.Qe();)b=wq(a),Fs(b.ud(),GG,!1),nD(a)}
function RG(a,b){Ii(a.j.k,b)?Fs(b.ud(),GG,!1):a.o?(yi(a.j.k,b),Fs(b.ud(),GG,!0)):(a.j.k._e(),yi(a.j.k,b))}function SG(a){this.f=a;this.j=new TG(this);this.n=new UG(this.j)}r(3,1,{});_.wc=function(){VG(this.j.e,"dragdrop-dragging")};_.xc=function(){Es(this.j.e,"dragdrop-dragging")};_.f=null;_.i=!1;_.j=null;_.k=0;_.n=null;_.o=!1;var MG;function TG(a){this.k=new vi;this.d=a;this.a=a.f}r(4,1,{},TG);_.a=null;_.b=0;_.c=0;_.d=null;_.e=null;_.f=null;_.i=0;_.j=0;
function WG(a,b,c){a.b.i=b;a.b.j=c;a.b.b=b-a.f;a.b.c=c-a.i;a.b.d.yc()}function XG(a,b){var c;c=Bq(a.c,YG).a;b.a.ctrlKey||b.a.metaKey||NG(a.b.d);RG(a.b.d,c)}function ZG(a){a.b.f=null;a.b.d.xc();Ct((Zs(),ov(null)),a.a,0,0);var b=a.a.ob;Or=b;Rr();zs=b;a.d=2}
function UG(a){this.c=new xl;this.b=a;this.a=new tu;Hs(this.a,cn(),bn());Ss(this.a,this,(Cp(),Cp(),Dp));Ss(this.a,this,(Jp(),Jp(),Kp));a=this.a.ob.style;a[HG]="alpha(opacity=0)";a.opacity=0;a.margin=0+(bo(),wf);a.borderStyle=($G(),bf);a[BG]="blue"}r(5,1,{},UG);
_.zc=function(a){var b,c,d,e;c=a.f;d=No(a);e=Oo(a);b=Um(a.a);if(!(3==this.d||2==this.d||1!=b)&&!YG)YG=c,this.b.e=Bq(this.c,YG).a,!a.a.ctrlKey&&!a.a.metaKey&&-1==Zu(this.b.k,this.b.e)&&(NG(this.b.d),RG(this.b.d,this.b.e)),aH(new bH),this.e=!0,a.a.preventDefault(),this.f=d,this.i=e,b=new cH(YG,null),YG!=this.b.e&&(c=new cH(this.b.e,null),this.f+=b.a-c.a,this.i+=b.d-c.d),0==this.b.d.k&&!a.a.ctrlKey&&!a.a.metaKey&&(this.b.i=d+b.a,this.b.j=e+b.d,ZG(this),1!=this.d&&WG(this,this.b.i,this.b.j))};
_.Ac=function(a){var b,c,d;c=a.f;b=c.ob;d=Lo(a,b);a=Mo(a,b);if(3==this.d||2==this.d){if(c!=this.a)return;this.d=3}else if(this.e&&(Oi(tA(d-this.f),tA(a-this.i))>=this.b.d.k?(dH(),-1!=Zu(this.b.k,this.b.e)||RG(this.b.d,this.b.e),c=new cH(YG,null),this.b.i=this.f+c.a,this.b.j=this.i+c.d,d+=c.a,a+=c.d,ZG(this)):Nr.preventDefault()),1==this.d)return;Nr.preventDefault();WG(this,d,a)};
_.Bc=function(a){var b,c,d,e;d=a.f;b=d.ob;e=Lo(a,b);b=Mo(a,b);if(1==Um(a.a)&&(this.e=!1,YG))try{if(dH(),1==this.d)XG(this,a);else{d!=this.a&&(c=new cH(d,null),e+=c.a,b+=c.d);try{WG(this,e,b),this.b.d.wc(),3!=this.d&&XG(this,a)}finally{var f=this.a.ob;Or&&f==Or&&(Or=null);Rr();f===zs&&(zs=null);Ys(this.a);this.d=1;this.b.e=null}}}finally{YG=null}};_.a=null;_.b=null;_.d=1;_.e=!1;_.f=0;_.i=0;var YG=null;function bH(){}r(6,1,rh,bH);_.Cc=function(){dH()};
function PG(a,b,c,d){this.a=a;this.b=b;this.c=d;this.d=c}r(7,1,{},PG);_.a=null;_.b=null;_.c=null;_.d=null;r(8,1,{});r(10,8,{});r(9,10,{});_.a=null;r(11,1,{});_.tS=VC;function cH(a,b){!a||a==(Zs(),ov(null))?this.f=this.e=0:(this.e=a.qd()-Xm(a.ob),this.f=a.rd()-(a.ob.scrollTop||0));!b||b==(Zs(),ov(null))?this.c=this.b=0:(this.b=Jm(b.ob)+eH(b.ob),this.c=Mm(b.ob)+fH(b.ob));this.a=this.e-this.b;this.d=this.f-this.c}r(14,11,{},cH);_.tS=VC;_.a=0;_.b=0;_.c=0;_.d=0;_.e=0;_.f=0;
function dH(){try{$wnd.getSelection().removeAllRanges()}catch(a){throw Error("unselect exception:\n"+a);}}function eH(a){try{var b=$doc.defaultView.getComputedStyle(a,null).getPropertyValue("border-left-width");return-1==b.indexOf(wf)?0:parseInt(b.substr(0,b.length-2))}catch(c){throw Error("getBorderLeft exception:\n"+c);}}
function fH(a){try{var b=$doc.defaultView.getComputedStyle(a,null).getPropertyValue("border-top-width");return-1==b.indexOf(wf)?0:parseInt(b.substr(0,b.length-2))}catch(c){throw Error("getBorderTop: "+c);}}function gH(a){try{return a.clientHeight}catch(b){throw Error("getClientHeight exception:\n"+b);}}function hH(a){try{return a.clientWidth}catch(b){throw Error("getClientWidth exception:\n"+b);}}function iH(a){return $wnd.setInterval(y(function(){a.Lc()}),100)}
function $G(){$G=s;jH=new kH;lH=new mH;nH=new oH;pH=new qH;rH=new sH;tH=F(uH,m,8,[jH,lH,nH,pH,rH])}r(151,152,eG);var tH,nH,lH,pH,jH,rH;function kH(){this.b=0}r(153,151,eG,kH);function mH(){this.b=1}r(154,151,eG,mH);function oH(){this.b=2}r(155,151,eG,oH);function qH(){this.b=3}r(156,151,eG,qH);function sH(){this.b=4}r(157,151,eG,sH);function vH(){vH=s;wH=new Jo(md,new xH)}function xH(){}r(206,200,Dh,xH);
_.Tc=function(a){var b=a.a,a=!a.a.H.c,c,d;if(a!=b.H.c)if(b.jb){if(a){if(b.N!=(yH(),zH))a=AH(b.ob),c=new BH(Om(b.ob,kf),Om(b.ob,jf)),d=new BH(Om(b.S.ib.ob,kf),Om(b.S.ib.ob,jf)),b.E.b=a.b-(c.b-d.b),b.E.a=a.a-(c.a-d.a);CH(b.H,!0);a=Om(b.S.ib.ob,kf);DH(b,new BH(a,EH(b.S.ib).a));b.I&&b.N!=zH&&FH(b.q,b)}else CH(b.H,!1),b.N!=(yH(),zH)?DH(b,new BH(b.E.b,b.E.a)):GH(b,AH(b.q.ob)),b.I&&b.N!=zH&&HH(b.q,b);JH(b.S.ib)}else CH(b.H,!0)};_.Wc=function(){return wH};var wH;function MH(){MH=s;TH=new Jo(Gd,new UH)}
function UH(){}r(212,195,{},UH);_.Tc=function(a){Ys(a.a.a)};_.Wc=function(){return TH};var TH;function VH(){VH=s;WH=new Jo(Me,new XH)}function XH(){}r(221,200,Dh,XH);_.Tc=function(a){var b;a.e&&1==a.d&&(b=new cH(YG,null),a.b.i=a.f+b.a,a.b.j=a.i+b.d,ZG(a))};_.Wc=function(){return WH};var WH;function YH(a){this.a=a}r(233,196,{},YH);_.Tc=function(a){a.cd(this)};_.Uc=function(){return ZH};var ZH=_.a=null;function $H(a){this.a=a}r(235,196,{},$H);_.Tc=function(a){a.ed(this)};_.Uc=function(){return aI};
var aI=_.a=null;function bI(a){a=Pm(a,EG);return cI(Qf,a)?(dI(),eI):cI(JG,a)?(dI(),fI):(dI(),gI)}function dI(){dI=s;eI=new hI(0);fI=new hI(1);gI=new hI(2);iI=F(jI,m,51,[eI,fI,gI])}function hI(a){this.b=a}r(246,152,{51:1,117:1,121:1,123:1},hI);var iI,gI,fI,eI;function kI(a,b){return br(a.l&b.l,a.m&b.m,a.h&b.h)}function lI(a,b){Bl(a.a.a,b.a);return a}function mI(){this.a=new nI}r(263,1,{},mI);function oI(a){if(null==a)throw new kq("css is null");this.a=a}r(264,1,{53:1,117:1},oI);
_.eQ=function(a){return!E(a,53)?!1:H(this.a,a.a)};_.hC=Qp;_.a=null;function pI(a){if(null==a)throw new kq("html is null");this.a=a}r(266,1,bG,pI);_.gd=JB;_.eQ=Ps;_.hC=Qp;_.a=null;r(267,1,bG,function(){this.a=l});_.gd=JB;_.eQ=Ps;_.hC=Qp;_.a=null;function qI(){qI=s;rI=RegExp(iG,Nd);sI=RegExp(kb,Nd);tI=RegExp(hb,Nd);uI=RegExp(kG,Nd);vI=RegExp(da,Nd)}
function wI(a){qI();-1!=a.indexOf(iG)&&(a=a.replace(rI,na));-1!=a.indexOf(hb)&&(a=a.replace(tI,pa));-1!=a.indexOf(kb)&&(a=a.replace(sI,oa));-1!=a.indexOf(da)&&(a=a.replace(vI,"&quot;"));-1!=a.indexOf(kG)&&(a=a.replace(uI,"&#39;"));return a}var rI,sI,tI,vI,uI;function xI(a,b,c){var d,e,f,g,j;if(a)for(g=0,j=c.length;g<j;++g){f=c[g];e=rq(a.a,f,null).Qe();for(e-=1;0<=e;--e)if(d=rq(a.a,f,null).bg(e),E(d,57)&&Jl(d.a,b)){var h=a.a,n=f;0<h.b?lq(h,new Zv(h,n,null,d)):Cq(h,n,null,d)}}}
function yI(a){this.a=a}r(275,274,$h,yI);_.hd=function(a){a.c&&(this.a.nd(a.d)||(a.a=!0))};function zI(a){this.a=a}r(276,274,$h,zI);_.dd=function(){var a=this.a.a;AI(a);BI(a.ob)};r(277,99,Bh,function(){});function CI(a){0!=a.b.c&&!a.e&&!a.c&&(a.e=!0,zi(a.d,1))}function DI(){this.a=new EI(this);this.b=new vi;this.d=new FI(this);this.f=new GI(this)}r(278,1,{},DI);_.c=!1;_.e=!1;function EI(a){Ai();this.a=a}r(279,26,{},EI);_.Mc=function(){if(this.a.c){var a=this.a,b=a.f;as(b.d.b,b.b);HI(a.f);a.c=!1;CI(a)}};
_.a=null;function FI(a){Ai();this.a=a}r(280,26,{},FI);_.Mc=function(){this.a.e=!1;var a=this.a,b=li(),c,d,e;e=!1;try{a.c=!0;a.f.a=a.b.c;for(zi(a.a,1E4);a.f.c<a.f.a;){d=II(a.f);try{if(null==d)break;E(d,58)&&(c=d,c.Cc())}finally{(e=-1==a.f.b)||HI(a.f)}if(100<=li()-b)break}}finally{e||(Hi(a.a),a.c=!1,CI(a))}};_.a=null;function II(a){var b;a.b=a.c;b=as(a.d.b,a.c++);a.c>=a.a&&(a.c=0);return b}function HI(a){yD(a.d.b,a.b);--a.a;a.b<=a.c&&0>--a.c&&(a.c=0);a.b=-1}function GI(a){this.d=a}r(281,1,{},GI);
_.jd=function(){return this.c<this.a};_.kd=function(){return II(this)};_.ld=function(){HI(this)};_.a=0;_.b=-1;_.c=0;_.d=null;function JI(){JI=s;KI=new DI}function aH(a){JI();if(!a)throw new kq("cmd cannot be null");var b=KI;yi(b.b,a);CI(b)}var KI;function LI(){var a;LI=s;MI=(a=$doc,H(a.compatMode,sb)?a.documentElement:a.body)}var MI;function NI(){this.b=new vi}function OI(a){a=a[AG];return null==a?-1:a}r(298,1,{},NI);_.a=null;function PI(a,b){this.a=a;this.b=b}r(299,1,{},PI);_.a=0;_.b=null;
function VG(a,b){Fs(a.ud(),b,!1)}r(308,1,zh);_.qd=Ny;_.rd=fi;_.vd=function(){return this.ob.style.display!=bf};_.wd=function(){throw new QI;};_.yd=function(a){Os(this.ob,a)};function RI(a){for(a=new SI(a);a.a.a<a.a.b.c-1;)Qv(a.a),Rv(a.a)}r(304,305,Jh);_.Ld=function(a){ut(this,a,this.ob)};_.Md=function(a,b,c){Ft(this,a,b,c)};r(311,312,Jh);_.vd=function(){return!H(he,this.ob.style[Gg])};_.nd=function(){return!0};_.yd=function(a){this.ob.style[Gg]=a?Hg:he};_.Ud=function(){Ut(this)};r(314,315,sh);
r(322,307,Uh);_.Zc=ei;_.$c=ey;_._c=Av;_.ad=xw;r(321,322,{14:1,15:1,16:1,17:1,18:1,19:1,20:1,21:1,22:1,23:1,24:1,25:1,26:1,27:1,28:1,29:1,30:1,31:1,32:1,33:1,34:1,35:1,36:1,37:1,38:1,39:1,40:1,41:1,42:1,43:1,44:1,45:1,46:1,48:1,50:1,54:1,59:1,62:1,65:1,66:1,67:1,68:1,69:1,70:1,71:1,74:1,78:1,79:1,80:1,81:1,82:1,84:1});_.Wd=function(){return this.ob.textContent};function TI(a){var b;this.ob=(b=$doc.createElement("BUTTON"),b.type=Qc,b);this.ob[Wc]="gwt-Button";Qm(this.ob,a)}
r(320,321,{14:1,15:1,16:1,17:1,18:1,19:1,20:1,21:1,22:1,23:1,24:1,25:1,26:1,27:1,28:1,29:1,30:1,31:1,32:1,33:1,34:1,35:1,36:1,37:1,38:1,39:1,40:1,41:1,42:1,43:1,44:1,45:1,46:1,48:1,50:1,54:1,59:1,61:1,62:1,65:1,66:1,67:1,68:1,69:1,70:1,71:1,74:1,78:1,79:1,80:1,81:1,82:1,84:1},TI);function UI(a,b){var c;if(a.f)throw new Vs("Composite.initWidget() may only be called once.");Ys(b);c=b.ob;a.ob=c;var d;Kr();try{d=!!c&&!!c.__gwt_resolve}catch(e){d=!1}d&&((Kr(),c).__gwt_resolve=VI(a));a.f=b;at(b,a)}
function WI(a){if(-1!=a.kb){var b=a.f,c=a.kb;-1==b.kb?Cs(b.ob,c|(b.ob.__eventBits||0)):b.kb|=c;a.kb=-1}a.f.Dd();a.ob.__listener=a;a.Fd()}r(324,307,hG);_.Cd=function(){return this.f?this.f.Cd():!1};_.Dd=function(){WI(this)};_.md=function(a){Ws(this,a);this.f.md(a)};_.Ed=function(){this.f.Ed()};_.wd=function(){return this.ob=this.f.wd()};_.f=null;
function XI(a,b,c){a.c=!1;c?Qm(a.a,b):a.a.textContent=b||l;if(a.d!=a.b)switch(a.d=a.b,b=a.a,a.b.b){case 0:b[EG]=Qf;break;case 1:b[EG]=JG;break;case 2:bI(b)!=(dI(),gI)&&(b[EG]=l)}}function YI(a){this.a=a;this.c=!1;this.d=this.b=bI(a)}r(325,1,{},YI);_.a=null;_.b=null;_.c=!1;_.d=null;r(326,312,oh);_.Zc=ei;_.$c=ey;_._c=Av;_.ad=xw;function ZI(a,b,c,d){b=a.d.a.c.rows[b].cells[c];var e,c=Sm(b);e=null;c&&(c=OI(c),e=0>c?null:as(a.i.b,c));e?$I(a,e):d&&Qm(b,l);return b}
function $I(a,b){var c;if(b.nb!=a)return!1;try{at(b,null)}finally{c=b.ob;Tm(c).removeChild(c);var d=a.i,e;e=OI(c);c[AG]=null;c=d.b;wx(e,c.c);dm(c.b,e,null);d.a=new PI(e,d.a)}return!0}r(328,306,cG);_.Kd=function(){return new aJ(this)};_.Hd=function(a){return $I(this,a)};_.c=null;_.d=null;_.e=null;_.f=null;function bJ(a){if(0>=a.b)throw new WC("Row index: 0, Row size: "+a.b);if(0>=a.a)throw new WC("Column index: 0, Column size: "+a.a);}
function cJ(){this.i=new NI;this.f=$doc.createElement(gg);this.c=$doc.createElement(jg);Jr(this.f,this.c);this.ob=this.f;this.d=new dJ(this);var a=new eJ(this);this.e&&(a.a=this.e.a);a=this.e=a;if(!a.a){a.a=$doc.createElement("colgroup");var b=a.a;As(a.b.f,(Kr(),Lr(b)),0);Jr(a.a,$doc.createElement(CG))}var c,d,e;if(1!=this.a){if(1<this.a)for(a=0;a<this.b;++a)for(b=this.a-1;1<=b;--b){c=b;d=void 0;d=this.b;if(a>=d||0>a)throw new WC("Row index: "+a+", Row size: "+d);if(0>c)throw new WC("Column "+c+" must be non-negative: "+
c);if(this.a<=c)throw new WC("Column index: "+c+", Column size: "+this.a);c=ZI(this,a,b,!1);d=this.c.rows[a];d.removeChild(c)}else for(a=0;a<this.b;++a)for(b=this.a;1>b;++b)d=this.c.rows[a],e=(c=$doc.createElement(kg),Qm(c,jG),c),As(d,(Kr(),Lr(e)),b);this.a=1;a=this.e;b=1;b=1<b?b:1;c=a.a.childNodes.length;if(c<b)for(;c<b;++c)d=$doc.createElement(CG),a.a.appendChild(d);else if(c>b)for(;c>b;--c)a.a.removeChild(a.a.lastChild)}if(1!=this.b)if(1>this.b){a=this.c;b=1-this.b;d=this.a;e=$doc.createElement(kg);
e.innerHTML=jG;c=$doc.createElement(wg);for(var f=0;f<d;f++){var g=e.cloneNode(!0);c.appendChild(g)}a.appendChild(c);for(d=1;d<b;d++)a.appendChild(c.cloneNode(!0));this.b=1}else for(;1<this.b;){a=this.b-1;c=b=void 0;c=this.a;for(b=0;b<c;++b)ZI(this,a,b,!1);this.c.removeChild(this.c.rows[a]);--this.b}}r(327,328,cG,cJ);_.a=0;_.b=0;
function fJ(a){var b;!a.a?b=null:a.a?b=a.a:b=a.a==(gJ(),hJ)?a.b.d==(dI(),fI)?(vu(),yu):a.b.d==eI?(vu(),zu):(vu(),Au):a.b.d==(dI(),fI)?(vu(),zu):a.b.d==eI?(vu(),yu):(vu(),Bu);b!=a.c&&(a.c=b,a.ob.style[mg]=!a.c?l:a.c.a)}r(331,307,wh);_.a=null;_.b=null;_.c=null;function iJ(){this.ob=$doc.createElement(rd);this.b=new YI(this.ob);this.ob[Wc]="gwt-Label"}function jJ(){iJ.call(this);XI(this.b,Kg,!1);fJ(this)}
r(330,331,{14:1,16:1,18:1,19:1,21:1,22:1,23:1,24:1,25:1,26:1,27:1,28:1,29:1,31:1,32:1,33:1,37:1,38:1,39:1,40:1,41:1,42:1,43:1,44:1,45:1,46:1,48:1,50:1,59:1,70:1,71:1,74:1,78:1,81:1,82:1,84:1},iJ,jJ);_.Zc=ei;_.$c=ey;_._c=Av;_.ad=xw;function kJ(a){var b=$doc.createElement(rd);cI(ag,b.tagName);this.ob=b;this.b=new YI(this.ob);this.ob[Wc]="gwt-HTML";XI(this.b,a,!0);fJ(this)}
r(329,330,{14:1,16:1,18:1,19:1,21:1,22:1,23:1,24:1,25:1,26:1,27:1,28:1,29:1,31:1,32:1,33:1,37:1,38:1,39:1,40:1,41:1,42:1,43:1,44:1,45:1,46:1,48:1,50:1,54:1,59:1,69:1,70:1,71:1,74:1,78:1,81:1,82:1,84:1},kJ);function lJ(a){for(;++a.b<a.d.c&&!(null!=as(a.d,a.b)););}function aJ(a){this.c=a;this.d=this.c.i.b;lJ(this)}r(332,1,{},aJ);_.jd=function(){return this.b<this.d.c};_.kd=function(){var a;if(this.b>=this.d.c)throw new At;a=as(this.d,this.b);this.a=this.b;lJ(this);return a};
_.ld=function(){var a;if(0>this.a)throw new Sv;a=as(this.d,this.a);Ys(a);this.a=-1};_.a=-1;_.b=-1;_.c=null;function dJ(a){this.a=a}r(333,1,{},dJ);_.a=null;function eJ(a){this.b=a}r(334,1,{},eJ);_.a=null;_.b=null;function gJ(){gJ=s;hJ=new mJ}var hJ;function mJ(){}r(336,1,{},mJ);function nJ(){nJ=s;new xl}function oJ(a,b,c,d,e){nJ();this.a=new pJ(this,a,b,c,d,e);this.ob[Wc]="gwt-Image"}function qJ(a,b,c,d,e){nJ();oJ.call(this,(Er(),new Cr(a)),b,c,d,e)}
r(340,307,{14:1,16:1,18:1,19:1,21:1,22:1,23:1,24:1,25:1,26:1,27:1,28:1,29:1,31:1,32:1,33:1,37:1,38:1,39:1,40:1,41:1,42:1,43:1,44:1,45:1,46:1,48:1,50:1,59:1,71:1,74:1,78:1,81:1,82:1,84:1},oJ,qJ);_.Zc=ei;_.$c=ey;_._c=Av;_.ad=xw;_.md=function(a){32768==Pr(a.type)&&this.a&&(this.ob.__gwtLastUnhandledEvent=l);Ws(this,a)};_.Fd=function(){var a=this.a;H(ye,Pm(this.ob,"__gwtLastUnhandledEvent"))&&(a.f=new rJ(a,this),ym((vm(),wm),a.f))};_.a=null;r(342,1,{});_.f=null;function sJ(){sJ=s;Tv()}
function pJ(a,b,c,d,e,f){var g,j;sJ();this.b=c;this.c=d;this.e=e;this.a=f;this.d=b;g=$doc.createElement(ag);j=new mI;lI(lI(lI(j,new oI("width:"+e+(bo(),wf)+gb)),new oI("height:"+f+KG)),new oI("background:url("+b.a+") no-repeat "+-c+"px "+-d+KG));!tJ&&(tJ=new uJ);b=Uv;c=new oI((new oI(j.a.a.a)).a);j=new nI;j.a.a+="<img onload='this.__gwtLastUnhandledEvent=\"load\";' src='";b=wI(b.a);Bl(j.a,b);j.a.a+="' style='";b=wI(c.a);Bl(j.a,b);j.a.a+="' border='0'>";j=new pI(j.a.a);g=(Qm(g,j.a),Sm(g));a.jb&&(a.ob.__listener=
null);if(a.ob&&(j=a.ob,b=j.parentNode))b.insertBefore(g,j),b.removeChild(j);a.ob=g;a.jb&&(a.ob.__listener=a);-1==a.kb?Cs(a.ob,133333119|(a.ob.__eventBits||0)):a.kb|=133333119}r(341,342,{},pJ);_.a=0;_.b=0;_.c=0;_.d=null;_.e=0;function rJ(a,b){this.a=a;this.b=b}r(343,1,{},rJ);_.Cc=function(){var a,b;this.b.a!=this.a||this!=this.a.f||(this.a.f=null,this.b.jb?(a=(b=$doc.createEvent("HTMLEvents"),b.initEvent(ye,!1,!1),b),this.b.ob.dispatchEvent(a)):this.b.ob.__gwtLastUnhandledEvent=ye)};_.a=null;_.b=null;
function vJ(a){this.a=a}r(346,345,$h,vJ);_.Xc=function(){};function VI(a){return function(){this.__gwt_resolve=wJ;return a.wd()}}function wJ(){throw"A PotentialElement cannot be resolved twice.";}function xJ(){Cv();var a=$doc.createElement("textarea");!Ir&&(Ir=new Hr);!Gr&&(Gr=new Fr);this.ob=a;this.ob[Wc]="gwt-TextArea"}r(369,370,ai,xJ);
function yJ(a,b){var c,d;c=$doc.createElement(wg);d=$doc.createElement(kg);d[xc]=a.a.a;d.style[Fg]=a.b.a;var e=(Kr(),Lr(d));c.appendChild(e);Jr(a.d,c);ut(a,b,d)}function zJ(){su.call(this);this.a=(vu(),Cu);this.b=(Du(),Gu);this.e[Sc]=Ya;this.e[Rc]=Ya}r(378,323,Jh,zJ);_.Hd=function(a){var b;b=Tm(a.ob);(a=yt(this,a))&&this.d.removeChild(Tm(b));return a};function AJ(a,b){if(0>b||b>=a.c)throw new xt;return a.a[b]}var tJ=null;function uJ(){}r(382,1,{},uJ);
function BJ(a,b,c){Vv();Wv.call(this,(Er(),new Cr(a)),b,0,c,16)}r(383,316,{},BJ);function CJ(a,b,c,d){0==--a.ic&&(a.tc!=a.le()&&(d|=4),!a.sc&&(d|=2),0<d&&new DJ(a,b,c,vr(d)))}function EJ(a){return!a.ec&&a.lc?EJ(a.lc):a.ec}function FJ(a){0==a.ic++&&(a.tc=a.le(),a.sc=!0,a.re())}function GJ(a){return!a.gc?(a.ke(),!0):!1}function Z(a,b){var c;c=a.ec;a.ec=b;b==c||b&&E(c,91)&&c.a==b.a||a.mc.rg(b)}function HJ(a,b){b==a.gc||b&&b==a.gc||(a.gc=b,a.ke(),a.mc.sg(b),a.le()&&a.te())}
function IJ(a){a.qc||(FJ(a),JJ(a,!0),Dw(a),a.qc=!0,new nw(a,102),CJ(a,a,a.lc,0),hw(a),a.mc.ug(a))}r(399,1,vh);_.Zd=Vo;_._d=function(){return EJ(this)};_.me=yw;_.re=ww;_.se=function(){return GJ(this)};_.te=ww;_.ve=function(a,b){this.we(this.uc,this.vc,a,b)};
function $(a,b,c){var d;if(-1>a._b.a.c)throw new Ji("Missing message: awt.12A");if(E(b,93)){if(b==a)throw new Ji("Missing message: awt.12B");a:{if(a&&!E(a,104))for(d=a.lc;d;){if(d==b){d=!0;break a}if(E(d,104))break;d=d.lc}d=!1}if(d)throw new Ji("Missing message: awt.12C");if(E(b,104))throw new Ji("Missing message: awt.12D");}if(b.lc){d=b.lc;if(!b)throw new xy;var e=Zu(d._b.a,b),f;f=as(d._b.a,e);d.ac&&d.ac.Fe(f);KJ(d,e);new LJ(d,301,f)}d=a._b.a.c;FJ(b);Px(a._b.a,d,b);b.lc=a;b.me(!0);gw(a);a.ac&&E(a.ac,
98)&&(a.ac.n=!1);d=(CJ(b,b,a,1),d);try{if(a.ac)if(E(a.ac,98)){if(!b)throw new kq("Missing message: awt.185");if(null==c||null!=c)MJ(a.ac,c,b);else throw new Ji("Missing message: awt.92");}else a.ac.Ae(null==c?null:c,b)}catch(g){g=nm(g);if(E(g,126))throw b=g,KJ(a,d),b;throw g;}b.ue();new LJ(a,300,b)}function JJ(a,b){var c;for(c=a._b.a.c-1;0<=c;--c)as(a._b.a,c).me(b)}function KJ(a,b){var c;c=as(a._b.a,b);FJ(c);c.me(!1);yD(a._b.a,b);c.lc=null;gw(a);a.ac&&E(a.ac,98)&&(a.ac.n=!1);CJ(c,c,a,1)}
function NJ(a){var b=(Cx(),Dx);HJ(a,b);for(b=0;b<a._b.a.c;++b)as(a._b.a,b).se()}r(398,399,Hh);_.me=function(a){JJ(this,a)};_.re=function(){var a;for(a=0;a<this._b.a.c;++a)FJ(as(this._b.a,a))};_.se=function(){var a;if(!GJ(this))return!1;for(a=0;a<this._b.a.c;++a)as(this._b.a,a).se();return!0};r(396,397,Hh);_.te=function(){Mw(this)};_.ve=UC;function OJ(){}r(405,406,Th,OJ);
function PJ(){PJ=s;QJ=new sq;RJ=new jw(0,0);tq(QJ,rG);tq(QJ,tG);tq(QJ,qG);tq(QJ,"Last");tq(QJ,tb);tq(QJ,wG);tq(QJ,yG);tq(QJ,zG);tq(QJ,sG)}function MJ(a,b,c){var d;if(null==b)d=tb;else if(d=b,!us(QJ.a,b))throw new Ji(SJ());Sq(Bq(a.c,d))===Sq(c)&&Sq(Bq(a.b,c))===Sq(d)||((b=Bq(a.c,d))&&TJ(a,b,d),iD(a.a.Kd(),c)&&TJ(a,c,d),b=a.a,new UJ(c,b.a.a),++b.b,D(a.b,c,d),D(a.c,d,c))}function VJ(a,b){return new jw(Oi(b[1].b,Oi(b[2].b,b[4].b+b[0].b+b[3].b+a.e)),b[1].a+b[2].a+Oi(b[0].a,Oi(b[4].a,b[3].a))+a.k)}
function TJ(a,b,c){jD(a.a,b);Dq(a.b,b);Dq(a.c,c)}function WJ(a,b){if(!a.n){a.n=!0;var c,d,e;XJ(a.f,RJ);XJ(a.i,RJ);XJ(a.o,null);a.p=0;for(d=YJ(a.a,0);d.b!=d.d.a;){c=ZJ(d);e=Bq(a.b,c);var f=b.kc;e=Jl(e,tb)?0:Jl(e,wG)?1:Jl(e,yG)?2:Jl(e,zG)?4:Jl(e,sG)?3:Jl(e,rG)?f.a?4:3:Jl(e,qG)?f.a?3:4:Jl(e,tG)?1:2;c.qc?a.o[e]||(dm(a.o,e,c),++a.p,a.f[e]=c.de(),a.i[e]=c.fe()):a.o[e]||(a.f[e]=c.de(),a.i[e]=c.fe())}0!=a.p&&(c=-1,a.o[1]&&++c,a.o[2]&&++c,a.o[0]||a.o[4]||a.o[3]?(a.e=(a.p-c-2)*a.d,++c):a.e=0,a.k=c*a.j)}}
function $J(){PJ();aK.call(this,0)}function aK(a){PJ();pw();this.a=new bK;this.b=new xl;this.c=new xl;this.d=a;this.j=0;this.n=!1;this.o=x(FD,m,92,5,0);this.f=x(cK,m,94,5,0);this.i=x(cK,m,94,5,0);this.p=this.e=this.k=0}r(408,1,{98:1,117:1},$J,aK);_.Ae=function(a,b){MJ(this,a,b)};_.Be=function(){this.n=!1};
_.Ce=function(a){WJ(this,a);if(0!=this.p)if(a=Aw(a),0>=a.b||0>=a.a){var b,c;for(c=0;5>c;++c)(b=this.o[c])&&b.we(a.c,a.d,0,0)}else{var d,e;b=a.c;e=a.d;this.o[1]&&(this.o[1].ve(a.b,this.i[1].a),this.o[1].xe(a.c,a.d,a.b,this.i[1].a,2,!0),e+=this.i[1].a+this.j);c=a.a-this.i[1].a-this.i[2].a-this.k;c=0<c?c:0;this.o[4]&&(this.o[4].ve(this.i[4].b,c),this.o[4].xe(a.c,e,this.i[4].b,c,2,!0),b+=this.i[4].b+this.d);d=a.b-this.i[4].b-this.i[3].b-this.e;this.o[0]&&this.o[0].we(b,e,0<d?d:0,c);this.o[2]&&(this.o[2].ve(a.b,
this.i[2].a),this.o[2].xe(a.c,a.d+a.a-this.i[2].a,a.b,this.i[2].a,2,!0));this.o[3]&&(this.o[3].ve(this.i[3].b,c),this.o[3].xe(a.c+a.b-this.i[3].b,e,this.i[3].b,c,2,!0))}};_.De=function(a){var b;b=this.n;WJ(this,a);this.n=b;return 0==this.p?zw(a,new jw(0,0)):zw(a,VJ(this,this.f))};_.Ee=function(a){var b;b=this.n;WJ(this,a);this.n=b;return zw(a,VJ(this,this.i))};_.Fe=function(a){var b;b=Bq(this.b,a);null!=b&&TJ(this,a,b)};_.tS=function(){return dK.d+"[hgap="+this.d+",vgap="+this.j+kc};_.a=null;
_.b=null;_.c=null;_.d=0;_.e=0;_.f=null;_.i=null;_.j=0;_.k=0;_.n=!1;_.o=null;_.p=0;var RJ,QJ;function eK(a){ow.call(this);this.mc=(pw(),new fK(a,this))}r(409,399,{89:1,92:1,99:1,111:1,117:1},eK);_.$d=function(){return Qc+this.oc.b.a++};_.ae=fy;_.ue=ww;r(411,1,{});r(410,411,{},function(){});function gK(a){if(!a.k){FJ(a);a.Rd();var b,c;for(b=0;b<a.o.c;++b)(c=as(a.o,b))&&gK(c);JJ(a,!1);a.k=!0;CJ(a,a,a.lc,0);new hK(a,202)}}
function iK(a){var b,c;a.qc&&(a.mc.Rd(),a.qc=!1);for(b=0;b<a.o.c;++b)(c=as(a.o,b))&&c.Rd()}function jK(a){!cw(a)&&NJ(a);var b=kw(a);a.we(a.uc,a.vc,b.b,b.a);Dw(a)}function kK(a,b){a.p!=b&&(a.p=b)}r(422,398,fG);_.ee=function(){return new uw(this.n.d,this.n.b,this.n.a,this.n.c)};_.Rd=function(){iK(this)};_.le=function(){return this.mc.c.gb};_.we=function(a,b,c,d){mw(this,a,b,c,d);this.fc=0};_.xe=function(a,b,c,d,e,f){e=c!=this.rc||d!=this.hc;mw(this,a,b,c,d);this.qc&&e&&!f&&Dw(this)};_.k=!1;_.p=!1;
function lK(a){Ew.call(this);this.q=new OJ;this.o=new vi;this.n=new uw(0,0,0,0);this.qc=!1;Cw(this,new $J);this.mc&&mK(this.mc.c.H.b,a);this.mc&&nK(this.mc.c,!0);kK(this,!0)}r(421,422,fG);_.ze=function(){return new uw(this.n.d,this.n.b,this.n.a,this.n.c)};_.he=function(){return Jm(this.mc.c.ob)};_.ie=function(){return Mm(this.mc.c.ob)};_.je=function(){this.mc=new oK((pw(),l),this)};
function pK(a){var b,c;c=Oi(0,a.d);0==c?(b=a.a,c=~~(a.b.length/b),0<a.b.length%b&&++c):(c=a.d,b=~~(a.b.length/c),0<a.b.length%c&&++b);return new jw(b,c)}function qK(a,b,c){var d,e,f,g,j,h;a.b=zx(b._b);if(0==a.b.length)return new sx;g=pK(a);j=h=0;for(e=a.b,b=0,f=e.length;b<f;++b)d=e[b],d=c?d.fe():d.de(),h=Oi(h,d.b),j=Oi(j,d.a);return new jw(h*g.b+a.c*(g.b-1),j*g.a+a.e*(g.a-1))}
function rK(a,b,c,d,e){var f,g,j,h;j=d.length;a-=(j-1)*c;for(g=0,h=0;g<j;++g,b+=c)f=I(a*((g+1)/j))-h,d[g]=f,e[g]=h+b,h+=f}function sK(a){pw();this.d=0;this.a=1;this.e=a;this.c=0}r(425,1,Th,sK);_.Ae=UC;
_.Ce=function(a){var b,c;this.b=zx(a._b);if(0!=this.b.length&&(b=Aw(a),!(0>=b.b||0>=b.a))){c=pK(this);var d=c.b;c=c.a;var a=a.kc.a,e,f,g,j,h,n,t;f=x(G,q,-1,d,1);e=x(G,q,-1,d,1);h=x(G,q,-1,c,1);n=x(G,q,-1,c,1);rK(b.b,b.c,this.c,f,e);rK(b.a,b.d,this.e,h,n);b=0;j=0;a:for(;b<c;++b)for(g=0;g<d;++g)if(t=a?g:d-g-1,this.b[j].we(e[t],n[b],f[t],h[b]),++j==this.b.length)break a}};_.De=function(a){return zw(a,qK(this,a,!1))};_.Ee=function(a){return zw(a,qK(this,a,!0))};_.Fe=yw;
_.tS=function(){return tK.d+"[hgap="+this.c+",vgap="+this.e+",rows="+this.d+",cols="+this.a+kc};_.a=0;_.b=null;_.c=0;_.d=0;_.e=0;function uK(a,b){ow.call(this);this.mc=(pw(),new vK(a));this.a=b;var c=this.mc;switch(b){case 1:var c=c.a,d=(vu(),wu);c.a=d;fJ(c);break;case 0:c=c.a;d=(vu(),yu);c.a=d;fJ(c);break;case 2:c=c.a,d=(vu(),zu),c.a=d,fJ(c)}}r(430,399,vh,uK);_.ae=fy;
_.pe=function(){var a=(null==this.jc&&(this.jc=aw(this)),this.jc)+va+this.uc+va+this.vc+va+this.rc+Kg+this.hc+(this.qc?l:",hidden")+",align=",b;b=se;switch(this.a){case 1:b=Tc;break;case 2:b=Kf}return a+b+",text=null"};_.a=0;function wK(a){var b=a.b;this.a=a.a;this.b=b}r(434,435,{101:1,109:1,117:1},wK);r(444,399,vh);_._d=ou;function xK(a,b){var c=a.mc;Bv(c.a,b);c.e.a=-1;c.e.b=-1}function LJ(a,b,c){Qw();nw.call(this,a,b);this.a=c}r(454,453,Th,LJ);
_.pe=function(){var a;switch(this.d){case 300:a="COMPONENT_ADDED";break;case 301:a="COMPONENT_REMOVED";break;default:a="unknown type"}a+=",child=";var b=this.a;null==b.jc&&(b.jc=b.$d());return a+b.jc};_.a=null;function DJ(a,b,c,d){Qw();Ow.call(this,a);this.d=1400;this.b=b;this.c=c;this.a=d}r(455,400,Th,DJ);
_.pe=function(){var a;switch(this.d){case 1400:a="HIERARCHY_CHANGED";break;case 1401:a="ANCESTOR_MOVED";break;case 1402:a="ANCESTOR_RESIZED";break;default:a="unknown type"}a+=" (";1400==this.d&&(yr(kI(this.a,Pg))&&(a+="PARENT_CHANGED,"),yr(kI(this.a,Qg))&&(a+="DISPLAYABILITY_CHANGED,"),yr(kI(this.a,Sg))&&(a+="SHOWING_CHANGED,"));return a+"changed="+this.b+",changedParent="+this.c+sa};_.a=Og;_.b=null;_.c=null;r(456,1,gG);function hK(a,b){Qw();nw.call(this,a,b);this.c=null;this.a=this.b=0}
r(457,453,Th,hK);
_.pe=function(){var a;switch(this.d){case 200:a="WINDOW_OPENED";break;case 201:a="WINDOW_CLOSING";break;case 202:a="WINDOW_CLOSED";break;case 203:a="WINDOW_ICONIFIED";break;case 204:a="WINDOW_DEICONIFIED";break;case 205:a="WINDOW_ACTIVATED";break;case 206:a="WINDOW_DEACTIVATED";break;case 207:a="WINDOW_GAINED_FOCUS";break;case 208:a="WINDOW_LOST_FOCUS";break;case 209:a="WINDOW_STATE_CHANGED";break;default:a="unknown type"}return a+",opposite="+this.c+",oldState="+this.b+",newState="+this.a};_.a=0;
_.b=0;_.c=null;r(462,100,Kh);function yK(){}function zK(a){this.f=a}r(461,462,{112:1,117:1,124:1,132:1},yK,zK);function AK(){AK=s;BK=new CK}function DK(a){var b;if(a.k){var c;b=new nI;Bl(b.a,a.f);b.a.a+=eb;c=a.a;null!=c&&0<c.length&&(b.a.a+=mG,Bl(b.a,a.a));c=a.b;a=a.j;null!=c&&Bl(b.a,c);null!=a&&(b.a.a+=la,Bl(b.a,a));b=b.a.a}else b="unknown protocol("+a.f+")://"+a.c+a.b;return b}
function EK(a){AK();var b,c,d;if(null==a)throw new yK;a=Ms(a);try{d=Ks(a,Ls(58))}catch(e){e=nm(e);if(E(e,128))throw new zK(Cl(e));throw e;}c=Ks(a,Ls(91));if(0<=d&&(-1==c||d<c)){this.f=a.substr(0,d-0);b=this.f.charCodeAt(0);b=97<=b&&122>=b||65<=b&&90>=b;for(c=1;b&&c<this.f.length;++c)b=this.f.charCodeAt(c),b=97<=b&&122>=b||65<=b&&90>=b||48<=b&&57>=b||43==b||45==b||46==b;if(b){c=this.f;FK();var f,g,j;j=c.length;b=new GK;for(g=0;g<j;++g){f=c.charCodeAt(g);if(65<=f&&90>=f){var h=b.a;f=String.fromCharCode(f+
32&65535)}else h=b.a,f=String.fromCharCode(f);h.a+=f}this.f=b.a.a}else this.f=null,d=-1}if(null==this.f)throw new zK(vG+a);if(!this.k&&(this.k=Bq(BK,this.f),this.k||(this.k=(pw(),new HK))&&D(BK,this.f,this.k),!this.k))throw new zK(vG+a);try{c=a;var n=++d,t=a.length,v,u,w,B,J,C,K,ya,Ob,ja,R,sc,Jc,Cg,vb,Yd,Zd,$d,bb,Kc,Eb;if(t<n||0>t){if(-2147483647>=t&&(n>=c.length||0>n)||!(0>n||n>=c.length)&&c.indexOf(mG,n)==n&&-1==$F(c,Ls(47),n+2))throw new IK(t);}else{R=c.substr(n,t-n);t-=n;C=0;K=this.c;sc=this.e;
$d=this.j;B=this.d;vb=this.i;v=this.a;Eb=this.n;bb=$F(R,Ls(35),0);if(0==R.indexOf(mG)&&0!=R.indexOf("////")){Ob=2;sc=-1;C=$F(R,Ls(47),2);Zd=$F(R,Ls(63),2);-1!=Zd&&(-1==C||C>Zd)&&(C=Zd);-1==C&&(C=t,B=l);ya=C;-1!=bb&&bb<C&&(ya=bb);var yd=Ls(64);Kc=R.lastIndexOf(yd,ya);v=R.substr(2,ya-2);-1<Kc&&(Eb=R.substr(2,Kc-2),Ob=Kc+1);Jc=$F(R,Ls(58),-1==Kc?Ob:Kc);w=Ks(R,Ls(93));if(-1!=w)try{R.length>w+1?(u=R.charCodeAt(w+1),58==u?Jc=w+1:Jc=-1):Jc=-1}catch(Af){if(Af=nm(Af),!E(Af,124))throw Af;}-1==Jc||Jc>C?K=R.substr(Ob,
ya-Ob):(K=R.substr(Ob,Jc-Ob),Cg=R.substr(Jc+1,ya-(Jc+1)),0==Cg.length?sc=-1:sc=EA(Cg,10))}-1<bb&&($d=R.substr(bb+1,t-(bb+1)));J=-1==bb?t:bb;var bc=Ls(63);Yd=R.lastIndexOf(bc,J);-1<Yd?(vb=R.substr(Yd+1,J-(Yd+1)),0==Yd&&null!=B&&(H(B,l)?B=Wa:B.indexOf(Wa),ja=bw(B,Ls(47))+1,B=B.substr(0,ja-0)),J=Yd):0!=bb&&(vb=null);-1<C&&(C<t&&47==R.charCodeAt(C)?B=R.substr(C,J-C):J>C&&(null==B?B=l:H(B,l)?B=Wa:B.indexOf(Wa),ja=bw(B,Ls(47))+1,0==ja?B=R.substr(C,J-C):B=B.substr(0,ja-0)+R.substr(C,J-C)));null==B&&(B=l);
null==K&&(K=l);d=K;var Pe;Pe=B;null!=vb&&!H(vb,l)&&(null!=B?Pe=B+lb+vb:Pe=lb+vb);null==this.f&&(this.f=this.f);this.c=d;this.b=Pe;this.e=sc;this.j=$d;var zd;null!=this.c&&0<this.c.length&&(this.a=this.c,-1!=this.e&&(this.a=this.a+eb+this.e));null!=this.c&&-1<(zd=bw(this.c,Ls(64)))?(this.n=this.c.substr(0,zd-0),this.c=Ns(this.c,zd+1)):this.n=null;null!=this.b&&-1<(zd=Ks(this.b,Ls(63)))?(this.i=Ns(this.b,zd+1),this.d=this.b.substr(0,zd-0)):(this.i=null,this.d=this.b);this.a=v;this.n=Eb;this.d=B;this.i=
vb}}catch(Ad){Ad=nm(Ad);if(E(Ad,124))throw new zK(Cl(Ad));throw Ad;}if(-1>this.e)throw new zK("incorrect port: "+this.e);}r(463,1,Th,EK);_.tS=function(){return DK(this)};_.a=null;_.b=null;_.c=null;_.d=null;_.e=-1;_.f=null;_.i=null;_.j=null;_.k=null;_.n=null;var BK;r(464,1,{});function CK(){zv(this)}r(465,466,Zh,CK);function JK(a){this.f=a}r(497,462,Kh,JK);function cI(a,b){return null==b?!1:a==b||a.toLowerCase()==b.toLowerCase()}function nI(){this.a=new Fm}function GK(){this.a=new Fm}
r(516,1,Ih,nI,GK);function IK(a){this.f="String index out of range: "+a}r(517,507,Bh,IK);function QI(){}r(519,99,Bh,QI);r(532,527,Lh);_.ag=function(a,b){var c;c=YJ(this,a);var d=c.d;new UJ(b,c.b);++d.b;++c.a;c.c=null};_.bg=function(a){var b;b=YJ(this,a);try{return ZJ(b)}catch(c){c=nm(c);if(E(c,137))throw new WC("Can't get element "+a);throw c;}};_.Kd=function(){return YJ(this,0)};
_.eg=function(a){var b,c;b=YJ(this,a);try{c=ZJ(b)}catch(d){d=nm(d);if(E(d,137))throw new WC("Can't remove element "+a);throw d;}KK(b);return c};function XJ(a,b){var c=a.length,d;for(d=0;d<c;++d)dm(a,d,b)}function YJ(a,b){var c,d;(0>b||b>a.b)&&qD(b,a.b);if(b>=a.b>>1){d=a.a;for(c=a.b;c>b;--c)d=d.b}else{d=a.a.a;for(c=0;c<b;++c)d=d.a}return new LK(a,b,d)}function bK(){this.a=new MK;this.b=0}r(540,532,Ch,bK);_.Wf=function(a){new UJ(a,this.a);++this.b;return!0};_.dg=function(a){return YJ(this,a)};
_.Qe=function(){return this.b};_.a=null;_.b=0;function ZJ(a){if(a.b==a.d.a)throw new At;a.c=a.b;a.b=a.b.a;++a.a;return a.c.c}function KK(a){if(!a.c)throw new Sv;a.b==a.c?a.b=a.c.a:--a.a;var b=a.c;b.a.b=b.b;b.b.a=b.a;b.a=b.b=b;a.c=null;--a.d.b}function LK(a,b,c){this.d=a;this.b=c;this.a=b}r(541,1,{},LK);_.jd=function(){return this.b!=this.d.a};_.fg=function(){return this.b.b!=this.d.a};_.kd=function(){return ZJ(this)};
_.gg=function(){if(this.b.b==this.d.a)throw new At;this.c=this.b=this.b.b;--this.a;return this.c.c};_.ld=function(){KK(this)};_.a=0;_.b=null;_.c=null;_.d=null;function MK(){this.a=this.b=this}function UJ(a,b){this.c=a;this.a=b;this.b=b.b;b.b.a=this;b.b=this}r(542,1,{},MK,UJ);_.a=null;_.b=null;_.c=null;function NK(a){a.mc.c.gb&&gK(a)}function OK(a){var b;if(a.mc.c.gb){b=dw(a);var c=a.j,d=b.b;c.a=b.a;c.b=d}iK(a)}function PK(a,b,c){a.a+=b;a.b+=c;a.a=0>a.a?0:a.a;a.b=0>a.b?0:a.b}
function QK(a){var b=a.j;RK(a.mc.c,b.a,b.b);!cw(a)&&NJ(a);IJ(a)}function SK(){lK.call(this,l);this.i=new eK(this.hg());Sw(this.q,new TK(this))}r(548,421,fG);_.Zd=function(a,b){return Sq(a.f)===Sq(this.i)?(OK(this),!0):this.ig(a,b)};_.hg=function(){return"Close"};_.ig=Vo;_.Rd=function(){OK(this)};_.i=null;_.j=null;function TK(a){this.a=a}r(552,456,gG,TK);_.a=null;
function UK(a,b){var c;vp();var d;SK.call(this);this.c=new eK("Help");new eK("Home");this.d=b;Z(this,(ez(),gz));this.mc&&nK(this.mc.c,!1);kK(this,!1);d=dw(b);if(1==a)this.e||(this.e=new wK(d),PK(this.e,-30,0)),this.j=this.e,c=rz(b),this.mc&&mK(this.mc.c.H.b,ac),Cw(this,new aK(2)),this.f=new cy(c+"     "),$(this,this.f,tb),d=new Hw,$(d,this.i,null),this.d.Mb&&(c=new eK("Submit"),$(d,c,null)),$(this,d,yG),xK(this.f,Ms(Pm(this.f.mc.a.ob,Bg))),this.mc&&nK(this.mc.c,!0),kK(this,!0);else if(2==a)this.b||
(this.b=new wK(d),PK(this.b,-50,13*I(b.bb)-80)),this.j=this.b,this.mc&&mK(this.mc.c.H.b,"Nonstandard atom"),Cw(this,new aK(2)),c=new Hw,$(c,new uK("atomic SMILES",1),null),$(this,c,wG),c=Cb,wp&&(c=Pm(wp.mc.a.ob,Bg)),wp=new dy(c,8),$(this,wp,tb),c=new Hw,$(c,this.i,null),$(this,c,yG);else{this.a||(this.a=new wK(d),PK(this.a,5*I(b.bb),0));var e,f;d="About "+(ez(),KB);this.mc&&mK(this.mc.c.H.b,d);Cw(this,new sK(0));Z(this,gz);$(this,new uK(KB+" Molecular Editor v2015-02-09",1),null);$(this,new uK("Peter Ertl and Bruno Bienfait",
1),null);for(c=fz,d=0,f=c.length;d<f;++d)e=c[d],e=new uK(e,1),HJ(e,this.d.B),$(this,e,null);c=new Hw;$(c,this.c,null);$(c,this.i,null);$(this,c,null);this.j=this.a}jK(this);c=this.j;RK(this.mc.c,c.a,c.b);!cw(this)&&NJ(this);IJ(this)}r(563,548,fG,UK);_.ig=function(a){var b,c;if(a.f===this.c){try{b=new EK(this.d.M),c=DK(b),$wnd.open(c,"_blank",l)}catch(d){if(d=nm(d),E(d,112))a=this.d,b=d.f,a.pb=!0,a.O="ERROR - "+b,yz(a);else throw d;}return!0}return!1};_.a=null;_.b=null;_.d=null;_.e=null;_.f=null;
function VK(a,b,c){a=new WK(b,c,a);if(!b.Zd(a,c))for(b=b.lc;b&&!b.Zd(a,c);)b=b.lc}function WK(a,b,c){op.call(this,a,0,b);this.a=c}r(590,417,Th,WK);r(607,307,wh);_.qd=Ny;_.rd=fi;function XK(a){var b;b=a.pg();if(!b){var c;if(c=a.mg()){b=hF(c.a);var d=b.b,e=b.a;Hs(c.Je(),d,e);c=hF(c.a);b=new jw(c.b-b.b,c.a-b.a)}else b=new jw(0,0);a.tg(b)}return b}function YK(a,b){var c;b&&(c=YE(b),a.og().ob.style[BG]=c)}r(610,1,{});_.mg=ou;_.ng=function(a){this.rg(a._d())};_.og=function(){return this.Je()};_.pg=function(){return ZK};
_.Rd=ww;_.qg=function(a){this.sg(cw(a))};_.rg=Qs;_.tg=function(a){ZK=a};_.ug=yw;var ZK=null;function fK(a,b){jF();lF.call(this);this.a=new TI(a);var c=l;this.a.ud()[Wc]=c;Ss(this.a,new $K(this,b),(Po(),Po(),Qo))}r(609,610,{},fK);_.Je=JB;_.rg=Qs;_.a=null;function $K(a,b){this.a=a;this.b=b}r(611,1,{},$K);_.Yc=function(a){pw();VK(a,this.b,this.a.a.ob.textContent)};_.a=null;_.b=null;function aL(a,b){var c,d;YK(a,b._d());for(d=new vq(b._b.a);d.b<d.d.Qe();)c=wq(d),c.qc&&c.mc.ng(c)}
function bL(a,b){var c,d,e,f,g,j,h;Hs(a.d,b.ge(),b.ce());for(d=new vq(b._b.a);d.b<d.d.Qe();)c=wq(d),c.qc&&(e=c.mc,e.qg(c),j=c.he(),h=c.ie(),g=c.ge(),f=c.ce(),0<g&&0<f&&(c=e.Je(),g-=XK(e).b,f-=XK(e).a,Hs(e.Je(),g,f),!c.nb&&a.d.Ld(c),a.d.Md(c,j,h)))}r(614,610,{});_.ng=function(a){aL(this,a)};_.qg=function(a){bL(this,a)};function vK(a){jF();lF.call(this);var b=this.a=new iJ;XI(b.b,a,!1);fJ(b);this.e.a=-1;this.e.b=-1}r(615,610,{},vK);_.Je=JB;
_.Ne=function(){var a;a=(this.a.b.c?Sm(this.a.b.a):this.a.b.a).textContent;return null==a||0==a.length};_.a=null;r(618,610,{});_.mg=function(){var a;a=new gy;Bv(a.a,"123456789");a.e.a=-1;a.e.b=-1;return a};_.pg=function(){return cL};_.tg=function(a){cL=a};var cL=null;r(619,614,{});function dL(a){var b;b=new BH(Om(a.ob,kf),Om(a.ob,jf));a=new BH(Om(a.S.ib.ob,kf),Om(a.S.ib.ob,jf));return F(G,q,-1,[b.b-a.b,b.a-a.a])}
function eL(a){null!=a.Q&&null!=a.P?(Is(a,a.Q,a.P),a.Q=a.P=null):null!=a.Q?(fL(a,a.Q),a.Q=null):null!=a.P&&(gL(a,a.P),a.P=null);aH(a.R)}function hL(a){a.jb?a.yg(EH(a.S.ib)):(a.Ud(),hL(a))}function gL(a,b){var c;a.jb?(c=dL(a),a.yg(new BH(-1,iL(b,!1)-c[1]))):a.P=b}function jL(a,b){var c;b!=a.Pd()&&(c=a.S.ib,RI(c),kL(c,b,c.ob,c.p.c,!0))}function fL(a,b){var c;a.jb?(c=dL(a),a.yg(new BH(iL(b,!0)-c[0],-1))):a.Q=b}r(622,309,dG);_.vg=function(){var a,b;b=EH(this.S.ib);a=dL(this);b.b+=a[0];b.a+=a[1];return b};
_.Pd=function(){var a;a=this.S.ib;return 0!=a.p.c?lL(AJ(a.p,0)):null};_.wg=function(a){mL(this.S.ib,a)};_.Kd=function(){return new SI(this.S.ib)};_.xg=ot;_.Fd=function(){eL(this)};_.Yd=ot;_.Hd=function(a){return nL(this.S.ib,a)};_.yg=function(a){GH(this.S.ib,a)};_.xd=function(a){gL(this,a)};_.Qd=function(a){jL(this,a)};_.zd=function(a){fL(this,a)};_.P=null;_.Q=null;function oL(){oL=s;Ot();var a=(pL(),qL(),rL);sL=new oJ(a.d,a.b,a.c,a.e,a.a)}
function tL(a,b){if(0!=a.H.a.p.c&&lL(AJ(a.H.a.p,0)))throw new Vs("WindowPanel can only contain one child widget");uL(a,b)}function vL(a){try{a.v=!1;var b,c,d,e,f;d=a.gb;c=a._;d||(a.ob.style[Gg]=he,a._=!1,a.Ud());b=a.ob;b.style[se]=0+(bo(),wf);b.style[rg]=Za;e=cn()-Om(a.ob,kf)>>1;f=bn()-Om(a.ob,jf)>>1;RK(a,Oi(dn($doc)+e,0),Oi(en($doc)+f,0));d||((a._=c)?(pv(a.ob,If),a.ob.style[Gg]=Hg,ki(a.fb,200)):a.ob.style[Gg]=Hg)}finally{a.v=!0}}
function wL(a,b){var c;if(a.v){c=new js;a.lb&&qq(a.lb,c);a.I&&FH(a.q,a);xL(a.q.c,a);a.k=yL(a.q,a);try{Qt(a,b)}finally{mv(a.s.a),mv(a.r.a),mv(a.t.a),a.O&&Ii(a.O,a.q),a.B&&(a.B=!1)}}else Qt(a,b)}function zL(a,b,c){var d,e;e=a.nb;d=new cH(a,e);e.Md(a,d.a+b,d.d+c)}function AL(a,b,c){b=new BL(Tm(Sm(rs(rs(a.S.c,b),c))));at(b,a);Ss(b,a.n,(Po(),Po(),Qo));return b}function DH(a,b){a.I&&(0<=b.b&&(a.p=b.b),0<=b.a&&(a.o=b.a));GH(a.S.ib,b)}
function RK(a,b,c){var d,e;(e=a.q)?(d=CL(e.ob),Tt(a,b+(Jm(e.ob)+d[3]),c+(Mm(e.ob)+d[0]))):Tt(a,b,c)}function nK(a,b){a.I!=b&&(a.I=b,a.gb&&(b?HH(a.q,a):FH(a.q,a)))}function uL(a,b){if(b!=(0!=a.H.a.p.c?lL(AJ(a.H.a.p,0)):null)){RI(a.H.a);var c=a.H.a;kL(c,b,c.ob,c.p.c,!0)}}
function DL(a,b){var c;if(a.N!=b){c=a.N;a.N=b;a.jb&&c==(yH(),EL)&&(a.N=a.F);var d,e;if(a.O)for(e=new vq(a.O);e.b<e.d.Qe();)if(d=wq(e),b==(yH(),FL)){!d.b&&(d.b=new GL);d=a;var f=c,g=void 0,j=void 0;if(d.I&&f==(yH(),zH))g=d.q,j=d.E,d.H.c?(RK(d,j.c,j.d),DH(d,new BH(j.b,-1))):(RK(d,j.c,j.d),DH(d,new BH(j.b,j.a)),HH(g,d)),OG(g.c,d,d.H.b),zi(d.y,333);else if(!d.B&&f==(yH(),EL))d.ob.style[Gg]=Hg,yH()}else if(b==zH){!d.b&&(d.b=new GL);d=a;var f=c,h=j=g=void 0;if(d.I){j=d.q;g=CL(j.ob);h=d.E;if(d.H.c)h.c=Jm(d.ob)-
g[3]-Jm(j.ob),h.d=Mm(d.ob)-g[0]-Mm(j.ob),d.E=h,RK(d,0,0),HL(d,AH(j.ob).b,-1);else{if(f!=(yH(),EL))h.c=Jm(d.ob)-g[3]-Jm(j.ob),h.d=Mm(d.ob)-g[0]-Mm(j.ob),h.b=d.p,h.a=d.o,d.E=h;RK(d,0,0);GH(d,new IL(AH(j.ob)));FH(j,d)}d==d.q.a||JL(d);zi(d.y,333)}}else b==EL&&(!d.b&&(d.b=new GL),d=a,d.B||(d.F=c,d.ob.style[Gg]=he))}}function KL(a,b){a.ob.style[Lg]=b+1E4+(a.B?1E3:0)+l;(a.B||a.ab)&&null.Fg().Fg()}
function LL(a){if(!a.jb){a.s=Ts(a,a.q,(!ZH&&(ZH=new Gi),ZH));a.r=Ts(a,a.q,Fi?Fi:Fi=new Gi);a.t=Ts(a,a.q,(!aI&&(aI=new Gi),aI));var b=a.q;!a.O&&(a.O=new vi);yi(a.O,b);ZH&&(b=new YH(a),a.lb&&qq(a.lb,b));a.I&&HH(a.q,a);OG(a.q.c,a,a.H.b);a.k&&(Tt(a,a.k.a,a.k.b),a.k=null);Ut(a);JL(a)}}function JL(a){if(a!=a.q.a){var b;aI&&(b=new $H(a),a.lb&&qq(a.lb,b))}}
function ML(a,b,c){Ot();var d=(cu(),du);Wt.call(this,!1,"popup");this.T=d.a;this.R=new NL(this);d=new OL;d.ob[Wc]="mosaic-popupLayoutPanel";Lt(this.S,d);St(this);this.n=new PL(this);this.y=new QL(this);this.z=new RL(this);this.A=new SL(this);this.E=new TL;this.N=(yH(),FL);this.I=c;this.q=a;a=this.H=new UL(b);b=new VL;!a.d&&(a.d=new WL);yi(a.d,b);a=new XL(new qJ(sL.a.d.a,sL.a.b,sL.a.c,sL.a.e,sL.a.a));Ss(a,new YL(this),(Po(),Po(),Qo));b=this.H.b;b.b||(b.b=new Ku,b.b.ud()[Wc]="mosaic-Caption-iconBoxRight",
c=b.b,d=(Du(),Eu),c.c=d,c=b.f,ZL(c,b.b,new $L(2),c.p.c));if(0<b.b.p.c){c=b.b;if(0>c.p.c)throw new xt;d=Iu(c);As(c.b,(Kr(),Lr(d)),0);wt(c,a,d,0,!1)}else Hu(b.b,a);mL(b.f,null);Ss(this.H.b,new aM(this),(vH(),vH(),wH));Ss(this.H.b,this.n,Qo);jL(this,this.H);Fs(Vt?Sm(this.ob):Tm(Sm(this.ob)),"mosaic-WindowPanel",!0)}r(621,622,dG);_.Pd=function(){return 0!=this.H.a.p.c?lL(AJ(this.H.a.p,0)):null};_.Sd=function(a){wL(this,a)};_.Kd=function(){return new SI(this.H.a)};_.Fd=function(){eL(this);aH(new bM(this))};
_.Hd=function(a){return nL(this.H.a,a)};_.yg=function(a){DH(this,a)};_.Td=function(a,b){RK(this,a,b)};_.Qd=function(a){uL(this,a)};_.Ud=function(){LL(this)};_.k=null;_.o=0;_.p=0;_.q=null;_.r=null;_.s=null;_.t=null;_.u=null;_.v=!0;_.w=null;_.x=null;_.B=!1;_.C=null;_.D=null;_.F=null;_.G=null;_.H=null;_.I=!1;_.J=null;_.K=null;_.L=null;_.M=null;_.O=null;var sL;function cM(a){a.f=(new eK(a.i)).mc.Je();Ss(a.f,new dM(a),(Po(),Po(),Qo));a.d=F(eM,m,61,[a.f])}
function fM(){oL();var a,b,c,d,e,f;ML.call(this,(gM(),hM),null,!0);this.Bg();this.cb=!0;a=new kJ(this.j);this.e=new xJ;this.e.ob.style[Jg]=ab;Gs(this.e,ab);this.zg();fL(this,"400px");f=new zJ;f.ob.style[ge]=ab;f.e[Sc]=10;c=(vu(),wu);f.a=c;yJ(f,a);yJ(f,this.e);e=new Ku;e.e[Sc]=20;for(b=this.d,c=0,d=b.length;c<d;++c)a=b[c],Hu(e,a);yJ(f,e);tL(this,f);nK(this,!1);this.Ag()}r(620,621,dG,fM);_.zg=function(){cM(this)};_.Ag=function(){var a=this.e;a.ob.readOnly=!0;var b=Js(a.ob)+"-readonly";Fs(a.ud(),b,!0)};
_.Bg=function(){mK(this.H.b,"Copy")};_.d=null;_.e=null;_.f=null;_.i="Close";_.j="Press Ctrl-C (Command-C on Mac) or right click (Option-click on Mac) on the selected text to copy it, then paste into another program.";function dM(a){this.a=a}r(623,1,{},dM);_.Yc=function(){wL(this.a,!1)};_.a=null;function oK(a,b){jF();Gw.call(this);this.c=new iM(a);this.b=new Ku;this.b.a=(vu(),wu);Hu(this.b,this.d);tL(this.c,this.b);this.c.a=this;this.a=b}r(645,619,{},oK);_.Je=function(){return this.c};_.og=function(){return this.b.nb};
_.Rd=function(){wL(this.c,!1)};_.sg=yw;_.ug=function(a){aL(this,a);bL(this,a);hL(this.c);LL(this.c)};_.a=null;_.b=null;_.c=null;function iM(a){oL();ML.call(this,(gM(),hM),a,!1)}r(647,621,dG,iM);_.Rd=function(){var a=this.a,b=new hK(a.a,201),c;a=a.a.q;a.a?a=new jM(new vq(a.a)):(a=(Eq(),Eq(),Fq),a=new vq(a));for(;a.jd();)c=a.kd(),201==b.d&&OK(c.a)};_.a=null;function HK(){}r(655,464,{},HK);function jM(a){if(!a)throw new xy;this.a=a}r(656,1,{},jM);_.jd=function(){return Cy(this.a)};_.kd=function(){return wq(this.a)};
_.ld=function(){throw new Hy("Missing message: awt.50");};_.a=null;function SJ(){return SJ()}function FK(){FK=s;var a;a=(yy(),zy["os.encoding"]);if(null!=a)try{if(H("UTF-8",a)||H("ISO-8859-1",a)||H("ISO-LATIN-1",a))x(kM,o,-1,0,1);else throw new JK(a+" is not supported");}catch(b){if(b=nm(b),!E(b,132))throw b;}}function lM(){lM=s;var a,b;a=$doc;if((b=a.getElementsByTagName(ie))&&0<b.length)b=$doc.getElementsByTagName(ie)[0],b.style[ge]=ab;a.body.style[ge]=ab}
function CL(a){lM();var b;b=x(G,q,-1,4,1);b[0]=mM(nM(a,"borderTopWidth"));b[1]=mM(nM(a,"borderRightWidth"));b[2]=mM(nM(a,"borderBottomWidth"));b[3]=mM(nM(a,"borderLeftWidth"));return b}function oM(a){lM();var b,c;c=pM(a);b=CL(a);a=new BH(a.clientWidth,a.clientHeight);a.b+=b[1]+b[3]+(c[1]+c[3]);a.a+=b[0]+b[2]+(c[0]+c[2]);return a}function AH(a){lM();return new BH(a.clientWidth,a.clientHeight)}
function pM(a){lM();var b;b=x(G,q,-1,4,1);b[0]=mM(nM(a,"marginTop"));b[1]=mM(nM(a,"marginRight"));b[2]=mM(nM(a,"marginBottom"));b[3]=mM(nM(a,"marginLeft"));return b}function qM(a){lM();var b;b=x(G,q,-1,4,1);b[0]=mM(nM(a,"paddingTop"));b[1]=mM(nM(a,"paddingRight"));b[2]=mM(nM(a,"paddingBottom"));b[3]=mM(nM(a,"paddingLeft"));return b}function rM(a,b,c){lM();try{H(b,IG)&&(b=DG),a.style[b]=c}catch(d){if(d=nm(d),!E(d,124))throw d;}}
function iL(a,b){lM();var c;sM||(sM=$doc.createElement(ag),rM(sM,se,l),rM(sM,rg,l),rM(sM,tf,nc),rM(sM,Gg,he),$doc.body.appendChild(sM));rM(sM,Jg,a);rM(sM,ge,a);c=oM(sM);return b?c.b:c.a}var sM=null;function tM(){BH.call(this,0,0)}function BH(a,b){this.b=a;this.a=b}function IL(a){BH.call(this,a.b,a.a)}r(661,1,Th,tM,BH,IL);_.eQ=function(a){return this===a?!0:null==a||uM!=Il(a)||this.a!=a.a||this.b!=a.b?!1:!0};_.hC=Rs;_.tS=function(){return"Dimension [height="+this.a+", width="+this.b+kc};_.a=0;
_.b=0;function vM(a){this.d=a[0];this.b=a[3];this.a=a[2];this.c=a[1]}r(662,1,{117:1,120:1,141:1},vM);_.eQ=function(a){return a===this?!0:E(a,141)?a.b==this.b&&a.a==this.a&&a.c==this.c&&a.d==this.d:!1};_.hC=function(){var a;a=213+this.d;a=71*a+this.b;a=71*a+this.a;return a=71*a+this.c};_.tS=function(){return wM.d+"[left="+this.b+",top="+this.d+",right="+this.c+",bottom="+this.a+kc};_.a=0;_.b=0;_.c=0;_.d=0;function xM(a,b){this.a=a;this.b=b}r(663,1,Th,xM);
_.eQ=function(a){return this===a?!0:null==a||yM!=Il(a)||this.a!=a.a||this.b!=a.b?!1:!0};_.hC=Rs;_.tS=function(){return yM.d+"[x="+this.a+",y="+this.b+kc};_.a=0;_.b=0;function TL(){this.b=this.a=this.d=this.c=0}r(664,1,Th,TL);_.eQ=function(a){return this===a?!0:null==a||zM!=Il(a)||this.a!=a.a||this.b!=a.b||this.c!=a.c||this.d!=a.d?!1:!0};_.hC=function(){var a;a=31+this.a;a=31*a+this.b;a=31*a+this.c;return a=31*a+this.d};
_.tS=function(){return zM.d+"[x="+this.c+",y="+this.d+",width="+this.b+",height="+this.a+kc};_.a=0;_.b=0;_.c=0;_.d=0;function nM(a,b){if(document.defaultView&&document.defaultView.getComputedStyle){var c=null;b==IG&&(b=DG);var d=a.ownerDocument.defaultView.getComputedStyle(a,l);d&&(c=d[b]);return c||a.style[b]||l}return el.style[b]||l}r(666,1,{});var AM=-1;function BM(){}r(667,666,{},BM);_.a=-1;_.b=-1;var CM=null;function mM(a){a=parseInt(a,10);a=isNaN(a)?null:DA(a);return!a?0:a.a}
r(670,324,{48:1,50:1,59:1,63:1,71:1,73:1,74:1,77:1,82:1,84:1,143:1,149:1});_.vg=function(){return EH(this.f)};_.wg=function(a){mL(this.f,a)};_.xg=gD;_.Yd=gD;_.xd=function(a){var b=this.f;b.ob.style[ge]=a;b.jb||(b.f=a)};_.zd=function(a){var b=this.f;b.ob.style[Jg]=a;b.jb||(b.i=a)};function pL(){pL=s;qL()}function mK(a,b){a.a.ob.textContent=b||l;mL(a.f,null)}
function DM(a){pL();var b;UI(this,new OL);this.a=new EM;b=this.f;FM(b,new GM);rM(b.ob,qf,Za);b.o=0;ZL(b,this.a,new $L(0),b.p.c);this.a.ud()[Wc]="mosaic-Caption-text";this.a.ob.textContent=a||l;mL(this.f,null);this.ob[Wc]="mosaic-Caption"}r(669,670,{18:1,21:1,22:1,37:1,38:1,39:1,40:1,41:1,42:1,48:1,50:1,59:1,63:1,69:1,70:1,71:1,73:1,74:1,77:1,81:1,82:1,84:1,143:1,149:1},DM);_.Zc=ei;_.$c=ey;_._c=Av;_.ad=xw;_.b=null;
function qL(){qL=s;HM=pm()+"40BAF81124143A595056A9CCA0E9DBBA.cache.png";new BJ(HM,240,20);new BJ(HM,224,16);new BJ(HM,208,16);new BJ(HM,192,16);new BJ(HM,176,16);new BJ(HM,160,16);new BJ(HM,144,16);new BJ(HM,128,16);new BJ(HM,112,16);new BJ(HM,96,16);new BJ(HM,80,16);new BJ(HM,64,16);new BJ(HM,260,16);rL=new BJ(HM,48,16);new BJ(HM,32,16);new BJ(HM,16,16);new BJ(HM,0,16)}var HM,rL;function IM(a,b){Os(a.a.ob,!b);mL(a.f,a.a)}
function CH(a,b){a.c=b;Os(a.a.ob,!b);mL(a.f,a.a);if(a.d){var c;for(c=new vq(a.d);c.b<c.d.Qe();)wq(c)}}function UL(a){var b;UI(this,new OL);b=this.f;FM(b,new JM((KM(),LM)));b.o=0;this.b=new DM(a);ZL(b,this.b,new $L(1),b.p.c);this.a=new OL;Es(this.a,"Body");ZL(b,this.a,new $L(0),b.p.c);this.ob[Wc]="mosaic-CaptionLayoutPanel"}r(672,670,{48:1,50:1,59:1,63:1,71:1,72:1,73:1,74:1,77:1,82:1,84:1,143:1,149:1},UL);_.Ad=function(){Us(this.f)};_.Bd=function(){Xs(this.f)};_.Kd=function(){return new SI(this.a)};
_.Hd=function(a){return nL(this.a,a)};_.a=null;_.b=null;_.c=!1;_.d=null;function WL(){wD(this)}r(673,533,kh,WL);function NL(a){this.a=a}r(674,1,rh,NL);_.Cc=function(){JH(this.a.S.ib)};_.a=null;function MM(a){var b;b=a.b;a=b.q;b=!a.e?-1:Zu(a.e.a,b);a.e&&as(a.e.a,b)&&yD(a.e.a,b);b=!a.e?0:a.e.a.c;0<b&&JL(!a.e?null:as(a.e.a,b-1))}function NM(a){var b;b=a.a;a=b.q;!a.e&&(a.e=new Fw);-1==Zu(a.e.a,b)&&yi(a.e.a,b)}function GL(){}r(675,1,{},GL);_.bd=function(a){MM(a)};_.cd=function(a){NM(a)};
_.ed=function(a){OM(a.a.q,a.a)};function gM(){gM=s;PM=new QM(1,"e");RM=new QM(2,Ze);SM=new QM(3,"ne");TM=new QM(10,"nw");UM=new QM(4,Rf);VM=new QM(5,Uf);WM=new QM(12,"sw");XM=new QM(8,"w");hM=new YM((Zs(),ov(null)).ob)}function yL(a,b){var c;c=CL(a.ob);return new xM(Jm(b.ob)-(Jm(a.ob)+c[3]),Mm(b.ob)-(Mm(a.ob)+c[0]))}function ZM(a,b,c){a=a.d;OG(a,b,b);D(a.c,b,c);Es(b,xG+c.b)}
function FH(a,b){var c;c=a.d;xL(c,b.G);VG(b.G,xG+TM.b);xL(c,b.C);VG(b.C,xG+RM.b);xL(c,b.D);VG(b.D,xG+SM.b);xL(c,b.M);VG(b.M,xG+XM.b);xL(c,b.u);VG(b.u,xG+PM.b);xL(c,b.L);VG(b.L,xG+WM.b);xL(c,b.J);VG(b.J,xG+UM.b);xL(c,b.K);VG(b.K,xG+VM.b)}
function HH(a,b){!b.G&&(b.G=AL(b,0,0));ZM(a,b.G,TM);!b.C&&(b.C=AL(b,0,1));ZM(a,b.C,RM);!b.D&&(b.D=AL(b,0,2));ZM(a,b.D,SM);!b.M&&(b.M=AL(b,1,0));ZM(a,b.M,XM);!b.u&&(b.u=AL(b,1,2));ZM(a,b.u,PM);!b.L&&(b.L=AL(b,2,0));ZM(a,b.L,WM);!b.J&&(b.J=AL(b,2,1));ZM(a,b.J,UM);!b.K&&(b.K=AL(b,2,2));ZM(a,b.K,VM)}function OM(a,b){var c,d;a.a=b;d=a.e.a.c;c=Zu(a.e.a,b);if(c+1<d){jD(a.e,b);for(yi(a.e.a,b);c<d;++c)KL(as(a.e.a,c),c)}else KL(b,c)}
function YM(a){a=new $M(a);UI(this,a);this.c=new aN(a);this.c.i=!0;QG(this.c);this.c.k=3;this.d=new bN(a);this.d.i=!0;QG(this.d);this.d.k=3;WI(this)}r(676,324,{48:1,50:1,59:1,63:1,71:1,73:1,74:1,77:1,82:1,84:1,149:1},YM);_.vg=function(){return AH(this.ob)};_.wg=function(){var a;(a=cN(this))&&a.wg(null)};_.xg=mD;_.bd=function(a){!this.b&&(this.b=new GL);MM(a)};_.cd=function(a){!this.b&&(this.b=new GL);NM(a)};_.Yd=mD;_.ed=function(a){!this.b&&(this.b=new GL);OM(a.a.q,a.a)};_.a=null;_.b=null;_.c=null;
_.d=null;_.e=null;var PM,RM,SM,TM,hM,UM,VM,WM,XM;function $M(a){this.p=new It(this);this.ob=a}r(677,304,Jh,$M);function QM(a,b){this.a=a;this.b=b}r(678,1,{},QM);_.a=0;_.b=null;function xL(a,b){try{var c;c=Dq(MG,b);var d;d=Dq(a.n.c,c);if(!d)throw new El("dragHandle was not draggable");mv(d.b.a);mv(d.d.a);mv(d.c.a);Fs(b.ud(),uG,!1);Fs(c.ud(),FG,!1)}catch(e){if(e=nm(e),!E(e,124))throw e;}}function aN(a){LG();SG.call(this,a)}r(679,3,{},aN);
_.wc=function(){var a;a=this.j.e;a.B||Ys(a.w);VG(this.j.e,"dragdrop-dragging");!a.H.c&&IM(a.H,!1)};_.yc=function(){var a,b;a=this.j.b;b=this.j.c;this.i&&(a=Oi(this.a,a<this.d?a:this.d),b=Oi(this.b,b<this.c?b:this.c));var c=this.j.e.ob;c.style[se]=a+(bo(),wf);c.style[rg]=b+wf};
_.xc=function(){var a;a=this.j.e;a==a.q.a||JL(a);a.H.c||IM(a.H,!0);a.B||(a.w||(a.w=new dN,Es(a.w,"mosaic-GlassPanel-invisible")),rM(a.w.ob,Lg,(lM(),nM(a.ob,Lg))),Ct((Zs(),ov(null)),a.w,0,0));Es(this.j.e,"dragdrop-dragging");a=new cH(this.j.a,null);this.a=a.a+eH(this.j.a.ob);this.b=a.d+fH(this.j.a.ob);this.d=this.a+hH(this.j.a.ob)-this.j.e.td();this.c=this.b+gH(this.j.a.ob)-this.j.e.sd()};_.a=0;_.b=0;_.c=0;_.d=0;function bN(a){LG();SG.call(this,a);this.c=new xl}r(680,3,{},bN);
_.wc=function(){var a;a=this.j.e.nb;a.B||Ys(a.w);VG(this.j.e,"dragdrop-dragging");IM(a.H,!1);DH(a,new BH(a.p,a.o));zi(a.y,1)};
_.yc=function(){var a,b,c,d;d=this.j.e.nb;c=Bq(this.j.d.c,this.j.e).a;0!=(c&2)?(b=this.i?this.j.e.rd()-Oi(this.j.c,this.b):this.j.e.rd()-this.j.c,0!=b&&(a=d.o,b=Oi(a+b,Om(d.H.b.ob,jf)),b!=a&&zL(d,0,a-b),DH(d,new BH(d.p,b)),zi(d.y,333))):0!=(c&4)&&(b=this.i?(this.j.c<this.d?this.j.c:this.d)-this.j.e.rd():this.j.c-this.j.e.rd(),0!=b&&(a=d.o,b=Oi(a+b,Om(d.H.b.ob,jf)),DH(d,new BH(d.p,b)),zi(d.y,333)));0!=(c&8)?(b=this.i?this.j.e.qd()-Oi(this.j.b,this.a):this.j.e.qd()-this.j.b,0!=b&&(a=d.p,b=96<a+b?a+
b:96,b!=a&&zL(d,a-b,0),DH(d,new BH(b,d.o)),zi(d.y,333))):0!=(c&1)&&(b=this.i?(this.j.b<this.e?this.j.b:this.e)-this.j.e.qd():this.j.b-this.j.e.qd(),0!=b&&(a=d.p,DH(d,new BH(96<a+b?a+b:96,d.o)),zi(d.y,333)))};
_.xc=function(){var a;a=this.j.e.nb;a==a.q.a||JL(a);IM(a.H,!0);a.B||(a.w||(a.w=new dN,Es(a.w,"mosaic-GlassPanel-invisible")),rM(a.w.ob,Lg,(lM(),nM(a.ob,Lg))),Ct((Zs(),ov(null)),a.w,0,0));Es(this.j.e,"dragdrop-dragging");a=new cH(this.j.a,null);this.a=a.a+eH(this.j.a.ob);this.b=a.d+fH(this.j.a.ob);this.e=this.a+hH(this.j.a.ob)-this.j.e.td();this.d=this.b+gH(this.j.a.ob)-this.j.e.sd()};_.a=0;_.b=0;_.d=0;_.e=0;
function dN(){var a;this.d=new eN(this);this.a=!1;this.b=new Mt;UI(this,this.b);a=this.ob.style;a[BG]="#000";a[HG]="alpha(opacity=50)";a.opacity="0.5";this.ob[Wc]="gwt-GlassPanel"}r(681,324,hG,dN);
_.Dd=function(){var a;WI(this);try{a=this.nb}catch(b){b=nm(b);if(E(b,131))throw new Vs("Parent widget must be an instance of AbsolutePanel");throw b;}a==(Zs(),ov(null))?(AI(this),BI(this.ob),a=this.d,a.b?$wnd.clearInterval(a.c):$wnd.clearTimeout(a.c),Ii(Bi,a),a.b=!0,a.c=iH(a),yi(Bi,a),this.c=new fN(this),ds(new zI(this.c))):(this.ob.style[Pc]=Za,this.ob.style[Kf]=Za);this.a&&Qr(new yI(this));Ct(ov(null),new gN,dn($doc),en($doc))};
_.Ed=function(){this.f.Ed();Hi(this.d);this.c&&(xI(bs,this.c,F(hN,m,49,[(!gq&&(gq=new Gi),gq)])),this.c=null);this.a&&xI(Tr,this,F(hN,m,49,[(!Sr&&(Sr=new Gi),Sr)]))};_.nd=function(a){switch(Pr(a.type)){case 256:if(27==(a.keyCode||0))return Ys(this),!1;case 1:if($m(this.ob,a.target))return Ys(this),!1}return!0};_.Fd=ww;_.a=!1;_.b=null;_.c=null;function eN(a){Ai();this.a=a}r(682,26,{},eN);_.Mc=function(){var a=this.a;AI(a);BI(a.ob)};_.a=null;function fN(a){this.a=a}r(683,1,{},fN);_.a=null;
function gN(){this.ob=uu();var a;a=new vJ(new iN(this));Ss(this,a,(Ho(),Ho(),Io));Ss(this,a,(MH(),MH(),TH))}r(684,326,oh,gN);_.Fd=function(){aH(new jN(this))};function iN(a){this.a=a}r(685,1,{},iN);_.a=null;function jN(a){this.a=a}r(686,1,rh,jN);_.Cc=function(){this.a.ob.focus()};_.a=null;function kN(a){a.ob.style[Jg]=Bc;a.ob.style[ge]=Bc;if(a.jb){var a=a.nb,b;E(a,149)?a.wg(null):(b=cN(a))&&b.wg(a)}}r(688,307,{48:1,50:1,59:1,70:1,71:1,74:1,77:1,78:1,81:1,82:1,84:1,149:1});
_.vg=function(){kN(this);return new BH(Om(this.ob,kf),Om(this.ob,jf))};_.wg=function(){kN(this)};_.xg=ww;_.md=function(){};_.Yd=ww;function EM(){this.ob=$doc.createElement("label");this.ob[Wc]="mosaic-Label";this.ob.style[Ig]=ef;this.ob[Wc]="mosaic-HTML"}r(687,688,{48:1,50:1,59:1,69:1,70:1,71:1,74:1,77:1,78:1,81:1,82:1,84:1,149:1},EM);function XL(a){UI(this,new lN(a));this.ob[Wc]="mosaic-ImageButton"}r(689,324,{21:1,48:1,50:1,59:1,63:1,71:1,73:1,74:1,78:1,82:1,84:1},XL);
function lN(a){var b=(vu(),wu),c=(Du(),Eu),d;d=new cJ;d.f[Ic]=Ya;d.f[Rc]=0;d.f[Sc]=0;this.a=b;this.b=c;var b=d.d,c=this.a,e=this.b;bJ(b.a);b.a.c.rows[0].cells[0][xc]=c.a;bJ(b.a);b.a.c.rows[0].cells[0].style[Fg]=e.a;bJ(d);b=ZI(d,0,0,!0);if(a){Ys(a);c=d.i;if(c.a){var e=c.a.a,f=c.b,g=e;wx(g,f.c);dm(f.b,g,a);c.a=c.a.b}else e=c.b.c,yi(c.b,a);a.ob[AG]=e;Jr(b,a.ob);at(a,d)}UI(this,d);Fs(this.ob,"mosaic-WidgetWrapper",!0)}r(692,324,hG,lN);_.a=null;_.b=null;function PL(a){this.a=a}r(693,1,{},PL);
_.Yc=function(){this.a.gb&&this.a!=this.a.q.a&&JL(this.a)};_.a=null;function QL(a){Ai();this.a=a}r(694,26,{},QL);_.Mc=function(){JH(this.a.S.ib);var a=this.a;fq((!a.x&&(a.x=new mN),a.x))};_.a=null;function RL(a){Ai();this.a=a}r(695,26,{},RL);_.Mc=function(){DL(this.a,(yH(),zH))};_.a=null;function SL(a){Ai();this.a=a}r(696,26,{},SL);_.Mc=function(){DL(this.a,(yH(),EL))};_.a=null;function VL(){}r(697,1,{},VL);function YL(a){this.a=a}r(698,1,{},YL);_.Yc=function(){this.a.Rd()};_.a=null;
function aM(a){this.a=a}r(699,1,{},aM);_.a=null;function bM(a){this.a=a}r(700,1,rh,bM);_.Cc=function(){this.a.N==(yH(),zH)?zi(this.a.z,333):this.a.N==EL&&zi(this.a.A,333)};_.a=null;function BL(a){this.ob=a;Us(this)}r(701,307,{18:1,21:1,37:1,38:1,39:1,40:1,41:1,42:1,48:1,50:1,59:1,71:1,74:1,82:1,84:1},BL);_.Zc=ei;_.$c=ey;_._c=Av;_.ad=xw;function mN(){yq.call(this,null)}r(702,237,Ah,mN);function yH(){yH=s;zH=new nN(0);EL=new nN(1);FL=new nN(2);oN=F(pN,m,144,[zH,EL,FL])}function nN(a){this.b=a}
r(703,152,{117:1,121:1,123:1,144:1},nN);var oN,zH,EL,FL;function AI(a){var b,c,d,e;c=cn();b=bn();e=(LI(),MI).scrollWidth;d=MI.scrollHeight;c=c>e?c:e;b=b>d?b:d;0<=c-1&&(a.ob.style[Jg]=c-1+wf);0<=b-1&&(a.ob.style[ge]=b-1+wf)}function BI(a){var b=$doc.defaultView.getComputedStyle($doc.documentElement,null);a.style.marginLeft=(xa+b.getPropertyValue("margin-left")).replace(lG,l);a.style.marginTop=(xa+b.getPropertyValue("margin-top")).replace(lG,l)}
function qN(a,b){var c,d,e;if(a.k)return!0;a.x._e();for(c=new SI(b);c.a.a<c.a.b.c-1;)d=lL(Qv(c.a)),e=d.nb,E(e,150)&&e.yd(d.vd()),d.vd()&&yi(a.x,d);return!0}
function rN(a,b){var c,d,e;if(b.a)a.c&&ji(a.c),a.c=new sN(a,b),ki(a.c,333);else for(d=new vq(a.x);d.b<d.d.Qe();)c=wq(d),e=c.mb,Ft(b,tN(c),e.s,e.t),uN(c,e.u,e.r,F(G,q,-1,[vN(a.q.a,c).d,vN(a.p.a,c).c,vN(a.n.a,c).a,vN(a.o.a,c).b]),F(G,q,-1,[wN(a.i.a,c).d,wN(a.f.a,c).c,wN(a.d.a,c).a,wN(a.e.a,c).b]),F(G,q,-1,[xN(a.u,c),xN(a.t,c),xN(a.r,c),xN(a.s,c)]))}
function yN(){this.x=new vi;this.j=new zN(this);this.w=new AN(this.j);this.v=new BN(this.j);this.q=new CN(this.j);this.p=new DN(this.j);this.n=new EN(this.j);this.o=new FN(this.j);this.i=new GN(this.j);this.f=new HN(this.j);this.d=new IN(this.j);this.e=new JN(this.j);this.u=new KN(this.j);this.t=new KN(this.j);this.r=new KN(this.j);this.s=new KN(this.j)}r(707,1,{});_.Dg=function(a){rN(this,a)};_.c=null;_.d=null;_.e=null;_.f=null;_.i=null;_.j=null;_.k=!1;_.n=null;_.o=null;_.p=null;_.q=null;_.r=null;
_.s=null;_.t=null;_.u=null;_.v=null;_.w=null;function sN(a,b){this.a=a;this.b=b;var c=(pi(),si);this.k=new oi(this);this.t=c}r(708,17,{},sN);_.Dc=vw;_.Ec=vw;
_.Gc=function(a){var b,c,d;for(c=new vq(this.a.x);c.b<c.d.Qe();)b=wq(c),E(b,64)&&(b=b.ib),d=b.mb,d.i=I(d.o+(d.s-d.o)*a),d.v=I(d.p+(d.t-d.p)*a),d.w=I(d.q+(d.u-d.q)*a),d.f=I(d.n+(d.r-d.n)*a),Ft(this.b,tN(b),d.i,d.v),uN(b,d.w,d.f,F(G,q,-1,[vN(this.a.q.a,b).d,vN(this.a.p.a,b).c,vN(this.a.n.a,b).a,vN(this.a.o.a,b).b]),F(G,q,-1,[wN(this.a.i.a,b).d,wN(this.a.f.a,b).c,wN(this.a.d.a,b).a,wN(this.a.e.a,b).b]),F(G,q,-1,[xN(this.a.u,b),xN(this.a.t,b),xN(this.a.r,b),xN(this.a.s,b)]))};_.a=null;_.b=null;
r(710,1,{});_.a=null;function IN(a){this.a=a}r(709,710,{},IN);function JN(a){this.a=a}r(711,710,{},JN);function HN(a){this.a=a}r(712,710,{},HN);function GN(a){this.a=a}r(713,710,{},GN);function EN(a){this.a=a}r(714,710,{},EN);function FN(a){this.a=a}r(715,710,{},FN);function DN(a){this.a=a}r(716,710,{},DN);function CN(a){this.a=a}r(717,710,{},CN);r(718,710,{},function(a){this.a=a});r(719,710,{},function(a){this.a=a});
function xN(a,b){var c=a.a,d;d=Bq(c.d,b);d||(d=new vM(qM(b.ob)),D(c.d,b,d));return d.d}function KN(a){this.a=a}r(720,710,{},KN);function BN(a){this.a=a}r(721,710,{},BN);function AN(a){this.a=a}r(722,710,{},AN);function wN(a,b){var c;c=Bq(a.a,b);c||(c=new vM(CL(b.ob)),D(a.a,b,c));return c}function vN(a,b){var c;c=Bq(a.b,b);c||(c=new vM(pM(b.ob)),D(a.b,b,c));return c}
function LN(a,b){var c,d;d=Bq(a.e,b);if(!d){c=b.mb;a:{d=a.f;var e=cN(b),f,g,j,h,n;if(E(b,149)){if(null!=c.k&&null!=c.j){d=new BH(MN(e,!0),MN(e,!1));break a}h=b.vg();null!=c.k&&(h.b=MN(e,!0));null!=c.j&&(h.a=MN(e,!1))}else{if(null!=c.k&&null!=c.j){d=new BH(MN(e,!0),MN(e,!1));break a}h=new tM;f=b.ob;n=f.style;g=n[tf];j=n[Gg];n[tf]="static";n[Gg]=he;null!=c.k?h.b=MN(e,!0):(n[Jg]=Bc,h.b=(f.offsetWidth||0)+vN(d.o.a,b).b+vN(d.p.a,b).c);null!=c.j?h.a=MN(e,!1):(n[ge]=Bc,h.a=(f.offsetHeight||0)+vN(d.q.a,b).d+
vN(d.n.a,b).a);n[tf]=g;n[Gg]=j}d=h}null!=c.k&&(bo(),fo)==c.k.Fg()||null!=c.j&&(bo(),fo)!=c.j.Fg()||D(a.e,b,d)}return d}function zN(a){this.f=a;this.c=new xl;this.e=new xl;this.b=new xl;this.a=new xl;this.d=new xl}r(723,1,{},zN);_.a=null;_.b=null;_.c=null;_.d=null;_.e=null;_.f=null;function NN(a){var b;b=a.mb;if(null==b||!E(b,147))b=new ON,a.mb=b;return b}function GM(){JM.call(this,(KM(),PN))}function JM(a){var b=(QN(),RN);yN.call(this);this.b=a;this.a=b}r(724,707,{},GM,JM);
_.Eg=function(a){var b,c,d,e,f,g,j,h,n;h=new tM;qN(this,a);n=vN(this.o.a,a).b+vN(this.p.a,a).c+wN(this.e.a,a).b+wN(this.f.a,a).c+xN(this.s,a)+xN(this.t,a);d=vN(this.q.a,a).d+vN(this.n.a,a).a+wN(this.i.a,a).d+wN(this.d.a,a).a+xN(this.u,a)+xN(this.r,a);c=this.x.c;if(0==c)return h.b=n,h.a=d,h;a=a.o;this.b==(KM(),PN)?n+=(c-1)*a:d+=(c-1)*a;f=g=0;for(a=new vq(this.x);a.b<a.d.Qe();)c=wq(a),e=NN(c),b=null,j=c.nb,E(j,150)&&(b=j,b=SN(b),b=new BH(b[1]+b[3],b[0]+b[0])),this.b==PN?(n+=LN(this.w.a,c).b,e.a=LN(this.v.a,
c).a,E(j,150)&&(n+=b.b,e.a+=b.a),f=Oi(f,e.a)):(d+=LN(this.v.a,c).a,e.b=LN(this.w.a,c).b,E(j,150)&&(d+=b.a,e.b+=b.b),g=Oi(g,e.b));this.b==PN?(h.b=n,h.a=d+f):(h.b=n+g,h.a=d);return h};
_.Dg=function(a){var b,c,d,e,f,g,j,h,n,t,v,u,w,B,J,C,K,ya;if(qN(this,a)&&(e=this.x.c,0!=e)){J=a.o;w=xN(this.s,a);C=xN(this.u,a);c=AH(a.ob);ya=c.b-(w+xN(this.t,a));v=c.a-(C+xN(this.r,a));g=ya;c=v;this.b==(KM(),PN)?g-=(e-1)*J:c-=(e-1)*J;j=h=0;for(e=new vq(this.x);e.b<e.d.Qe();)d=wq(e),b=null,u=NN(d),B=d.nb,E(B,150)&&(b=B,b=SN(b),b=new BH(b[1]+b[3],b[0]+b[0])),this.b==PN?(u.d?++h:(u.b=LN(this.w.a,d).b,E(B,150)&&(u.b+=b.b),g-=u.b),u.c?u.a=v:(u.a=LN(this.v.a,d).a,E(B,150)&&(u.a+=b.a))):(u.c?++j:(u.a=LN(this.v.a,
d).a,E(B,150)&&(u.a+=b.a),c-=u.a),u.d?u.b=ya:(u.b=LN(this.w.a,d).b,E(B,150)&&(u.b+=b.b)));for(e=new vq(this.x);e.b<e.d.Qe();)d=wq(e),b=null,u=d.mb,B=d.nb,E(B,150)&&(b=B,b=SN(b),b=new BH(b[1]+b[3],b[0]+b[0])),K=u.b,t=u.a,this.b==PN?u.d&&(K=~~(g/h)):u.c&&(t=~~(c/j)),C=0>C?0:C,n=K,f=t,E(B,150)&&(n-=b.b,f-=b.a),this.b==LM?(u.s=this.a==(QN(),RN)?w:this.a==TN?w+~~(ya/2)-~~(K/2):w+ya-K,u.t=C,u.u=n,u.r=f,C+=t+J):(this.a==(QN(),RN)?(u.s=w,u.t=C):this.a==TN?(u.s=w,u.t=C+~~(v/2)-~~(t/2)):(u.s=w,u.t=C+v-t),u.u=
n,u.r=f,w+=K+J),a.a&&(B=d.qd()-Jm(a.ob)-xN(this.s,a),-1==u.o&&(u.o=B),B=d.rd()-Mm(a.ob)-xN(this.u,a),-1==u.p&&(u.p=B),B=d.td(),-1==u.q&&(u.q=B),d=d.sd(),-1==u.n&&(u.n=d));rN(this,a)}};_.a=null;_.b=null;function QN(){QN=s;RN=new UN(0);TN=new UN(1);VN=new UN(2);WN=F(XN,m,145,[RN,TN,VN])}function UN(a){this.b=a}r(725,152,{117:1,121:1,123:1,145:1},UN);var WN,TN,VN,RN;function KM(){KM=s;PN=new YN(0);LM=new YN(1);ZN=F($N,m,146,[PN,LM])}function YN(a){this.b=a}r(726,152,{117:1,121:1,123:1,146:1},YN);
var ZN,PN,LM;r(728,1,{151:1});_.e=!1;_.f=0;_.i=0;_.j=null;_.k=null;_.n=0;_.o=0;_.p=0;_.q=0;_.r=0;_.s=0;_.t=0;_.u=0;_.v=0;_.w=0;function ON(){this.e=!1}function $L(a){this.e=!1;0==a?this.c=this.d=!0:1==a?this.d=!0:2==a&&(this.c=!0)}r(727,728,{147:1,151:1},ON,$L);_.a=0;_.b=0;_.c=!1;_.d=!1;function aO(a,b){if(a.k)return!0;qN(a,b);if(0<a.x.c){a.a=as(a.x,0);var c=a.a,d;d=c.mb;if(null==d||!E(d,148))d=new bO,c.mb=d;a.b=d;a.x._e();yi(a.x,a.a)}else a.a=null,a.b=null;return a.k=!!a.a}
function cO(){yN.call(this)}r(729,707,{},cO);_.Eg=function(a){var b,c;c=new tM;aO(this,a);if(this.a){b=LN(this.w.a,this.a).b;var d=LN(this.v.a,this.a).a;c.b=b;c.a=d;b=this.a.nb;E(b,150)&&(b=SN(b),c.b+=b[1]+b[3],c.a+=b[0]+b[0])}c.b+=vN(this.o.a,a).b+vN(this.p.a,a).c+wN(this.e.a,a).b+wN(this.f.a,a).c+xN(this.s,a)+xN(this.t,a);c.a+=vN(this.q.a,a).d+vN(this.n.a,a).a+wN(this.i.a,a).d+wN(this.d.a,a).a+xN(this.u,a)+xN(this.r,a);return c};
_.Dg=function(a){var b,c,d,e,f;aO(this,a)&&(d=xN(this.s,a),e=xN(this.u,a),c=AH(a.ob),f=c.b-(d+xN(this.t,a)),c=c.a-(e+xN(this.r,a)),b=this.a.nb,E(b,150)&&(b=SN(b),f-=b[1]+b[3],c-=b[0]+b[2]),this.b.s=d,this.b.u=f,this.b.t=e,this.b.r=c,a.a&&(d=this.b,e=this.a.qd()-Jm(a.ob)-xN(this.s,a),-1==d.o&&(d.o=e),d=this.b,e=this.a.rd()-Mm(a.ob)-xN(this.u,a),-1==d.p&&(d.p=e),d=this.b,e=this.a.td(),-1==d.q&&(d.q=e),d=this.b,e=this.a.sd(),-1==d.n&&(d.n=e)),rN(this,a))};_.a=null;_.b=null;function bO(){this.e=!1}
r(730,728,{148:1,151:1},bO);function SN(a){var b,c,d,e;null==a.a&&(a.a=x(G,q,-1,4,1),e=Sm(rs(rs(a.c,0),0)),c=Sm(rs(rs(a.c,2),2)),d=pM(a.ob),b=CL(a.ob),a.a[0]=(e.offsetHeight||0)+b[0]+d[0],a.a[1]=(c.offsetWidth||0)+b[1]+d[1],a.a[2]=(c.offsetHeight||0)+b[2]+d[2],a.a[3]=(e.offsetWidth||0)+b[3]+d[3]);return a.a}function dO(a,b){a.jb&&Ys(a);return Kt(a,b)}function eO(){lu();bu.call(this,mu)}r(731,314,{48:1,50:1,59:1,64:1,71:1,72:1,74:1,82:1,84:1,150:1},eO);_.Hd=function(a){return dO(this,a)};_.a=null;
function tN(a){var b;b=a.nb;return E(b,150)?b:a}function EH(a){if(!a.jb)return new tM;if(-1==a.j.b||-1==a.j.a)a.j=a.d.Eg(a),GH(a,a.j),a.d.Dg(a),a.j=a.d.Eg(a);return a.j}function lL(a){return E(a,150)?a.ib:a}function fO(a){var b;if(!a.n){b=(!CM&&(CM=new BM),CM);var c=gO(a,nG,!0);b.a=c;c=gO(a,oG,!0);b.b=c;a.n=b}return a.n}
function kL(a,b,c,d,e){if(E(b,64))throw new Ji("Adding a DecoratorPanel is not allowed!");var f;f=b.mb;null!=f&&E(f,151)&&f.e?(c=new eO,wt(a,c,a.ob,d,!0),Lt(c,b)):wt(a,b,c,d,e);mL(a,b)}function ZL(a,b,c,d){b.mb=c;kL(a,b,a.ob,d,!0)}
function mL(a,b){var c;c=a.d;if(b){var d=c.j;Dq(d.c,b);Dq(d.e,b);Dq(d.b,b);Dq(d.a,b);Dq(d.d,b)}else d=c.j,zv(d.c),zv(d.e),zv(d.b),zv(d.a),zv(d.d);c.k=!1;if(!a.c){a.c=!0;c=a.j;c.b=-1;c.a=-1;c=a.nb;if(c==tN(a))c=c.nb;else{if(E(c,143)||E(c,63))d=c,c=c.nb,c==tN(d)&&(c=c.nb);E(c,150)&&E(c.nb,142)&&(c=c.nb)}E(c,149)&&!E(c,142)&&(c.wg(a.nb),c.wg(a))}}
function JH(a){if(a.jb&&a.ob.style.display!=bf){a.ob.scrollTop=0;var b=a.ob,c=0;!Ym()&&b.ownerDocument.defaultView.getComputedStyle(b,null).direction==Qf&&(c+=(b.scrollWidth||0)-b.clientWidth);b.scrollLeft=c;a.d.Dg(a);a.c=!1;hO(a)}}function hO(a){var b,c,d;c=a.p.c;for(d=0;d<c;++d)b=lL(AJ(a.p,d)),E(b,150)&&(b=b.ib),b.vd()&&(E(b,149)?b.xg():E(b,77)&&b.Yd())}function nL(a,b){var c;E(b,150)&&(b=E(b,150)?b.ib:b);c=tN(b);return Dt(a,c)?(E(c,150)&&dO(c,b),mL(a,null),!0):!1}
function FM(a,b){var c;a.d=b;null!=a.e&&VG(a,Js(a.ob)+xa+a.e);a.e=b.cZ.d;c=bw(a.e,Ls(46));a.e=a.e.substr(c+1,a.e.length-(c+1));Es(a,Js(a.ob)+xa+a.e);mL(a,null)}function gO(a,b,c){a.k||(a.k=$doc.createElement(ag),rM(a.k,tf,nc),rM(a.k,Gg,he),rM(a.k,se,Za),rM(a.k,rg,Za),a.ob.appendChild(a.k));rM(a.k,Jg,b);rM(a.k,ge,b);a=oM(a.k);return c?a.b:a.a}
function MN(a,b){var c;c=null.Fg();if(c==(bo(),ro)){c=(fO(a),null.Fg());var d=(-1==AM&&(AM=(lM(),iL(pG,!0))),AM);return M(L(Math.round(100*d*c/254)))}if(c==ho)return c=fO(a),d=null.Fg(),M(L(T(d*(-1==c.a&&(c.a=iL(nG,!0)),c.a))));if(c==jo)return c=fO(a),d=null.Fg(),M(L(T(d*(-1==c.b&&(c.b=iL(oG,!0)),c.a))));if(c==po)return c=(fO(a),null.Fg()),d=(-1==AM&&(AM=(lM(),iL(pG,!0))),AM),M(L(Math.round(d*c)));if(c==to)return c=(fO(a),null.Fg()),d=(-1==AM&&(AM=(lM(),iL(pG,!0))),AM),M(L(Math.round(10*d*c/254)));
if(c==no)return M(L(T(12*(fO(a),null.Fg())*M(L(T((-1==AM&&(AM=(lM(),iL(pG,!0))),AM)/72))))));if(c==fo)return gO(a,null.Fg(),b);if(c==lo)return c=(fO(a),M(L(T(null.Fg())))),d=(-1==AM&&(AM=(lM(),iL(pG,!0))),AM),M(L(Math.round(d*c/72)));if(null.Fg()==co)return M(L(T(null.Fg())));throw new Ji("Invalid size: "+null.Fg());}function OL(){var a=new cO;Ht.call(this);this.j=new BH(-1,-1);new iO(this);this.ob[Wc]="mosaic-LayoutPanel";FM(this,a)}
r(732,304,{48:1,50:1,59:1,71:1,72:1,74:1,77:1,82:1,84:1,149:1},OL);_.Ld=function(a){kL(this,a,this.ob,this.p.c,!0)};_.Ad=function(){qt(this,new jO)};_.Bd=function(){qt(this,new kO)};_.vg=function(){return EH(this)};_.Id=function(a){return zt(this.p,tN(a))};_.Jd=function(a,b,c,d){kL(this,a,b,c,d)};_.wg=function(a){mL(this,a)};_.Kd=function(){return new SI(this)};_.xg=pt;
_.Fd=function(){var a;this.b&&(null!=this.i&&null!=this.f?(Is(this,this.i,this.f),this.i=this.f=null):(a=EH(this),null!=this.i?(Is(this,this.i,a.a+wf),this.i=null):null!=this.f?(Is(this,a.b+wf,this.f),this.f=null):Is(this,a.b+wf,a.a+wf)),JH(this))};_.Yd=pt;_.Hd=function(a){return nL(this,a)};_.xd=function(a){this.ob.style[ge]=a;this.jb||(this.f=a)};_.Md=function(a,b,c){Ft(this,tN(a),b,c)};_.zd=function(a){this.ob.style[Jg]=a;this.jb||(this.i=a)};_.a=!1;_.b=!1;_.c=!0;_.d=null;_.e=null;_.f=null;
_.i=null;_.k=null;_.n=null;_.o=4;function jO(){}r(733,1,{},jO);_.Vd=function(a){tN(a).Dd()};function kO(){}r(734,1,{},kO);_.Vd=function(a){tN(a).Ed()};function SI(a){this.b=a;this.a=new Bt(this.b.p)}r(735,1,{},SI);_.jd=function(){return this.a.a<this.a.b.c-1};_.kd=function(){return lL(Qv(this.a))};_.ld=function(){Rv(this.a)};_.b=null;function lO(){lO=s;new jJ}function iO(a){lO();Fs(a.ob,"dragdrop-dropTarget",!0);this.a=a;new mO(this)}r(736,9,{},iO);function mO(a){Ai();this.a=a}r(737,26,{},mO);
_.Mc=function(){mL(this.a.a,null);JH(this.a.a)};_.a=null;function cN(a){a=a.nb;return!a?null:E(a,149)?a:cN(a)}function HL(a,b,c){var d;d=a.ob;uN(a,b,c,pM(d),CL(d),qM(d))}function uN(a,b,c,d,e,f){var g;0<=b&&(b-=d[1]+d[3],g=b-(e[1]+e[3]+f[1]+f[3]),a.zd((0>g?0:g)+(bo(),wf)),b!=a.td()&&a.zd((0>b?0:b)+wf));0<=c&&(c-=d[0]+d[2],b=c-(e[0]+e[2]+f[0]+f[2]),a.xd((0>b?0:b)+(bo(),wf)),c!=a.sd()&&a.xd((0>c?0:c)+wf))}function GH(a,b){HL(a,b.b,b.a)}var nO=PC(" B"),kM=JC(758,nO);Y(422);Y(421);Y(548);Y(563);Y(456);
Y(552);Y(411);var oO=NC(151,function(){$G();return tH}),uH=JC(766,oO);NC(153,null);NC(154,null);NC(155,null);NC(156,null);NC(157,null);var pO=NC(246,function(){dI();return iI}),jI=JC(773,pO);Y(340);Y(342);Y(341);Y(343);Y(430);var tK=Y(425);Y(409);Y(410);OC();OC();OC();Y(455);Y(615);Y(454);Y(331);Y(330);Y(457);var dK=Y(408),cK=JC(777,tx);Y(609);Y(611);Y(622);Y(621);Y(647);Y(619);Y(645);var qO=NC(703,function(){yH();return oN}),pN=JC(778,qO);Y(702);Y(701);Y(693);Y(694);Y(695);Y(696);Y(697);Y(698);Y(699);
Y(700);Y(674);Y(532);Y(540);Y(541);Y(542);Y(321);var rO=Y(320);Y(325);Y(263);Y(267);Y(382);Y(264);Y(324);Y(676);Y(3);Y(679);Y(680);Y(678);Y(677);Y(670);Y(669);Y(732);Y(733);Y(734);Y(735);Y(672);Y(235);var uM=Y(661),yM=Y(663);Y(233);Y(688);Y(687);Y(462);Y(461);Y(463);Y(266);Y(346);Y(275);var hN=JC(782,QF);Y(276);Y(314);Y(731);Y(278);Y(281);Y(279);Y(280);Y(5);Y(7);Y(6);Y(464);Y(620);var eM=JC(783,rO);Y(623);Y(465);Y(689);Y(656);Y(497);Y(517);var zM=Y(664);Y(673);Y(692);Y(728);Y(727);Y(206);Y(221);Y(4);
Y(655);Y(707);Y(724);var sO=NC(725,function(){QN();return WN}),XN=JC(784,sO),tO=NC(726,function(){KM();return ZN}),$N=JC(785,tO);Y(710);Y(719);Y(718);Y(722);Y(721);Y(717);Y(716);Y(714);Y(715);Y(713);Y(712);Y(709);Y(711);Y(720);Y(723);Y(708);Y(675);Y(729);Y(328);Y(327);Y(333);Y(334);Y(332);Y(277);Y(298);Y(299);Y(11);Y(14);Y(329);Y(378);Y(369);Y(730);Y(8);Y(10);Y(9);Y(736);Y(737);Y(681);Y(684);Y(685);Y(686);Y(682);Y(683);var wM=Y(662);Y(666);Y(667);Y(212);y(aG)(8);function ww(){}
function ot(){JH(this.S.ib)}function Av(a){return Ss(this,a,(VH(),VH(),WH))}function Rs(){var a;a=31+this.a;return a=31*a+this.b}function mD(){var a,b,c,d,e,f;if(this.e){a=AH(this.ob);for(c=0,d=this.e.a.c;c<d;++c)f=as(this.e.a,c),b=new BH(Om(f.ob,kf),Om(f.ob,jf)),e=yL(this,f),e.a-=Oi(0,e.a+Om(f.ob,kf)-a.b),e.b-=Oi(0,e.b+Om(f.ob,jf)-a.a),RK(f,Oi(0,e.a),Oi(0,e.b)),b.b=b.b>a.b?a.b:-1,b.a=b.a>a.a?a.a:-1,HL(f,b.b,b.a),f.N==(yH(),zH)&&GH(f,new IL(AH(this.ob))),zi(f.y,1)}}
function ei(a){return Ss(this,a,(zp(),zp(),Ap))}function vw(){var a,b;b=this.a;a=this.b;var c,d,e;for(d=new vq(b.x);d.b<d.d.Qe();)c=wq(d),E(c,64)&&(c=c.ib),e=c.mb,Ft(a,tN(c),e.s,e.t),uN(c,e.u,e.r,F(G,q,-1,[vN(b.q.a,c).d,vN(b.p.a,c).c,vN(b.n.a,c).a,vN(b.o.a,c).b]),F(G,q,-1,[wN(b.i.a,c).d,wN(b.f.a,c).c,wN(b.d.a,c).a,wN(b.e.a,c).b]),F(G,q,-1,[xN(b.u,c),xN(b.t,c),xN(b.r,c),xN(b.s,c)]));hO(a);this.a.c=null;for(b=new vq(this.a.x);b.b<b.d.Qe();)a=wq(b),E(a,64)&&(a=a.ib),a=a.mb,a.o=a.p=a.q=a.n=-1}
function xw(a){return Ss(this,a,(Jp(),Jp(),Kp))}function fi(){return Mm(this.ob)}function ey(a){return Ss(this,a,(Cp(),Cp(),Dp))}function Vo(){return!1}function yw(){}function VC(){return ra+this.a+wa+this.d+sa}function fy(){return!cw(this)?new jw(0,0):tw(this.mc,this)}function JB(){return this.a}function Qp(){return Dr(this.a)}function UC(){}function Qs(a){YK(this,a)}function Ny(){return Jm(this.ob)}function Ps(a){return!E(a,55)?!1:H(this.a,a.gd())}function gD(){JH(this.f)}
function pt(){JH(this)}function ou(){return null};