var tO="3",uO="Any",vO="Aromatic",wO="Nonring",xO="Reset",yO="Ring";function zO(){zO=s;AO=new Jo(Vc,new BO)}function BO(){}r(198,195,{},BO);_.Tc=function(a){ow();UK(this,a.b,CO(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return AO};var AO;function DO(a,b){if(0>b||b>=a.ob.options.length)throw new wt;}function CO(a,b){DO(a,b);return a.ob.options[b].value}function EO(){this.ob=$doc.createElement("select");this.ob[Xc]="gwt-ListBox"}r(344,322,Uh,EO);function FO(){FO=s}
function GO(a,b){if(null==b)throw new jq("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(nf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function HO(){FO();nw.call(this);new vi;this.mc=new IO((ow(),this))}r(412,399,{90:1,92:1,99:1,111:1,117:1},HO);_.ae=function(){return sw(this.mc,this)};
_.pe=function(){return(null==this.jc&&(this.jc=$v(this)),this.jc)+va+this.uc+va+this.vc+va+this.rc+Kg+this.hc+(this.qc?l:",hidden")+",current="+CO(this.mc.a,this.mc.a.ob.selectedIndex)};function JO(){rK.call(this,7)}r(425,1,Th,JO);function KO(a){tK.call(this,a,0)}r(430,399,vh,KO);r(556,554,Vh);_.Pc=function(){!this.a.Ib?this.a.Ib=new LO(this.a):this.a.Ib.mc.c.gb?IL(this.a.Ib.mc.c):PK(this.a.Ib)};function MO(a,b){DJ(b)==a.a?Z(b,(Yw(),gx)):Z(b,a.a)}
function NO(a){var b,c,d,e;e=l;d=!1;DJ(OO)!=a.a?(e=ta,d=!0):DJ(PO)!=a.a?(e="!#6",d=!0):DJ(QO)!=a.a?(Z(YO,(Yw(),gx)),Z(ZO,gx),Z($O,gx),Z(aP,gx),e="F,Cl,Br,I"):(b=DJ(bP)!=a.a,c=DJ(cP)!=a.a,DJ(dP)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),DJ(eP)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),DJ(fP)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),DJ(gP)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),DJ(hP)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),DJ(YO)!=a.a&&(e+="F,"),DJ(ZO)!=a.a&&(e+="Cl,"),DJ($O)!=a.a&&(e+="Br,"),DJ(aP)!=a.a&&(e+="I,"),
$C(e,va)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=nc:c?e=ob:(Z(OO,(Yw(),gx)),e=ta)));b=l;d&&DJ(bP)!=a.a&&(b+=";a");d&&DJ(cP)!=a.a&&(b+=";A");DJ(iP)!=a.a&&(b+=";R");DJ(jP)!=a.a&&(b+=";!R");DJ(OO)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=kP.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=lP.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);DJ(mP)!=a.a&&(e="~");DJ(nP)!=a.a&&(e=eb);DJ(oP)!=a.a&&(e=nb);DJ(pP)!=a.a&&(e="!@");wK(a.e,e)}
function qP(a){rP(a);sP(a);var b=kP.mc.a;DO(b,0);b.ob.options[0].selected=!0;b=lP.mc.a;DO(b,0);b.ob.options[0].selected=!0;Z(bP,a.a);Z(cP,a.a);Z(iP,a.a);Z(jP,a.a);Z(kP,a.a);Z(lP,a.a);tP(a)}function rP(a){Z(dP,a.a);Z(eP,a.a);Z(fP,a.a);Z(gP,a.a);Z(hP,a.a);Z(YO,a.a);Z(ZO,a.a);Z($O,a.a);Z(aP,a.a)}function sP(a){Z(OO,a.a);Z(PO,a.a);Z(QO,a.a)}function tP(a){Z(mP,a.a);Z(nP,a.a);Z(oP,a.a);Z(pP,a.a);a.b=!1}
function LO(a){kK.call(this,"Atom/Bond Query");this.i=new dK(this.hg());Rw(this.q,new SK(this));this.a=(fz(),hz);this.c=a;this.d||(a=cw(a),this.d=new vK(a),OK(this.d,-150,10));this.j=this.d;Bw(this,new JO);Z(this,this.a);a=new Gw;Bw(a,new xx(0,3,1));$(a,new KO("Atom type :"),null);OO=new dK(uO);PO=new dK("Any except C");QO=new dK("Halogen");$(a,OO,null);$(a,PO,null);$(a,QO,null);$(this,a,null);a=new Gw;Bw(a,new xx(0,3,1));$(a,new tK("Or select one or more from the list :",0),null);$(this,a,null);
a=new Gw;Bw(a,new xx(0,3,1));dP=new dK(rb);eP=new dK(Nb);fP=new dK(Tb);gP=new dK($b);hP=new dK(Ub);YO=new dK(Ab);ZO=new dK(ub);$O=new dK(qb);aP=new dK(Ib);$(a,dP,null);$(a,eP,null);$(a,fP,null);$(a,gP,null);$(a,hP,null);$(a,YO,null);$(a,ZO,null);$(a,$O,null);$(a,aP,null);$(this,a,null);a=new Gw;Bw(a,new xx(0,3,1));kP=new HO;GO(kP,uO);GO(kP,Ya);GO(kP,$a);GO(kP,db);GO(kP,tO);$(a,new KO("Number of hydrogens :  "),null);$(a,kP,null);$(this,a,null);a=new Gw;Bw(a,new xx(0,3,1));lP=new HO;GO(lP,uO);GO(lP,
Ya);GO(lP,$a);GO(lP,db);GO(lP,tO);GO(lP,"4");GO(lP,"5");GO(lP,"6");$(a,new tK("Number of connections :",0),null);$(a,lP,null);$(a,new tK(" (H's don't count.)",0),null);$(this,a,null);a=new Gw;Bw(a,new xx(0,3,1));$(a,new KO("Atom is :"),null);bP=new dK(vO);$(a,bP,null);cP=new dK("Nonaromatic");$(a,cP,null);iP=new dK(yO);$(a,iP,null);jP=new dK(wO);$(a,jP,null);$(this,a,null);a=new Gw;Z(a,nx(DJ(this)));Bw(a,new xx(0,3,1));$(a,new KO("Bond is :"),null);mP=new dK(uO);$(a,mP,null);nP=new dK(vO);$(a,nP,
null);oP=new dK(yO);$(a,oP,null);pP=new dK(wO);$(a,pP,null);$(this,a,null);a=new Gw;Bw(a,new xx(1,3,1));this.e=new cy(ta,20);$(a,this.e,null);$(a,new dK(xO),null);$(a,this.i,null);$(this,a,null);this.mc&&mK(this.mc.c,!1);jK(this,!1);rP(this);sP(this);tP(this);Z(bP,this.a);Z(cP,this.a);Z(iP,this.a);Z(jP,this.a);Z(kP,this.a);Z(lP,this.a);MO(this,OO);iK(this);a=this.j;QK(this.mc.c,a.a,a.b);!bw(this)&&MJ(this);HJ(this)}r(566,548,eG,LO);
_.ig=function(a,b){var c;H(b,xO)?(qP(this),MO(this,OO),NO(this)):E(a.f,89)?(tP(this),Rq(a.f)===Rq(OO)?(rP(this),sP(this)):Rq(a.f)===Rq(PO)?(rP(this),sP(this)):Rq(a.f)===Rq(QO)?(rP(this),sP(this)):Rq(a.f)===Rq(iP)?Z(jP,this.a):Rq(a.f)===Rq(jP)?(Z(iP,this.a),Z(bP,this.a)):Rq(a.f)===Rq(bP)?(Z(cP,this.a),Z(jP,this.a)):Rq(a.f)===Rq(cP)?Z(bP,this.a):Rq(a.f)===Rq(mP)||Rq(a.f)===Rq(nP)||Rq(a.f)===Rq(oP)||Rq(a.f)===Rq(pP)?(qP(this),this.b=!0):sP(this),MO(this,a.f),NO(this)):E(a.f,90)&&(tP(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(Yw(),gx)),NO(this));107!=this.c.e&&(this.c.e=107,Lw(this.c));return!0};_.jg=function(){return Pm(this.e.mc.a.ob,Eg)};_.kg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var OO=_.e=null,mP=null,PO=null,bP=null,nP=null,$O=null,dP=null,lP=null,kP=null,ZO=null,YO=null,QO=null,aP=null,eP=null,cP=null,jP=null,pP=null,fP=null,hP=null,iP=null,oP=null,gP=null;function IO(a){iF();kF.call(this);this.a=new EO;Rs(this.a,new uP(this,a),(zO(),zO(),AO))}r(612,610,{},IO);_.Je=function(){return this.a};
_.a=null;function uP(a,b){this.a=a;this.b=b}r(613,1,{},uP);_.a=null;_.b=null;Y(566);Y(412);Y(612);Y(613);Y(344);Y(198);y($F)(3);