var pP="3",qP="Any",rP="Aromatic",sP="Nonring",tP="Reset",uP="Ring";function CP(){CP=r;DP=new ap(Xc,new EP)}function EP(){}q(210,207,{},EP);_.Pc=function(a){rx();PL(this,a.b,FP(a.a.a,a.a.a.ob.selectedIndex))};_.Sc=function(){return DP};var DP;function GP(a,b){if(0>b||b>=a.ob.options.length)throw new tu;}function FP(a,b){GP(a,b);return a.ob.options[b].value}function HP(){this.ob=$doc.createElement("select");this.ob[fd]="gwt-ListBox"}q(356,334,Wh,HP);function IP(){IP=r}
function JP(a,b){if(null==b)throw new Sq("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(qf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function KP(){IP();qx.call(this);new Bi;this.mc=new LP((rx(),this))}q(421,408,{90:1,92:1,99:1,111:1,117:1},KP);_.ae=function(){return vx(this.mc,this)};
_.pe=function(){return(null==this.jc&&(this.jc=cx(this)),this.jc)+xa+this.uc+xa+this.vc+xa+this.rc+Ng+this.hc+(this.qc?l:",hidden")+",current="+FP(this.mc.a,this.mc.a.ob.selectedIndex)};function MP(){mL.call(this,7)}q(434,1,Vh,MP);function NP(a){oL.call(this,a,0)}q(439,408,xh,NP);q(576,574,Xh);_.Lc=function(){!this.a.Ib?this.a.Ib=new OP(this.a):this.a.Ib.mc.c.gb?DM(this.a.Ib.mc.c):KL(this.a.Ib)};function PP(a,b){yK(b)==a.a?Z(b,(by(),ky)):Z(b,a.a)}
function QP(a){var b,c,d,e;e=l;d=!1;yK(RP)!=a.a?(e=va,d=!0):yK(SP)!=a.a?(e="!#6",d=!0):yK(TP)!=a.a?(Z(UP,(by(),ky)),Z(VP,ky),Z(WP,ky),Z(XP,ky),e="F,Cl,Br,I"):(b=yK(YP)!=a.a,c=yK(ZP)!=a.a,yK($P)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),yK(aQ)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),yK(bQ)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),yK(cQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),yK(dQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),yK(UP)!=a.a&&(e+="F,"),yK(VP)!=a.a&&(e+="Cl,"),yK(WP)!=a.a&&(e+="Br,"),yK(XP)!=a.a&&(e+="I,"),
tE(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=pc:c?e=pb:(Z(RP,(by(),ky)),e=va)));b=l;d&&yK(YP)!=a.a&&(b+=";a");d&&yK(ZP)!=a.a&&(b+=";A");yK(eQ)!=a.a&&(b+=";R");yK(fQ)!=a.a&&(b+=";!R");yK(RP)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=gQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=hQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);yK(iQ)!=a.a&&(e="~");yK(jQ)!=a.a&&(e=fb);yK(kQ)!=a.a&&(e=ob);yK(lQ)!=a.a&&(e="!@");rL(a.e,e)}
function mQ(a){nQ(a);oQ(a);var b=gQ.mc.a;GP(b,0);b.ob.options[0].selected=!0;b=hQ.mc.a;GP(b,0);b.ob.options[0].selected=!0;Z(YP,a.a);Z(ZP,a.a);Z(eQ,a.a);Z(fQ,a.a);Z(gQ,a.a);Z(hQ,a.a);pQ(a)}function nQ(a){Z($P,a.a);Z(aQ,a.a);Z(bQ,a.a);Z(cQ,a.a);Z(dQ,a.a);Z(UP,a.a);Z(VP,a.a);Z(WP,a.a);Z(XP,a.a)}function oQ(a){Z(RP,a.a);Z(SP,a.a);Z(TP,a.a)}function pQ(a){Z(iQ,a.a);Z(jQ,a.a);Z(kQ,a.a);Z(lQ,a.a);a.b=!1}
function OP(a){fL.call(this,"Atom/Bond Query");this.i=new ZK(this.jg());Vx(this.q,new NL(this));this.a=(zA(),BA);this.c=a;this.d||(a=fx(a),this.d=new qL(a),JL(this.d,-150,10));this.j=this.d;Ex(this,new MP);Z(this,this.a);a=new Jx;Ex(a,new By(0,3,1));$(a,new NP("Atom type :"),null);RP=new ZK(qP);SP=new ZK("Any except C");TP=new ZK("Halogen");$(a,RP,null);$(a,SP,null);$(a,TP,null);$(this,a,null);a=new Jx;Ex(a,new By(0,3,1));$(a,new oL("Or select one or more from the list :",0),null);$(this,a,null);
a=new Jx;Ex(a,new By(0,3,1));$P=new ZK(sb);aQ=new ZK(Pb);bQ=new ZK(Tb);cQ=new ZK(ac);dQ=new ZK(Ub);UP=new ZK(Ab);VP=new ZK(wb);WP=new ZK(rb);XP=new ZK(Ib);$(a,$P,null);$(a,aQ,null);$(a,bQ,null);$(a,cQ,null);$(a,dQ,null);$(a,UP,null);$(a,VP,null);$(a,WP,null);$(a,XP,null);$(this,a,null);a=new Jx;Ex(a,new By(0,3,1));gQ=new KP;JP(gQ,qP);JP(gQ,$a);JP(gQ,cb);JP(gQ,eb);JP(gQ,pP);$(a,new NP("Number of hydrogens :  "),null);$(a,gQ,null);$(this,a,null);a=new Jx;Ex(a,new By(0,3,1));hQ=new KP;JP(hQ,qP);JP(hQ,
$a);JP(hQ,cb);JP(hQ,eb);JP(hQ,pP);JP(hQ,"4");JP(hQ,"5");JP(hQ,"6");$(a,new oL("Number of connections :",0),null);$(a,hQ,null);$(a,new oL(" (H's don't count.)",0),null);$(this,a,null);a=new Jx;Ex(a,new By(0,3,1));$(a,new NP("Atom is :"),null);YP=new ZK(rP);$(a,YP,null);ZP=new ZK("Nonaromatic");$(a,ZP,null);eQ=new ZK(uP);$(a,eQ,null);fQ=new ZK(sP);$(a,fQ,null);$(this,a,null);a=new Jx;Z(a,ry(yK(this)));Ex(a,new By(0,3,1));$(a,new NP("Bond is :"),null);iQ=new ZK(qP);$(a,iQ,null);jQ=new ZK(rP);$(a,jQ,
null);kQ=new ZK(uP);$(a,kQ,null);lQ=new ZK(sP);$(a,lQ,null);$(this,a,null);a=new Jx;Ex(a,new By(1,3,1));this.e=new gz(va,20);$(a,this.e,null);$(a,new ZK(tP),null);$(a,this.i,null);$(this,a,null);this.mc&&hL(this.mc.c,!1);eL(this,!1);nQ(this);oQ(this);pQ(this);Z(YP,this.a);Z(ZP,this.a);Z(eQ,this.a);Z(fQ,this.a);Z(gQ,this.a);Z(hQ,this.a);PP(this,RP);dL(this);a=this.j;LL(this.mc.c,a.a,a.b);!ex(this)&&HK(this);CK(this)}q(586,568,wH,OP);
_.kg=function(a,b){var c;H(b,tP)?(mQ(this),PP(this,RP),QP(this)):D(a.f,89)?(pQ(this),zr(a.f)===zr(RP)?(nQ(this),oQ(this)):zr(a.f)===zr(SP)?(nQ(this),oQ(this)):zr(a.f)===zr(TP)?(nQ(this),oQ(this)):zr(a.f)===zr(eQ)?Z(fQ,this.a):zr(a.f)===zr(fQ)?(Z(eQ,this.a),Z(YP,this.a)):zr(a.f)===zr(YP)?(Z(ZP,this.a),Z(fQ,this.a)):zr(a.f)===zr(ZP)?Z(YP,this.a):zr(a.f)===zr(iQ)||zr(a.f)===zr(jQ)||zr(a.f)===zr(kQ)||zr(a.f)===zr(lQ)?(mQ(this),this.b=!0):oQ(this),PP(this,a.f),QP(this)):D(a.f,90)&&(pQ(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(by(),ky)),QP(this));107!=this.c.e&&(this.c.e=107,Ox(this.c));return!0};_.lg=function(){return Km(this.e.mc.a.ob,Hg)};_.mg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var RP=_.e=null,iQ=null,SP=null,YP=null,jQ=null,WP=null,$P=null,hQ=null,gQ=null,VP=null,UP=null,TP=null,XP=null,aQ=null,ZP=null,fQ=null,lQ=null,bQ=null,dQ=null,eQ=null,kQ=null,cQ=null;function LP(a){BG();DG.call(this);this.a=new HP;au(this.a,new qQ(this,a),(CP(),CP(),DP))}q(632,630,{},LP);_.Je=function(){return this.a};
_.a=null;function qQ(a,b){this.a=a;this.b=b}q(633,1,{},qQ);_.a=null;_.b=null;W(586);W(421);W(632);W(633);W(356);W(210);x(sH)(3);