language: php

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

php:
  - 7.2

sudo: required

addons:
  firefox: "35.0.1"
  postgresql: "9.6"

services:
  - mysql

matrix:
  include:
    - php: 7.0
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.0
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.1
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.1
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_35_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_36_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.2
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 7.2
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.3
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 7.3
      env: DB=mysqli MOODLE_BRANCH=master
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_38_STABLE
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=MOODLE_39_STABLE
    - php: 7.4
      env: DB=pgsql  MOODLE_BRANCH=master
    - php: 7.4
      env: DB=mysqli MOODLE_BRANCH=master

before_install:
  - sudo hostname short-hostname
  - phpenv config-rm xdebug.ini
  - cd ../..
  - export MOODLE_VERSION=$(echo "$MOODLE_BRANCH" | cut -d'_' -f 2)
  - if [ "$MOODLE_VERSION" = 36 ] || [ "$MOODLE_VERSION" -le 34 ]; then NVMVERSION=8.9; else NVMVERSION=14.0.0; fi
  - nvm install $NVMVERSION;
  - nvm use $NVMVERSION;
  - composer create-project -n --no-dev --prefer-dist moodlehq/moodle-plugin-ci ci ^3;
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install -vvv

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci validate
  - moodle-plugin-ci savepoints || travis_terminate 1;
  - moodle-plugin-ci grunt || travis_terminate 1;
  - moodle-plugin-ci phpunit
  - moodle-plugin-ci behat
