<?php 
   require_once(dirname(__FILE__).'/header.php');
   require_once(dirname(__FILE__).'/reg.php');
   ?>
<?php
require_once(dirname(__FILE__).'/customscriptloadrenderer.php');
require_once(dirname(__FILE__).'/footerrenderer.php');
$bodyattributes = $OUTPUT->body_attributes();
$blockspre = $OUTPUT->blocks('side-pre');
$blockspost = $OUTPUT->blocks('side-post');
$hassidepre = $PAGE->blocks->region_has_content('side-pre', $OUTPUT);
$hassidepost = $PAGE->blocks->region_has_content('side-post', $OUTPUT);
$templatecontext = [
'sitename' => format_string($SITE->shortname, true, ['context' => context_course::instance(SITEID), "escape" => false]),
'output' => $OUTPUT,
'sidepreblocks' => $blockspre,
'sidepostblocks' => $blockspost,
'haspreblocks' => $hassidepre,
'haspostblocks' => $hassidepost,
'bodyattributes' => $bodyattributes,
// Global
'favicon' => $favicon,
'logourl' => $logourl,
// Slider
'displayslidersection' => $displayslidersection,
'slider1imageurl' => $slider1imageurl,
'slider1caption' => $slider1caption,
'joinnowbuttontext' => $joinnowbuttontext,
'joinnowbuttonurl' => $joinnowbuttonurl,
'readmorebuttontext' => $readmorebuttontext,
'readmorebuttonurl' => $readmorebuttonurl,
'slider2imageurl' => $slider2imageurl,
'slider2caption' => $slider2caption,
'startcoursebuttontext' => $startcoursebuttontext,
'startcoursebuttonurl' => $startcoursebuttonurl,
'taketourbuttontext' => $taketourbuttontext,
'taketourbuttonurl' => $taketourbuttonurl,
'slider3imageurl' => $slider3imageurl,
'slider3caption' => $slider3caption,
'slider4imageurl' => $slider4imageurl,
'slider4caption' => $slider4caption,
'slider4tagline' => $slider4tagline,
'slider5imageurl' => $slider5imageurl,
'slider5caption' => $slider5caption,
'slider6imageurl' => $slider6imageurl,
'slider6caption' => $slider6caption,
'slider6tagline' => $slider6tagline,
'slider6buttontext' => $slider6buttontext,
'slider6buttonurl' => $slider6buttonurl,
// All for Frontpage
'categorytagline' => $categorytagline,
'allcoursestagline' => $allcoursestagline,
'enrolledcoursestagline' => $enrolledcoursestagline,
'sitenewstagline' => $sitenewstagline,
'blockcustombutton' => $blockcustombutton,
'blockcustombuttonurl' => $blockcustombuttonurl,
'blockheading' => $blockheading,
'blocktagline' => $blocktagline,
'callus' => $callus,
'callusurl' => $callusurl,
'emailus' => $emailus,
'emailusurl' => $emailusurl,
'livechat' => $livechat,
'livechaturl' => $livechaturl,
'displayaboutussection' => $displayaboutussection,
'aboutusheading' => $aboutusheading,
'aboutustagline' => $aboutustagline,
'aboutusimage' => $aboutusimage,
'aboutusdescription' => $aboutusdescription,
'accordionbox1heading' => $accordionbox1heading,
'accordionbox1description' => $accordionbox1description,
'accordionbox2heading' => $accordionbox2heading,
'accordionbox2description' => $accordionbox2description,
'accordionbox3heading' => $accordionbox3heading,
'accordionbox3description' => $accordionbox3description,
'accordionbox4heading' => $accordionbox4heading,
'accordionbox4description' => $accordionbox4description,
'displaymarketingsection' => $displaymarketingsection,
'marketingheading' => $marketingheading,
'marketingbuttontext' => $marketingbuttontext,
'marketingbuttonurl' => $marketingbuttonurl,
'displaytutorsection' => $displaytutorsection,
'tutorssectionheading' => $tutorssectionheading,
'tutorssectiontagline' => $tutorssectiontagline,
'displaytutor1' => $displaytutor1,
'tutor1image' => $tutor1image,
'tutor1name' => $tutor1name,
'tutor1url' => $tutor1url,
'tutor1designation' => $tutor1designation,
'displaytutor2' => $displaytutor2,
'tutor2image' => $tutor2image,
'tutor2name' => $tutor2name,
'tutor2url' => $tutor2url,
'tutor2designation' => $tutor2designation,
'displaytutor3' => $displaytutor3,
'tutor3image' => $tutor3image,
'tutor3name' => $tutor3name,
'tutor3url' => $tutor3url,
'tutor3designation' => $tutor3designation,
'displaytutor4' => $displaytutor4,
'tutor4image' => $tutor4image,
'tutor4name' => $tutor4name,
'tutor4url' => $tutor4url,
'tutor4designation' => $tutor4designation,
'displaytutor5' => $displaytutor5,
'tutor5image' => $tutor5image,
'tutor5name' => $tutor5name,
'tutor5url' => $tutor5url,
'tutor5designation' => $tutor5designation,
'displaytutor6' => $displaytutor6,
'tutor6image' => $tutor6image,
'tutor6name' => $tutor6name,
'tutor6url' => $tutor6url,
'tutor6designation' => $tutor6designation,
'displaytutor7' => $displaytutor7,
'tutor7image' => $tutor7image,
'tutor7name' => $tutor7name,
'tutor7url' => $tutor7url,
'tutor7designation' => $tutor7designation,
'displaytutor8' => $displaytutor8,
'tutor8image' => $tutor8image,
'tutor8name' => $tutor8name,
'tutor8url' => $tutor8url,
'tutor8designation' => $tutor8designation,
'displaytutor9' => $displaytutor9,
'tutor9image' => $tutor9image,
'tutor9name' => $tutor9name,
'tutor9url' => $tutor9url,
'tutor9designation' => $tutor9designation,
'displaystudentsection' => $displaystudentsection,
'studentsectionheading' => $studentsectionheading,
'studentsectiontagline' => $studentsectiontagline,
'student1backgroundurl' => $student1backgroundurl,
'student1name' => $student1name,
'student1description' => $student1description,
'student2backgroundurl' => $student2backgroundurl,
'student2name' => $student2name,
'student2description' => $student2description,
'student3backgroundurl' => $student3backgroundurl,
'student3name' => $student3name,
'student3description' => $student3description,
'student4backgroundurl' => $student4backgroundurl,
'student4name' => $student4name,
'student4description' => $student4description,
'student5backgroundurl' => $student5backgroundurl,
'student5name' => $student5name,
'student5description' => $student5description,
'displaynewslettersection' => $displaynewslettersection,
'newsletterheading' => $newsletterheading,
'newslettertagline' => $newslettertagline,
// Category Section
'categorytagline' => $categorytagline,
'enablecategoryimage' => $enablecategoryimage,
// Footer Section
'footerlogo' => $footerlogo,
'hasfacebook' => $hasfacebook,
'hastwitter' => $hastwitter,
'hasgoogleplus' => $hasgoogleplus,
'haspinterest' => $haspinterest,
'hasinstagram' => $hasinstagram,
'hasyoutube' => $hasyoutube,
'hasflickr' => $hasflickr,
'haswhatsapp' => $haswhatsapp,
'hasskype' => $hasskype,
'hasgithub' => $hasgithub,
'hascopyright' => $hascopyright,
'privacypolicy' => $privacypolicy,
'privacypolicyurl' => $privacypolicyurl,
'backtotop' => $backtotop,
'googleplayurl' => $googleplayurl,
'copyrightY' => $copyrightY,
'reg' => $reg,
'customscriptloadernoamd'=> $customscriptloadernoamd,
'footer'=> $footer
];
$PAGE->requires->js('/theme/trending/javascript/custom2.js');
$PAGE->requires->js('/theme/trending/javascript/jquery.min.js');
$PAGE->requires->js('/theme/trending/javascript/owl.carousel.js');
$PAGE->requires->js('/theme/trending/javascript/custom.js');
echo $OUTPUT->render_from_template('theme_trending/frontpage', $templatecontext);

