var XN="3",YN="Any",ZN="Aromatic",$N="Nonring",aO="Reset",bO="Ring";function cO(){cO=s;dO=new oo(Wc,new eO)}function eO(){}r(196,193,{},eO);_.Tc=function(a){Yv();xK(this,a.b,fO(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return dO};var dO;function gO(a,b){if(0>b||b>=a.ob.options.length)throw new Ps;}function fO(a,b){gO(a,b);return a.ob.options[b].value}function hO(){Tt();this.ob=$doc.createElement("select");this.ob[Yc]="gwt-ListBox"}r(341,319,Ah,hO);function iO(){iO=s}
function jO(a,b){if(null==b)throw new Qp("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(nf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function kO(){iO();Xv.call(this);new ti;this.mc=new lO((Yv(),this))}r(408,395,{89:1,91:1,98:1,110:1,116:1},kO);_.be=function(){return bw(this.mc,this)};
_.qe=function(){return(null==this.jc&&(this.jc=Jv(this)),this.jc)+va+this.uc+va+this.vc+va+this.rc+Lg+this.hc+(this.qc?l:",hidden")+",current="+fO(this.mc.a,this.mc.a.ob.selectedIndex)};function mO(){WJ.call(this,7)}r(421,1,vh,mO);function nO(a){YJ.call(this,a,0)}r(426,395,bi,nO);r(552,550,Th);_.Pc=function(){!this.a.Ib?this.a.Ib=new oO(this.a):this.a.Ib.mc.c.gb?lL(this.a.Ib.mc.c):sK(this.a.Ib)};function pO(a,b){hJ(b)==a.a?Z(b,(Hw(),Qw)):Z(b,a.a)}
function qO(a){var b,c,d,e;e=l;d=!1;hJ(rO)!=a.a?(e=ta,d=!0):hJ(sO)!=a.a?(e="!#6",d=!0):hJ(tO)!=a.a?(Z(uO,(Hw(),Qw)),Z(CO,Qw),Z(DO,Qw),Z(EO,Qw),e="F,Cl,Br,I"):(b=hJ(FO)!=a.a,c=hJ(GO)!=a.a,hJ(HO)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),hJ(IO)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),hJ(JO)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),hJ(KO)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),hJ(LO)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),hJ(uO)!=a.a&&(e+="F,"),hJ(CO)!=a.a&&(e+="Cl,"),hJ(DO)!=a.a&&(e+="Br,"),hJ(EO)!=a.a&&(e+="I,"),
IC(e,va)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=mc:c?e=ob:(Z(rO,(Hw(),Qw)),e=ta)));b=l;d&&hJ(FO)!=a.a&&(b+=";a");d&&hJ(GO)!=a.a&&(b+=";A");hJ(MO)!=a.a&&(b+=";R");hJ(NO)!=a.a&&(b+=";!R");hJ(rO)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=OO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=PO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);hJ(QO)!=a.a&&(e="~");hJ(RO)!=a.a&&(e=eb);hJ(SO)!=a.a&&(e=nb);hJ(TO)!=a.a&&(e="!@");Mx(a.e.mc,e)}
function UO(a){VO(a);WO(a);var b=OO.mc.a;gO(b,0);b.ob.options[0].selected=!0;b=PO.mc.a;gO(b,0);b.ob.options[0].selected=!0;Z(FO,a.a);Z(GO,a.a);Z(MO,a.a);Z(NO,a.a);Z(OO,a.a);Z(PO,a.a);XO(a)}function VO(a){Z(HO,a.a);Z(IO,a.a);Z(JO,a.a);Z(KO,a.a);Z(LO,a.a);Z(uO,a.a);Z(CO,a.a);Z(DO,a.a);Z(EO,a.a)}function WO(a){Z(rO,a.a);Z(sO,a.a);Z(tO,a.a)}function XO(a){Z(QO,a.a);Z(RO,a.a);Z(SO,a.a);Z(TO,a.a);a.b=!1}
function oO(a){PJ.call(this,"Atom/Bond Query");this.i=new IJ(this.ig());Aw(this.q,new vK(this));this.a=(Ny(),Py);this.c=a;this.d||(a=Mv(a),this.d=new $J(a),rK(this.d,-150,10));this.j=this.d;kw(this,new mO);Z(this,this.a);a=new pw;kw(a,new gx(0,3,1));$(a,new nO("Atom type :"),null);rO=new IJ(YN);sO=new IJ("Any except C");tO=new IJ("Halogen");$(a,rO,null);$(a,sO,null);$(a,tO,null);$(this,a,null);a=new pw;kw(a,new gx(0,3,1));$(a,new YJ("Or select one or more from the list :",0),null);$(this,a,null);
a=new pw;kw(a,new gx(0,3,1));HO=new IJ(sb);IO=new IJ(Pb);JO=new IJ(Tb);KO=new IJ(ac);LO=new IJ(Ub);uO=new IJ(Ab);CO=new IJ(wb);DO=new IJ(rb);EO=new IJ(Ib);$(a,HO,null);$(a,IO,null);$(a,JO,null);$(a,KO,null);$(a,LO,null);$(a,uO,null);$(a,CO,null);$(a,DO,null);$(a,EO,null);$(this,a,null);a=new pw;kw(a,new gx(0,3,1));OO=new kO;jO(OO,YN);jO(OO,Ya);jO(OO,$a);jO(OO,db);jO(OO,XN);$(a,new nO("Number of hydrogens :  "),null);$(a,OO,null);$(this,a,null);a=new pw;kw(a,new gx(0,3,1));PO=new kO;jO(PO,YN);jO(PO,
Ya);jO(PO,$a);jO(PO,db);jO(PO,XN);jO(PO,"4");jO(PO,"5");jO(PO,"6");$(a,new YJ("Number of connections :",0),null);$(a,PO,null);$(a,new YJ(" (H's don't count.)",0),null);$(this,a,null);a=new pw;kw(a,new gx(0,3,1));$(a,new nO("Atom is :"),null);FO=new IJ(ZN);$(a,FO,null);GO=new IJ("Nonaromatic");$(a,GO,null);MO=new IJ(bO);$(a,MO,null);NO=new IJ($N);$(a,NO,null);$(this,a,null);a=new pw;Z(a,Xw(hJ(this)));kw(a,new gx(0,3,1));$(a,new nO("Bond is :"),null);QO=new IJ(YN);$(a,QO,null);RO=new IJ(ZN);$(a,RO,
null);SO=new IJ(bO);$(a,SO,null);TO=new IJ($N);$(a,TO,null);$(this,a,null);a=new pw;kw(a,new gx(1,3,1));this.e=new Lx(ta,20);$(a,this.e,null);$(a,new IJ(aO),null);$(a,this.i,null);$(this,a,null);this.mc&&RJ(this.mc.c,!1);OJ(this,!1);VO(this);WO(this);XO(this);Z(FO,this.a);Z(GO,this.a);Z(MO,this.a);Z(NO,this.a);Z(OO,this.a);Z(PO,this.a);pO(this,rO);NJ(this);a=this.j;tK(this.mc.c,a.a,a.b);!Lv(this)&&qJ(this);lJ(this)}r(562,544,PF,oO);
_.jg=function(a,b){var c;H(b,aO)?(UO(this),pO(this,rO),qO(this)):E(a.f,88)?(XO(this),xq(a.f)===xq(rO)?(VO(this),WO(this)):xq(a.f)===xq(sO)?(VO(this),WO(this)):xq(a.f)===xq(tO)?(VO(this),WO(this)):xq(a.f)===xq(MO)?Z(NO,this.a):xq(a.f)===xq(NO)?(Z(MO,this.a),Z(FO,this.a)):xq(a.f)===xq(FO)?(Z(GO,this.a),Z(NO,this.a)):xq(a.f)===xq(GO)?Z(FO,this.a):xq(a.f)===xq(QO)||xq(a.f)===xq(RO)||xq(a.f)===xq(SO)||xq(a.f)===xq(TO)?(UO(this),this.b=!0):WO(this),pO(this,a.f),qO(this)):E(a.f,89)&&(XO(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(Hw(),Qw)),qO(this));107!=this.c.e&&(this.c.e=107,uw(this.c));return!0};_.kg=function(){return Km(this.e.mc.a.ob,Cg)};_.lg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var rO=_.e=null,QO=null,sO=null,FO=null,RO=null,DO=null,HO=null,PO=null,OO=null,CO=null,uO=null,tO=null,EO=null,IO=null,GO=null,NO=null,TO=null,JO=null,LO=null,MO=null,SO=null,KO=null;function lO(a){SE();UE.call(this);this.a=new hO;ws(this.a,new YO(this,a),(cO(),cO(),dO))}r(608,606,{},lO);_.Ke=function(){return this.a};
_.a=null;function YO(a,b){this.a=a;this.b=b}r(609,1,{},YO);_.a=null;_.b=null;Y(562);Y(408);Y(608);Y(609);Y(341);Y(196);y(IF)(3);