var vO="3",wO="Any",xO="Aromatic",yO="Nonring",zO="Reset",AO="Ring";function BO(){BO=s;CO=new Ko(Vc,new DO)}function DO(){}r(198,195,{},DO);_.Tc=function(a){pw();VK(this,a.b,EO(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return CO};var CO;function FO(a,b){if(0>b||b>=a.ob.options.length)throw new xt;}function EO(a,b){FO(a,b);return a.ob.options[b].value}function GO(){this.ob=$doc.createElement("select");this.ob[Xc]="gwt-ListBox"}r(344,322,Vh,GO);function HO(){HO=s}
function IO(a,b){if(null==b)throw new kq("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(of);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function JO(){HO();ow.call(this);new wi;this.mc=new KO((pw(),this))}r(412,399,{90:1,92:1,99:1,111:1,117:1},JO);_.ae=function(){return tw(this.mc,this)};
_.pe=function(){return(null==this.jc&&(this.jc=aw(this)),this.jc)+va+this.uc+va+this.vc+va+this.rc+Lg+this.hc+(this.qc?l:",hidden")+",current="+EO(this.mc.a,this.mc.a.ob.selectedIndex)};function LO(){sK.call(this,7)}r(425,1,Uh,LO);function MO(a){uK.call(this,a,0)}r(430,399,wh,MO);r(556,554,Wh);_.Pc=function(){!this.a.Ib?this.a.Ib=new NO(this.a):this.a.Ib.mc.c.gb?JL(this.a.Ib.mc.c):QK(this.a.Ib)};function OO(a,b){EJ(b)==a.a?Z(b,(Zw(),hx)):Z(b,a.a)}
function PO(a){var b,c,d,e;e=l;d=!1;EJ(QO)!=a.a?(e=ta,d=!0):EJ(RO)!=a.a?(e="!#6",d=!0):EJ(SO)!=a.a?(Z($O,(Zw(),hx)),Z(aP,hx),Z(bP,hx),Z(cP,hx),e="F,Cl,Br,I"):(b=EJ(dP)!=a.a,c=EJ(eP)!=a.a,EJ(fP)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),EJ(gP)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),EJ(hP)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),EJ(iP)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),EJ(jP)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),EJ($O)!=a.a&&(e+="F,"),EJ(aP)!=a.a&&(e+="Cl,"),EJ(bP)!=a.a&&(e+="Br,"),EJ(cP)!=a.a&&(e+="I,"),
aD(e,va)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=nc:c?e=ob:(Z(QO,(Zw(),hx)),e=ta)));b=l;d&&EJ(dP)!=a.a&&(b+=";a");d&&EJ(eP)!=a.a&&(b+=";A");EJ(kP)!=a.a&&(b+=";R");EJ(lP)!=a.a&&(b+=";!R");EJ(QO)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=mP.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=nP.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);EJ(oP)!=a.a&&(e="~");EJ(pP)!=a.a&&(e=eb);EJ(qP)!=a.a&&(e=nb);EJ(rP)!=a.a&&(e="!@");xK(a.e,e)}
function sP(a){tP(a);uP(a);var b=mP.mc.a;FO(b,0);b.ob.options[0].selected=!0;b=nP.mc.a;FO(b,0);b.ob.options[0].selected=!0;Z(dP,a.a);Z(eP,a.a);Z(kP,a.a);Z(lP,a.a);Z(mP,a.a);Z(nP,a.a);vP(a)}function tP(a){Z(fP,a.a);Z(gP,a.a);Z(hP,a.a);Z(iP,a.a);Z(jP,a.a);Z($O,a.a);Z(aP,a.a);Z(bP,a.a);Z(cP,a.a)}function uP(a){Z(QO,a.a);Z(RO,a.a);Z(SO,a.a)}function vP(a){Z(oP,a.a);Z(pP,a.a);Z(qP,a.a);Z(rP,a.a);a.b=!1}
function NO(a){lK.call(this,"Atom/Bond Query");this.i=new eK(this.hg());Sw(this.q,new TK(this));this.a=(gz(),iz);this.c=a;this.d||(a=dw(a),this.d=new wK(a),PK(this.d,-150,10));this.j=this.d;Cw(this,new LO);Z(this,this.a);a=new Hw;Cw(a,new yx(0,3,1));$(a,new MO("Atom type :"),null);QO=new eK(wO);RO=new eK("Any except C");SO=new eK("Halogen");$(a,QO,null);$(a,RO,null);$(a,SO,null);$(this,a,null);a=new Hw;Cw(a,new yx(0,3,1));$(a,new uK("Or select one or more from the list :",0),null);$(this,a,null);
a=new Hw;Cw(a,new yx(0,3,1));fP=new eK(rb);gP=new eK(Nb);hP=new eK(Tb);iP=new eK($b);jP=new eK(Ub);$O=new eK(Ab);aP=new eK(ub);bP=new eK(qb);cP=new eK(Ib);$(a,fP,null);$(a,gP,null);$(a,hP,null);$(a,iP,null);$(a,jP,null);$(a,$O,null);$(a,aP,null);$(a,bP,null);$(a,cP,null);$(this,a,null);a=new Hw;Cw(a,new yx(0,3,1));mP=new JO;IO(mP,wO);IO(mP,Ya);IO(mP,$a);IO(mP,db);IO(mP,vO);$(a,new MO("Number of hydrogens :  "),null);$(a,mP,null);$(this,a,null);a=new Hw;Cw(a,new yx(0,3,1));nP=new JO;IO(nP,wO);IO(nP,
Ya);IO(nP,$a);IO(nP,db);IO(nP,vO);IO(nP,"4");IO(nP,"5");IO(nP,"6");$(a,new uK("Number of connections :",0),null);$(a,nP,null);$(a,new uK(" (H's don't count.)",0),null);$(this,a,null);a=new Hw;Cw(a,new yx(0,3,1));$(a,new MO("Atom is :"),null);dP=new eK(xO);$(a,dP,null);eP=new eK("Nonaromatic");$(a,eP,null);kP=new eK(AO);$(a,kP,null);lP=new eK(yO);$(a,lP,null);$(this,a,null);a=new Hw;Z(a,ox(EJ(this)));Cw(a,new yx(0,3,1));$(a,new MO("Bond is :"),null);oP=new eK(wO);$(a,oP,null);pP=new eK(xO);$(a,pP,
null);qP=new eK(AO);$(a,qP,null);rP=new eK(yO);$(a,rP,null);$(this,a,null);a=new Hw;Cw(a,new yx(1,3,1));this.e=new dy(ta,20);$(a,this.e,null);$(a,new eK(zO),null);$(a,this.i,null);$(this,a,null);this.mc&&nK(this.mc.c,!1);kK(this,!1);tP(this);uP(this);vP(this);Z(dP,this.a);Z(eP,this.a);Z(kP,this.a);Z(lP,this.a);Z(mP,this.a);Z(nP,this.a);OO(this,QO);jK(this);a=this.j;RK(this.mc.c,a.a,a.b);!cw(this)&&NJ(this);IJ(this)}r(566,548,fG,NO);
_.ig=function(a,b){var c;H(b,zO)?(sP(this),OO(this,QO),PO(this)):E(a.f,89)?(vP(this),Sq(a.f)===Sq(QO)?(tP(this),uP(this)):Sq(a.f)===Sq(RO)?(tP(this),uP(this)):Sq(a.f)===Sq(SO)?(tP(this),uP(this)):Sq(a.f)===Sq(kP)?Z(lP,this.a):Sq(a.f)===Sq(lP)?(Z(kP,this.a),Z(dP,this.a)):Sq(a.f)===Sq(dP)?(Z(eP,this.a),Z(lP,this.a)):Sq(a.f)===Sq(eP)?Z(dP,this.a):Sq(a.f)===Sq(oP)||Sq(a.f)===Sq(pP)||Sq(a.f)===Sq(qP)||Sq(a.f)===Sq(rP)?(sP(this),this.b=!0):uP(this),OO(this,a.f),PO(this)):E(a.f,90)&&(vP(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(Zw(),hx)),PO(this));107!=this.c.e&&(this.c.e=107,Mw(this.c));return!0};_.jg=function(){return Qm(this.e.mc.a.ob,Cg)};_.kg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var QO=_.e=null,oP=null,RO=null,dP=null,pP=null,bP=null,fP=null,nP=null,mP=null,aP=null,$O=null,SO=null,cP=null,gP=null,eP=null,lP=null,rP=null,hP=null,jP=null,kP=null,qP=null,iP=null;function KO(a){jF();lF.call(this);this.a=new GO;Ss(this.a,new wP(this,a),(BO(),BO(),CO))}r(612,610,{},KO);_.Je=function(){return this.a};
_.a=null;function wP(a,b){this.a=a;this.b=b}r(613,1,{},wP);_.a=null;_.b=null;Y(566);Y(412);Y(612);Y(613);Y(344);Y(198);y(aG)(3);