var GP="3",HP="Any",IP="Aromatic",JP="Nonring",KP="Reset",LP="Ring";function TP(){TP=r;UP=new kp(ed,new VP)}function VP(){}q(215,212,{},VP);_.Tc=function(a){Nx();gM(this,a.b,WP(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return UP};var UP;function XP(a,b){if(0>b||b>=a.ob.options.length)throw new Eu;}function WP(a,b){XP(a,b);return a.ob.options[b].value}function YP(){wv();this.ob=$doc.createElement("select");this.ob[gd]="gwt-ListBox"}q(361,339,bi,YP);function ZP(){ZP=r}
function $P(a,b){if(null==b)throw new cr("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(sf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function aQ(){ZP();Mx.call(this);new Di;this.mc=new bQ((Nx(),this))}q(428,415,{90:1,92:1,99:1,111:1,117:1},aQ);_.fe=function(){return Rx(this.mc,this)};
_.ue=function(){return(null==this.jc&&(this.jc=yx(this)),this.jc)+xa+this.uc+xa+this.vc+xa+this.rc+Sg+this.hc+(this.qc?l:",hidden")+",current="+WP(this.mc.a,this.mc.a.ob.selectedIndex)};function cQ(){EL.call(this,7)}q(441,1,ai,cQ);function dQ(a){GL.call(this,a,0)}q(446,415,Dh,dQ);q(583,581,ci);_.Pc=function(){!this.a.Ib?this.a.Ib=new eQ(this.a):this.a.Ib.mc.c.gb?VM(this.a.Ib.mc.c):bM(this.a.Ib)};function fQ(a,b){QK(b)==a.a?Z(b,(xy(),Gy)):Z(b,a.a)}
function gQ(a){var b,c,d,e;e=l;d=!1;QK(hQ)!=a.a?(e=va,d=!0):QK(iQ)!=a.a?(e="!#6",d=!0):QK(jQ)!=a.a?(Z(kQ,(xy(),Gy)),Z(lQ,Gy),Z(mQ,Gy),Z(nQ,Gy),e="F,Cl,Br,I"):(b=QK(oQ)!=a.a,c=QK(pQ)!=a.a,QK(qQ)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),QK(rQ)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),QK(sQ)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),QK(tQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),QK(uQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),QK(kQ)!=a.a&&(e+="F,"),QK(lQ)!=a.a&&(e+="Cl,"),QK(mQ)!=a.a&&(e+="Br,"),QK(nQ)!=a.a&&(e+="I,"),
OE(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=oc:c?e=qb:(Z(hQ,(xy(),Gy)),e=va)));b=l;d&&QK(oQ)!=a.a&&(b+=";a");d&&QK(pQ)!=a.a&&(b+=";A");QK(vQ)!=a.a&&(b+=";R");QK(wQ)!=a.a&&(b+=";!R");QK(hQ)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=xQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=yQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);QK(zQ)!=a.a&&(e="~");QK(AQ)!=a.a&&(e=gb);QK(BQ)!=a.a&&(e=pb);QK(CQ)!=a.a&&(e="!@");JL(a.e,e)}
function DQ(a){EQ(a);FQ(a);var b=xQ.mc.a;XP(b,0);b.ob.options[0].selected=!0;b=yQ.mc.a;XP(b,0);b.ob.options[0].selected=!0;Z(oQ,a.a);Z(pQ,a.a);Z(vQ,a.a);Z(wQ,a.a);Z(xQ,a.a);Z(yQ,a.a);GQ(a)}function EQ(a){Z(qQ,a.a);Z(rQ,a.a);Z(sQ,a.a);Z(tQ,a.a);Z(uQ,a.a);Z(kQ,a.a);Z(lQ,a.a);Z(mQ,a.a);Z(nQ,a.a)}function FQ(a){Z(hQ,a.a);Z(iQ,a.a);Z(jQ,a.a)}function GQ(a){Z(zQ,a.a);Z(AQ,a.a);Z(BQ,a.a);Z(CQ,a.a);a.b=!1}
function eQ(a){xL.call(this,"Atom/Bond Query");this.i=new qL(this.og());qy(this.q,new eM(this));this.a=(SA(),UA);this.c=a;this.d||(a=Bx(a),this.d=new IL(a),aM(this.d,-150,10));this.j=this.d;$x(this,new cQ);Z(this,this.a);a=new ey;$x(a,new Xy(0,3,1));$(a,new dQ("Atom type :"),null);hQ=new qL(HP);iQ=new qL("Any except C");jQ=new qL("Halogen");$(a,hQ,null);$(a,iQ,null);$(a,jQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));$(a,new GL("Or select one or more from the list :",0),null);$(this,a,null);
a=new ey;$x(a,new Xy(0,3,1));qQ=new qL(ub);rQ=new qL(Rb);sQ=new qL(Vb);tQ=new qL(cc);uQ=new qL(Wb);kQ=new qL(Cb);lQ=new qL(yb);mQ=new qL(tb);nQ=new qL(Kb);$(a,qQ,null);$(a,rQ,null);$(a,sQ,null);$(a,tQ,null);$(a,uQ,null);$(a,kQ,null);$(a,lQ,null);$(a,mQ,null);$(a,nQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));xQ=new aQ;$P(xQ,HP);$P(xQ,$a);$P(xQ,cb);$P(xQ,fb);$P(xQ,GP);$(a,new dQ("Number of hydrogens :  "),null);$(a,xQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));yQ=new aQ;$P(yQ,HP);$P(yQ,
$a);$P(yQ,cb);$P(yQ,fb);$P(yQ,GP);$P(yQ,"4");$P(yQ,"5");$P(yQ,"6");$(a,new GL("Number of connections :",0),null);$(a,yQ,null);$(a,new GL(" (H's don't count.)",0),null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));$(a,new dQ("Atom is :"),null);oQ=new qL(IP);$(a,oQ,null);pQ=new qL("Nonaromatic");$(a,pQ,null);vQ=new qL(LP);$(a,vQ,null);wQ=new qL(JP);$(a,wQ,null);$(this,a,null);a=new ey;Z(a,Ny(QK(this)));$x(a,new Xy(0,3,1));$(a,new dQ("Bond is :"),null);zQ=new qL(HP);$(a,zQ,null);AQ=new qL(IP);$(a,AQ,
null);BQ=new qL(LP);$(a,BQ,null);CQ=new qL(JP);$(a,CQ,null);$(this,a,null);a=new ey;$x(a,new Xy(1,3,1));this.e=new Bz(va,20);$(a,this.e,null);$(a,new qL(KP),null);$(a,this.i,null);$(this,a,null);this.mc&&zL(this.mc.c,!1);wL(this,!1);EQ(this);FQ(this);GQ(this);Z(oQ,this.a);Z(pQ,this.a);Z(vQ,this.a);Z(wQ,this.a);Z(xQ,this.a);Z(yQ,this.a);fQ(this,hQ);vL(this);a=this.j;cM(this.mc.c,a.a,a.b);!Ax(this)&&ZK(this);UK(this)}q(593,575,SH,eQ);
_.pg=function(a,b){var c;H(b,KP)?(DQ(this),fQ(this,hQ),gQ(this)):D(a.f,89)?(GQ(this),Kr(a.f)===Kr(hQ)?(EQ(this),FQ(this)):Kr(a.f)===Kr(iQ)?(EQ(this),FQ(this)):Kr(a.f)===Kr(jQ)?(EQ(this),FQ(this)):Kr(a.f)===Kr(vQ)?Z(wQ,this.a):Kr(a.f)===Kr(wQ)?(Z(vQ,this.a),Z(oQ,this.a)):Kr(a.f)===Kr(oQ)?(Z(pQ,this.a),Z(wQ,this.a)):Kr(a.f)===Kr(pQ)?Z(oQ,this.a):Kr(a.f)===Kr(zQ)||Kr(a.f)===Kr(AQ)||Kr(a.f)===Kr(BQ)||Kr(a.f)===Kr(CQ)?(DQ(this),this.b=!0):FQ(this),fQ(this,a.f),gQ(this)):D(a.f,90)&&(GQ(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(xy(),Gy)),gQ(this));107!=this.c.e&&(this.c.e=107,jy(this.c));return!0};_.qg=function(){return Tm(this.e.mc.a.ob,Mg)};_.rg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var hQ=_.e=null,zQ=null,iQ=null,oQ=null,AQ=null,mQ=null,qQ=null,yQ=null,xQ=null,lQ=null,kQ=null,jQ=null,nQ=null,rQ=null,pQ=null,wQ=null,CQ=null,sQ=null,uQ=null,vQ=null,BQ=null,tQ=null;function bQ(a){XG();ZG.call(this);this.a=new YP;lu(this.a,new HQ(this,a),(TP(),TP(),UP))}q(639,637,{},bQ);_.Oe=function(){return this.a};
_.a=null;function HQ(a,b){this.a=a;this.b=b}q(640,1,{},HQ);_.a=null;_.b=null;W(593);W(428);W(639);W(640);W(361);W(215);x(OH)(3);