var UN="3",VN="Any",WN="Aromatic",XN="Nonring",YN="Reset",ZN="Ring";function $N(){$N=s;aO=new jo(Tc,new bO)}function bO(){}r(192,189,{},bO);_.Pc=function(a){Gv();rK(this,a.b,cO(a.a.a,a.a.a.ob.selectedIndex))};_.Sc=function(){return aO};var aO;function dO(a,b){if(0>b||b>=a.ob.options.length)throw new Us;}function cO(a,b){dO(a,b);return a.ob.options[b].value}function eO(){this.ob=$doc.createElement("<SELECT>");this.ob[Vc]="gwt-ListBox"}r(338,316,vh,eO);function fO(){fO=s}
function gO(a,b){if(null==b)throw new Kp("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=Em(df);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e):(c=f.options[c])?f.add(e,c.index):f.add(e)}function hO(){fO();Fv.call(this);new ri;this.mc=new iO((Gv(),this))}r(405,392,{89:1,91:1,98:1,110:1,116:1},hO);_.Yd=function(){return Kv(this.mc,this)};
_.le=function(){return(null==this.jc&&(this.jc=rv(this)),this.jc)+sa+this.uc+sa+this.vc+sa+this.rc+Hg+this.hc+(this.qc?l:",hidden")+",current="+cO(this.mc.a,this.mc.a.ob.selectedIndex)};function jO(){PJ.call(this,7)}r(418,1,rh,jO);function kO(a){RJ.call(this,a,0)}r(423,392,Wh,kO);r(549,547,Nh);_.Lc=function(){!this.a.Ib?this.a.Ib=new lO(this.a):this.a.Ib.mc.c.gb?fL(this.a.Ib.mc.c):mK(this.a.Ib)};function mO(a,b){aJ(b)==a.a?Z(b,(pw(),yw)):Z(b,a.a)}
function nO(a){var b,c,d,e;e=l;d=!1;aJ(oO)!=a.a?(e=qa,d=!0):aJ(pO)!=a.a?(e="!#6",d=!0):aJ(qO)!=a.a?(Z(rO,(pw(),yw)),Z(sO,yw),Z(vO,yw),Z(wO,yw),e="F,Cl,Br,I"):(b=aJ(xO)!=a.a,c=aJ(yO)!=a.a,aJ(zO)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),aJ(AO)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),aJ(BO)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),aJ(CO)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),aJ(DO)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),aJ(rO)!=a.a&&(e+="F,"),aJ(sO)!=a.a&&(e+="Cl,"),aJ(vO)!=a.a&&(e+="Br,"),aJ(wO)!=a.a&&(e+="I,"),
tC(e,sa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=nc:c?e=lb:(Z(oO,(pw(),yw)),e=qa)));b=l;d&&aJ(xO)!=a.a&&(b+=";a");d&&aJ(yO)!=a.a&&(b+=";A");aJ(EO)!=a.a&&(b+=";R");aJ(FO)!=a.a&&(b+=";!R");aJ(oO)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=GO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=HO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);aJ(IO)!=a.a&&(e="~");aJ(JO)!=a.a&&(e=ab);aJ(KO)!=a.a&&(e=kb);aJ(LO)!=a.a&&(e="!@");UJ(a.e,e)}
function MO(a){NO(a);OO(a);var b=GO.mc.a;dO(b,0);b.ob.options[0].selected=!0;b=HO.mc.a;dO(b,0);b.ob.options[0].selected=!0;Z(xO,a.a);Z(yO,a.a);Z(EO,a.a);Z(FO,a.a);Z(GO,a.a);Z(HO,a.a);PO(a)}function NO(a){Z(zO,a.a);Z(AO,a.a);Z(BO,a.a);Z(CO,a.a);Z(DO,a.a);Z(rO,a.a);Z(sO,a.a);Z(vO,a.a);Z(wO,a.a)}function OO(a){Z(oO,a.a);Z(pO,a.a);Z(qO,a.a)}function PO(a){Z(IO,a.a);Z(JO,a.a);Z(KO,a.a);Z(LO,a.a);a.b=!1}
function lO(a){IJ.call(this,"Atom/Bond Query");this.i=new BJ(this.dg());iw(this.q,new pK(this));this.a=(xy(),zy);this.c=a;this.d||(a=uv(a),this.d=new TJ(a),lK(this.d,-150,10));this.j=this.d;Tv(this,new jO);Z(this,this.a);a=new Yv;Tv(a,new Pw(0,3,1));$(a,new kO("Atom type :"),null);oO=new BJ(VN);pO=new BJ("Any except C");qO=new BJ("Halogen");$(a,oO,null);$(a,pO,null);$(a,qO,null);$(this,a,null);a=new Yv;Tv(a,new Pw(0,3,1));$(a,new RJ("Or select one or more from the list :",0),null);$(this,a,null);
a=new Yv;Tv(a,new Pw(0,3,1));zO=new BJ(ob);AO=new BJ(Kb);BO=new BJ(Ob);CO=new BJ(Xb);DO=new BJ(Pb);rO=new BJ(yb);sO=new BJ(tb);vO=new BJ(nb);wO=new BJ(Db);$(a,zO,null);$(a,AO,null);$(a,BO,null);$(a,CO,null);$(a,DO,null);$(a,rO,null);$(a,sO,null);$(a,vO,null);$(a,wO,null);$(this,a,null);a=new Yv;Tv(a,new Pw(0,3,1));GO=new hO;gO(GO,VN);gO(GO,Wa);gO(GO,Ya);gO(GO,$a);gO(GO,UN);$(a,new kO("Number of hydrogens :  "),null);$(a,GO,null);$(this,a,null);a=new Yv;Tv(a,new Pw(0,3,1));HO=new hO;gO(HO,VN);gO(HO,
Wa);gO(HO,Ya);gO(HO,$a);gO(HO,UN);gO(HO,"4");gO(HO,"5");gO(HO,"6");$(a,new RJ("Number of connections :",0),null);$(a,HO,null);$(a,new RJ(" (H's don't count.)",0),null);$(this,a,null);a=new Yv;Tv(a,new Pw(0,3,1));$(a,new kO("Atom is :"),null);xO=new BJ(WN);$(a,xO,null);yO=new BJ("Nonaromatic");$(a,yO,null);EO=new BJ(ZN);$(a,EO,null);FO=new BJ(XN);$(a,FO,null);$(this,a,null);a=new Yv;Z(a,Fw(aJ(this)));Tv(a,new Pw(0,3,1));$(a,new kO("Bond is :"),null);IO=new BJ(VN);$(a,IO,null);JO=new BJ(WN);$(a,JO,
null);KO=new BJ(ZN);$(a,KO,null);LO=new BJ(XN);$(a,LO,null);$(this,a,null);a=new Yv;Tv(a,new Pw(1,3,1));this.e=new ux(qa,20);$(a,this.e,null);$(a,new BJ(YN),null);$(a,this.i,null);$(this,a,null);this.mc&&KJ(this.mc.c,!1);HJ(this,!1);NO(this);OO(this);PO(this);Z(xO,this.a);Z(yO,this.a);Z(EO,this.a);Z(FO,this.a);Z(GO,this.a);Z(HO,this.a);mO(this,oO);GJ(this);a=this.j;nK(this.mc.c,a.a,a.b);!tv(this)&&jJ(this);eJ(this)}r(559,541,CF,lO);
_.eg=function(a,b){var c;H(b,YN)?(MO(this),mO(this,oO),nO(this)):E(a.f,88)?(PO(this),rq(a.f)===rq(oO)?(NO(this),OO(this)):rq(a.f)===rq(pO)?(NO(this),OO(this)):rq(a.f)===rq(qO)?(NO(this),OO(this)):rq(a.f)===rq(EO)?Z(FO,this.a):rq(a.f)===rq(FO)?(Z(EO,this.a),Z(xO,this.a)):rq(a.f)===rq(xO)?(Z(yO,this.a),Z(FO,this.a)):rq(a.f)===rq(yO)?Z(xO,this.a):rq(a.f)===rq(IO)||rq(a.f)===rq(JO)||rq(a.f)===rq(KO)||rq(a.f)===rq(LO)?(MO(this),this.b=!0):OO(this),mO(this,a.f),nO(this)):E(a.f,89)&&(PO(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(pw(),yw)),nO(this));107!=this.c.e&&(this.c.e=107,cw(this.c));return!0};_.fg=function(){return Am(this.e.mc.a.ob,xg)};_.gg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var oO=_.e=null,IO=null,pO=null,xO=null,JO=null,vO=null,zO=null,HO=null,GO=null,sO=null,rO=null,qO=null,wO=null,AO=null,yO=null,FO=null,LO=null,BO=null,DO=null,EO=null,KO=null,CO=null;function iO(a){FE();HE.call(this);this.a=new eO;os(this.a,new QO(this,a),($N(),$N(),aO))}r(604,602,{},iO);_.Fe=function(){return this.a};
_.a=null;function QO(a,b){this.a=a;this.b=b}r(605,1,{},QO);_.a=null;_.b=null;Y(559);Y(405);Y(604);Y(605);Y(338);Y(192);y(vF)(3);