var aO="3",bO="Any",cO="Aromatic",dO="Nonring",eO="Reset",fO="Ring";function gO(){gO=s;hO=new po(Xc,new iO)}function iO(){}r(196,193,{},iO);_.Tc=function(a){Yv();AK(this,a.b,jO(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return hO};var hO;function kO(a,b){if(0>b||b>=a.ob.options.length)throw new Ps;}function jO(a,b){kO(a,b);return a.ob.options[b].value}function lO(){Tt();this.ob=$doc.createElement("select");this.ob[fd]="gwt-ListBox"}r(341,319,Bh,lO);function mO(){mO=s}
function nO(a,b){if(null==b)throw new Qp("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(of);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function oO(){mO();Xv.call(this);new ui;this.mc=new pO((Yv(),this))}r(408,395,{89:1,91:1,98:1,110:1,116:1},oO);_.be=function(){return bw(this.mc,this)};
_.qe=function(){return(null==this.jc&&(this.jc=Jv(this)),this.jc)+va+this.uc+va+this.vc+va+this.rc+Mg+this.hc+(this.qc?l:",hidden")+",current="+jO(this.mc.a,this.mc.a.ob.selectedIndex)};function qO(){ZJ.call(this,7)}r(421,1,wh,qO);function rO(a){aK.call(this,a,0)}r(426,395,ci,rO);r(552,550,Nh);_.Pc=function(){!this.a.Ib?this.a.Ib=new sO(this.a):this.a.Ib.mc.c.gb?oL(this.a.Ib.mc.c):vK(this.a.Ib)};function tO(a,b){kJ(b)==a.a?Z(b,(Hw(),Qw)):Z(b,a.a)}
function uO(a){var b,c,d,e;e=l;d=!1;kJ(vO)!=a.a?(e=ta,d=!0):kJ(wO)!=a.a?(e="!#6",d=!0):kJ(xO)!=a.a?(Z(yO,(Hw(),Qw)),Z(GO,Qw),Z(HO,Qw),Z(IO,Qw),e="F,Cl,Br,I"):(b=kJ(JO)!=a.a,c=kJ(KO)!=a.a,kJ(LO)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),kJ(MO)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),kJ(NO)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),kJ(OO)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),kJ(PO)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),kJ(yO)!=a.a&&(e+="F,"),kJ(GO)!=a.a&&(e+="Cl,"),kJ(HO)!=a.a&&(e+="Br,"),kJ(IO)!=a.a&&(e+="I,"),
LC(e,va)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=nc:c?e=ob:(Z(vO,(Hw(),Qw)),e=ta)));b=l;d&&kJ(JO)!=a.a&&(b+=";a");d&&kJ(KO)!=a.a&&(b+=";A");kJ(QO)!=a.a&&(b+=";R");kJ(RO)!=a.a&&(b+=";!R");kJ(vO)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=SO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=TO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);kJ(UO)!=a.a&&(e="~");kJ(VO)!=a.a&&(e=eb);kJ(WO)!=a.a&&(e=nb);kJ(XO)!=a.a&&(e="!@");Mx(a.e.mc,e)}
function YO(a){ZO(a);$O(a);var b=SO.mc.a;kO(b,0);b.ob.options[0].selected=!0;b=TO.mc.a;kO(b,0);b.ob.options[0].selected=!0;Z(JO,a.a);Z(KO,a.a);Z(QO,a.a);Z(RO,a.a);Z(SO,a.a);Z(TO,a.a);aP(a)}function ZO(a){Z(LO,a.a);Z(MO,a.a);Z(NO,a.a);Z(OO,a.a);Z(PO,a.a);Z(yO,a.a);Z(GO,a.a);Z(HO,a.a);Z(IO,a.a)}function $O(a){Z(vO,a.a);Z(wO,a.a);Z(xO,a.a)}function aP(a){Z(UO,a.a);Z(VO,a.a);Z(WO,a.a);Z(XO,a.a);a.b=!1}
function sO(a){SJ.call(this,"Atom/Bond Query");this.i=new LJ(this.ig());Aw(this.q,new yK(this));this.a=(Py(),Ry);this.c=a;this.d||(a=Mv(a),this.d=new cK(a),uK(this.d,-150,10));this.j=this.d;kw(this,new qO);Z(this,this.a);a=new pw;kw(a,new gx(0,3,1));$(a,new rO("Atom type :"),null);vO=new LJ(bO);wO=new LJ("Any except C");xO=new LJ("Halogen");$(a,vO,null);$(a,wO,null);$(a,xO,null);$(this,a,null);a=new pw;kw(a,new gx(0,3,1));$(a,new aK("Or select one or more from the list :",0),null);$(this,a,null);
a=new pw;kw(a,new gx(0,3,1));LO=new LJ(sb);MO=new LJ(Pb);NO=new LJ(Tb);OO=new LJ(ac);PO=new LJ(Ub);yO=new LJ(Ab);GO=new LJ(wb);HO=new LJ(rb);IO=new LJ(Ib);$(a,LO,null);$(a,MO,null);$(a,NO,null);$(a,OO,null);$(a,PO,null);$(a,yO,null);$(a,GO,null);$(a,HO,null);$(a,IO,null);$(this,a,null);a=new pw;kw(a,new gx(0,3,1));SO=new oO;nO(SO,bO);nO(SO,Ya);nO(SO,$a);nO(SO,db);nO(SO,aO);$(a,new rO("Number of hydrogens :  "),null);$(a,SO,null);$(this,a,null);a=new pw;kw(a,new gx(0,3,1));TO=new oO;nO(TO,bO);nO(TO,
Ya);nO(TO,$a);nO(TO,db);nO(TO,aO);nO(TO,"4");nO(TO,"5");nO(TO,"6");$(a,new aK("Number of connections :",0),null);$(a,TO,null);$(a,new aK(" (H's don't count.)",0),null);$(this,a,null);a=new pw;kw(a,new gx(0,3,1));$(a,new rO("Atom is :"),null);JO=new LJ(cO);$(a,JO,null);KO=new LJ("Nonaromatic");$(a,KO,null);QO=new LJ(fO);$(a,QO,null);RO=new LJ(dO);$(a,RO,null);$(this,a,null);a=new pw;Z(a,Xw(kJ(this)));kw(a,new gx(0,3,1));$(a,new rO("Bond is :"),null);UO=new LJ(bO);$(a,UO,null);VO=new LJ(cO);$(a,VO,
null);WO=new LJ(fO);$(a,WO,null);XO=new LJ(dO);$(a,XO,null);$(this,a,null);a=new pw;kw(a,new gx(1,3,1));this.e=new Lx(ta,20);$(a,this.e,null);$(a,new LJ(eO),null);$(a,this.i,null);$(this,a,null);this.mc&&UJ(this.mc.c,!1);RJ(this,!1);ZO(this);$O(this);aP(this);Z(JO,this.a);Z(KO,this.a);Z(QO,this.a);Z(RO,this.a);Z(SO,this.a);Z(TO,this.a);tO(this,vO);QJ(this);a=this.j;wK(this.mc.c,a.a,a.b);!Lv(this)&&tJ(this);oJ(this)}r(562,544,RF,sO);
_.jg=function(a,b){var c;H(b,eO)?(YO(this),tO(this,vO),uO(this)):E(a.f,88)?(aP(this),xq(a.f)===xq(vO)?(ZO(this),$O(this)):xq(a.f)===xq(wO)?(ZO(this),$O(this)):xq(a.f)===xq(xO)?(ZO(this),$O(this)):xq(a.f)===xq(QO)?Z(RO,this.a):xq(a.f)===xq(RO)?(Z(QO,this.a),Z(JO,this.a)):xq(a.f)===xq(JO)?(Z(KO,this.a),Z(RO,this.a)):xq(a.f)===xq(KO)?Z(JO,this.a):xq(a.f)===xq(UO)||xq(a.f)===xq(VO)||xq(a.f)===xq(WO)||xq(a.f)===xq(XO)?(YO(this),this.b=!0):$O(this),tO(this,a.f),uO(this)):E(a.f,89)&&(aP(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(Hw(),Qw)),uO(this));107!=this.c.e&&(this.c.e=107,uw(this.c));return!0};_.kg=function(){return Lm(this.e.mc.a.ob,Gg)};_.lg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var vO=_.e=null,UO=null,wO=null,JO=null,VO=null,HO=null,LO=null,TO=null,SO=null,GO=null,yO=null,xO=null,IO=null,MO=null,KO=null,RO=null,XO=null,NO=null,PO=null,QO=null,WO=null,OO=null;function pO(a){UE();WE.call(this);this.a=new lO;ws(this.a,new bP(this,a),(gO(),gO(),hO))}r(608,606,{},pO);_.Ke=function(){return this.a};
_.a=null;function bP(a,b){this.a=a;this.b=b}r(609,1,{},bP);_.a=null;_.b=null;Y(562);Y(408);Y(608);Y(609);Y(341);Y(196);y(KF)(3);