var cQ="3",dQ="Any",eQ="Aromatic",fQ="Nonring",gQ="Reset",oQ="Ring";function pQ(){pQ=r;qQ=new Fp(Xc,new rQ)}function rQ(){}q(217,214,{},rQ);_.Tc=function(a){dy();CM(this,a.b,sQ(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return qQ};var qQ;function tQ(a,b){if(0>b||b>=a.ob.options.length)throw new Zu;}function sQ(a,b){tQ(a,b);return a.ob.options[b].value}function uQ(){this.ob=$doc.createElement("select");this.ob[Zc]="gwt-ListBox"}q(364,342,ci,uQ);function vQ(){vQ=r}
function wQ(a,b){if(null==b)throw new wr("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(tf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function xQ(){vQ();cy.call(this);new Gi;this.mc=new yQ((dy(),this))}q(432,419,{91:1,93:1,100:1,112:1,118:1},xQ);_.ee=function(){return hy(this.mc,this)};
_.te=function(){return(null==this.jc&&(this.jc=Px(this)),this.jc)+xa+this.uc+xa+this.vc+xa+this.rc+Sg+this.hc+(this.qc?l:",hidden")+",current="+sQ(this.mc.a,this.mc.a.ob.selectedIndex)};function zQ(){$L.call(this,7)}q(445,1,ni,zQ);function AQ(a){bM.call(this,a,0)}q(450,419,Th,AQ);q(587,585,Hh);_.Pc=function(){!this.a.Ib?this.a.Ib=new BQ(this.a):this.a.Ib.mc.c.gb?qN(this.a.Ib.mc.c):xM(this.a.Ib)};function CQ(a,b){lL(b)==a.a?Z(b,(Oy(),Xy)):Z(b,a.a)}
function DQ(a){var b,c,d,e;e=l;d=!1;lL(EQ)!=a.a?(e=va,d=!0):lL(FQ)!=a.a?(e="!#6",d=!0):lL(GQ)!=a.a?(Z(HQ,(Oy(),Xy)),Z(IQ,Xy),Z(JQ,Xy),Z(KQ,Xy),e="F,Cl,Br,I"):(b=lL(LQ)!=a.a,c=lL(MQ)!=a.a,lL(NQ)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),lL(OQ)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),lL(PQ)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),lL(QQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),lL(RQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),lL(HQ)!=a.a&&(e+="F,"),lL(IQ)!=a.a&&(e+="Cl,"),lL(JQ)!=a.a&&(e+="Br,"),lL(KQ)!=a.a&&(e+="I,"),
fF(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=pc:c?e=qb:(Z(EQ,(Oy(),Xy)),e=va)));b=l;d&&lL(LQ)!=a.a&&(b+=";a");d&&lL(MQ)!=a.a&&(b+=";A");lL(SQ)!=a.a&&(b+=";R");lL(TQ)!=a.a&&(b+=";!R");lL(EQ)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=UQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=VQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);lL(WQ)!=a.a&&(e="~");lL(XQ)!=a.a&&(e=gb);lL(YQ)!=a.a&&(e=pb);lL(ZQ)!=a.a&&(e="!@");eM(a.e,e)}
function $Q(a){aR(a);bR(a);var b=UQ.mc.a;tQ(b,0);b.ob.options[0].selected=!0;b=VQ.mc.a;tQ(b,0);b.ob.options[0].selected=!0;Z(LQ,a.a);Z(MQ,a.a);Z(SQ,a.a);Z(TQ,a.a);Z(UQ,a.a);Z(VQ,a.a);cR(a)}function aR(a){Z(NQ,a.a);Z(OQ,a.a);Z(PQ,a.a);Z(QQ,a.a);Z(RQ,a.a);Z(HQ,a.a);Z(IQ,a.a);Z(JQ,a.a);Z(KQ,a.a)}function bR(a){Z(EQ,a.a);Z(FQ,a.a);Z(GQ,a.a)}function cR(a){Z(WQ,a.a);Z(XQ,a.a);Z(YQ,a.a);Z(ZQ,a.a);a.b=!1}
function BQ(a){TL.call(this,"Atom/Bond Query");this.i=new ML(this.ng());Hy(this.q,new AM(this));this.a=(lB(),nB);this.c=a;this.d||(a=Sx(a),this.d=new dM(a),wM(this.d,-150,10));this.j=this.d;qy(this,new zQ);Z(this,this.a);a=new vy;qy(a,new nz(0,3,1));$(a,new AQ("Atom type :"),null);EQ=new ML(dQ);FQ=new ML("Any except C");GQ=new ML("Halogen");$(a,EQ,null);$(a,FQ,null);$(a,GQ,null);$(this,a,null);a=new vy;qy(a,new nz(0,3,1));$(a,new bM("Or select one or more from the list :",0),null);$(this,a,null);
a=new vy;qy(a,new nz(0,3,1));NQ=new ML(tb);OQ=new ML(Rb);PQ=new ML(Vb);QQ=new ML(cc);RQ=new ML(Wb);HQ=new ML(Cb);IQ=new ML(xb);JQ=new ML(sb);KQ=new ML(Kb);$(a,NQ,null);$(a,OQ,null);$(a,PQ,null);$(a,QQ,null);$(a,RQ,null);$(a,HQ,null);$(a,IQ,null);$(a,JQ,null);$(a,KQ,null);$(this,a,null);a=new vy;qy(a,new nz(0,3,1));UQ=new xQ;wQ(UQ,dQ);wQ(UQ,$a);wQ(UQ,bb);wQ(UQ,fb);wQ(UQ,cQ);$(a,new AQ("Number of hydrogens :  "),null);$(a,UQ,null);$(this,a,null);a=new vy;qy(a,new nz(0,3,1));VQ=new xQ;wQ(VQ,dQ);wQ(VQ,
$a);wQ(VQ,bb);wQ(VQ,fb);wQ(VQ,cQ);wQ(VQ,"4");wQ(VQ,"5");wQ(VQ,"6");$(a,new bM("Number of connections :",0),null);$(a,VQ,null);$(a,new bM(" (H's don't count.)",0),null);$(this,a,null);a=new vy;qy(a,new nz(0,3,1));$(a,new AQ("Atom is :"),null);LQ=new ML(eQ);$(a,LQ,null);MQ=new ML("Nonaromatic");$(a,MQ,null);SQ=new ML(oQ);$(a,SQ,null);TQ=new ML(fQ);$(a,TQ,null);$(this,a,null);a=new vy;Z(a,dz(lL(this)));qy(a,new nz(0,3,1));$(a,new AQ("Bond is :"),null);WQ=new ML(dQ);$(a,WQ,null);XQ=new ML(eQ);$(a,XQ,
null);YQ=new ML(oQ);$(a,YQ,null);ZQ=new ML(fQ);$(a,ZQ,null);$(this,a,null);a=new vy;qy(a,new nz(1,3,1));this.e=new Tz(va,20);$(a,this.e,null);$(a,new ML(gQ),null);$(a,this.i,null);$(this,a,null);this.mc&&VL(this.mc.c,!1);SL(this,!1);aR(this);bR(this);cR(this);Z(LQ,this.a);Z(MQ,this.a);Z(SQ,this.a);Z(TQ,this.a);Z(UQ,this.a);Z(VQ,this.a);CQ(this,EQ);RL(this);a=this.j;yM(this.mc.c,a.a,a.b);!Rx(this)&&uL(this);pL(this)}q(597,579,iI,BQ);
_.og=function(a,b){var c;H(b,gQ)?($Q(this),CQ(this,EQ),DQ(this)):D(a.f,90)?(cR(this),ds(a.f)===ds(EQ)?(aR(this),bR(this)):ds(a.f)===ds(FQ)?(aR(this),bR(this)):ds(a.f)===ds(GQ)?(aR(this),bR(this)):ds(a.f)===ds(SQ)?Z(TQ,this.a):ds(a.f)===ds(TQ)?(Z(SQ,this.a),Z(LQ,this.a)):ds(a.f)===ds(LQ)?(Z(MQ,this.a),Z(TQ,this.a)):ds(a.f)===ds(MQ)?Z(LQ,this.a):ds(a.f)===ds(WQ)||ds(a.f)===ds(XQ)||ds(a.f)===ds(YQ)||ds(a.f)===ds(ZQ)?($Q(this),this.b=!0):bR(this),CQ(this,a.f),DQ(this)):D(a.f,91)&&(cR(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(Oy(),Xy)),DQ(this));107!=this.c.e&&(this.c.e=107,Ay(this.c));return!0};_.pg=function(){return Zm(this.e.mc.a.ob,Mg)};_.qg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var EQ=_.e=null,WQ=null,FQ=null,LQ=null,XQ=null,JQ=null,NQ=null,VQ=null,UQ=null,IQ=null,HQ=null,GQ=null,KQ=null,OQ=null,MQ=null,TQ=null,ZQ=null,PQ=null,RQ=null,SQ=null,YQ=null,QQ=null;function yQ(a){nH();pH.call(this);this.a=new uQ;Gu(this.a,new dR(this,a),(pQ(),pQ(),qQ))}q(643,641,{},yQ);_.Ne=function(){return this.a};
_.a=null;function dR(a,b){this.a=a;this.b=b}q(644,1,{},dR);_.a=null;_.b=null;W(597);W(432);W(643);W(644);W(364);W(217);x(fI)(3);