var HP="3",IP="Any",JP="Aromatic",KP="Nonring",LP="Reset",MP="Ring";function UP(){UP=r;VP=new lp(fd,new WP)}function WP(){}q(215,212,{},WP);_.Tc=function(a){Nx();hM(this,a.b,XP(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return VP};var VP;function YP(a,b){if(0>b||b>=a.ob.options.length)throw new Eu;}function XP(a,b){YP(a,b);return a.ob.options[b].value}function ZP(){wv();this.ob=$doc.createElement("select");this.ob[hd]="gwt-ListBox"}q(361,339,ci,ZP);function $P(){$P=r}
function aQ(a,b){if(null==b)throw new cr("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(tf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function bQ(){$P();Mx.call(this);new Ei;this.mc=new cQ((Nx(),this))}q(428,415,{90:1,92:1,99:1,111:1,117:1},bQ);_.fe=function(){return Rx(this.mc,this)};
_.ue=function(){return(null==this.jc&&(this.jc=yx(this)),this.jc)+xa+this.uc+xa+this.vc+xa+this.rc+Tg+this.hc+(this.qc?l:",hidden")+",current="+XP(this.mc.a,this.mc.a.ob.selectedIndex)};function dQ(){FL.call(this,7)}q(441,1,bi,dQ);function eQ(a){HL.call(this,a,0)}q(446,415,Eh,eQ);q(583,581,di);_.Pc=function(){!this.a.Ib?this.a.Ib=new fQ(this.a):this.a.Ib.mc.c.gb?WM(this.a.Ib.mc.c):cM(this.a.Ib)};function gQ(a,b){RK(b)==a.a?Z(b,(xy(),Gy)):Z(b,a.a)}
function hQ(a){var b,c,d,e;e=l;d=!1;RK(iQ)!=a.a?(e=va,d=!0):RK(jQ)!=a.a?(e="!#6",d=!0):RK(kQ)!=a.a?(Z(lQ,(xy(),Gy)),Z(mQ,Gy),Z(nQ,Gy),Z(oQ,Gy),e="F,Cl,Br,I"):(b=RK(pQ)!=a.a,c=RK(qQ)!=a.a,RK(rQ)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),RK(sQ)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),RK(tQ)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),RK(uQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),RK(vQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),RK(lQ)!=a.a&&(e+="F,"),RK(mQ)!=a.a&&(e+="Cl,"),RK(nQ)!=a.a&&(e+="Br,"),RK(oQ)!=a.a&&(e+="I,"),
QE(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=tc:c?e=qb:(Z(iQ,(xy(),Gy)),e=va)));b=l;d&&RK(pQ)!=a.a&&(b+=";a");d&&RK(qQ)!=a.a&&(b+=";A");RK(wQ)!=a.a&&(b+=";R");RK(xQ)!=a.a&&(b+=";!R");RK(iQ)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=yQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=zQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);RK(AQ)!=a.a&&(e="~");RK(BQ)!=a.a&&(e=gb);RK(CQ)!=a.a&&(e=pb);RK(DQ)!=a.a&&(e="!@");KL(a.e,e)}
function EQ(a){FQ(a);GQ(a);var b=yQ.mc.a;YP(b,0);b.ob.options[0].selected=!0;b=zQ.mc.a;YP(b,0);b.ob.options[0].selected=!0;Z(pQ,a.a);Z(qQ,a.a);Z(wQ,a.a);Z(xQ,a.a);Z(yQ,a.a);Z(zQ,a.a);HQ(a)}function FQ(a){Z(rQ,a.a);Z(sQ,a.a);Z(tQ,a.a);Z(uQ,a.a);Z(vQ,a.a);Z(lQ,a.a);Z(mQ,a.a);Z(nQ,a.a);Z(oQ,a.a)}function GQ(a){Z(iQ,a.a);Z(jQ,a.a);Z(kQ,a.a)}function HQ(a){Z(AQ,a.a);Z(BQ,a.a);Z(CQ,a.a);Z(DQ,a.a);a.b=!1}
function fQ(a){yL.call(this,"Atom/Bond Query");this.i=new rL(this.og());qy(this.q,new fM(this));this.a=(UA(),WA);this.c=a;this.d||(a=Bx(a),this.d=new JL(a),bM(this.d,-150,10));this.j=this.d;$x(this,new dQ);Z(this,this.a);a=new ey;$x(a,new Xy(0,3,1));$(a,new eQ("Atom type :"),null);iQ=new rL(IP);jQ=new rL("Any except C");kQ=new rL("Halogen");$(a,iQ,null);$(a,jQ,null);$(a,kQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));$(a,new HL("Or select one or more from the list :",0),null);$(this,a,null);
a=new ey;$x(a,new Xy(0,3,1));rQ=new rL(ub);sQ=new rL(Rb);tQ=new rL(Vb);uQ=new rL(cc);vQ=new rL(Wb);lQ=new rL(Gb);mQ=new rL(yb);nQ=new rL(tb);oQ=new rL(Kb);$(a,rQ,null);$(a,sQ,null);$(a,tQ,null);$(a,uQ,null);$(a,vQ,null);$(a,lQ,null);$(a,mQ,null);$(a,nQ,null);$(a,oQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));yQ=new bQ;aQ(yQ,IP);aQ(yQ,$a);aQ(yQ,cb);aQ(yQ,fb);aQ(yQ,HP);$(a,new eQ("Number of hydrogens :  "),null);$(a,yQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));zQ=new bQ;aQ(zQ,IP);aQ(zQ,
$a);aQ(zQ,cb);aQ(zQ,fb);aQ(zQ,HP);aQ(zQ,"4");aQ(zQ,"5");aQ(zQ,"6");$(a,new HL("Number of connections :",0),null);$(a,zQ,null);$(a,new HL(" (H's don't count.)",0),null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));$(a,new eQ("Atom is :"),null);pQ=new rL(JP);$(a,pQ,null);qQ=new rL("Nonaromatic");$(a,qQ,null);wQ=new rL(MP);$(a,wQ,null);xQ=new rL(KP);$(a,xQ,null);$(this,a,null);a=new ey;Z(a,Ny(RK(this)));$x(a,new Xy(0,3,1));$(a,new eQ("Bond is :"),null);AQ=new rL(IP);$(a,AQ,null);BQ=new rL(JP);$(a,BQ,
null);CQ=new rL(MP);$(a,CQ,null);DQ=new rL(KP);$(a,DQ,null);$(this,a,null);a=new ey;$x(a,new Xy(1,3,1));this.e=new Bz(va,20);$(a,this.e,null);$(a,new rL(LP),null);$(a,this.i,null);$(this,a,null);this.mc&&AL(this.mc.c,!1);xL(this,!1);FQ(this);GQ(this);HQ(this);Z(pQ,this.a);Z(qQ,this.a);Z(wQ,this.a);Z(xQ,this.a);Z(yQ,this.a);Z(zQ,this.a);gQ(this,iQ);wL(this);a=this.j;dM(this.mc.c,a.a,a.b);!Ax(this)&&$K(this);VK(this)}q(593,575,TH,fQ);
_.pg=function(a,b){var c;H(b,LP)?(EQ(this),gQ(this,iQ),hQ(this)):D(a.f,89)?(HQ(this),Kr(a.f)===Kr(iQ)?(FQ(this),GQ(this)):Kr(a.f)===Kr(jQ)?(FQ(this),GQ(this)):Kr(a.f)===Kr(kQ)?(FQ(this),GQ(this)):Kr(a.f)===Kr(wQ)?Z(xQ,this.a):Kr(a.f)===Kr(xQ)?(Z(wQ,this.a),Z(pQ,this.a)):Kr(a.f)===Kr(pQ)?(Z(qQ,this.a),Z(xQ,this.a)):Kr(a.f)===Kr(qQ)?Z(pQ,this.a):Kr(a.f)===Kr(AQ)||Kr(a.f)===Kr(BQ)||Kr(a.f)===Kr(CQ)||Kr(a.f)===Kr(DQ)?(EQ(this),this.b=!0):GQ(this),gQ(this,a.f),hQ(this)):D(a.f,90)&&(HQ(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(xy(),Gy)),hQ(this));107!=this.c.e&&(this.c.e=107,jy(this.c));return!0};_.qg=function(){return Um(this.e.mc.a.ob,Ng)};_.rg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var iQ=_.e=null,AQ=null,jQ=null,pQ=null,BQ=null,nQ=null,rQ=null,zQ=null,yQ=null,mQ=null,lQ=null,kQ=null,oQ=null,sQ=null,qQ=null,xQ=null,DQ=null,tQ=null,vQ=null,wQ=null,CQ=null,uQ=null;function cQ(a){YG();$G.call(this);this.a=new ZP;lu(this.a,new IQ(this,a),(UP(),UP(),VP))}q(639,637,{},cQ);_.Oe=function(){return this.a};
_.a=null;function IQ(a,b){this.a=a;this.b=b}q(640,1,{},IQ);_.a=null;_.b=null;W(593);W(428);W(639);W(640);W(361);W(215);x(PH)(3);