var RN="3",SN="Any",TN="Aromatic",UN="Nonring",VN="Reset",WN="Ring";function XN(){XN=s;YN=new jo(Tc,new ZN)}function ZN(){}r(192,189,{},ZN);_.Pc=function(a){Gv();qK(this,a.b,$N(a.a.a,a.a.a.ob.selectedIndex))};_.Sc=function(){return YN};var YN;function aO(a,b){if(0>b||b>=a.ob.options.length)throw new Us;}function $N(a,b){aO(a,b);return a.ob.options[b].value}function bO(){this.ob=$doc.createElement("<SELECT>");this.ob[Vc]="gwt-ListBox"}r(338,316,vh,bO);function cO(){cO=s}
function dO(a,b){if(null==b)throw new Kp("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=Em(df);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e):(c=f.options[c])?f.add(e,c.index):f.add(e)}function eO(){cO();Fv.call(this);new ri;this.mc=new fO((Gv(),this))}r(405,392,{89:1,91:1,98:1,110:1,116:1},eO);_.Yd=function(){return Kv(this.mc,this)};
_.le=function(){return(null==this.jc&&(this.jc=rv(this)),this.jc)+sa+this.uc+sa+this.vc+sa+this.rc+Hg+this.hc+(this.qc?l:",hidden")+",current="+$N(this.mc.a,this.mc.a.ob.selectedIndex)};function gO(){OJ.call(this,7)}r(418,1,rh,gO);function hO(a){QJ.call(this,a,0)}r(423,392,Wh,hO);r(549,547,Nh);_.Lc=function(){!this.a.Ib?this.a.Ib=new iO(this.a):this.a.Ib.mc.c.gb?eL(this.a.Ib.mc.c):lK(this.a.Ib)};function jO(a,b){$I(b)==a.a?Z(b,(pw(),yw)):Z(b,a.a)}
function kO(a){var b,c,d,e;e=l;d=!1;$I(lO)!=a.a?(e=qa,d=!0):$I(mO)!=a.a?(e="!#6",d=!0):$I(nO)!=a.a?(Z(oO,(pw(),yw)),Z(pO,yw),Z(sO,yw),Z(tO,yw),e="F,Cl,Br,I"):(b=$I(uO)!=a.a,c=$I(vO)!=a.a,$I(wO)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),$I(xO)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),$I(yO)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),$I(zO)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),$I(AO)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),$I(oO)!=a.a&&(e+="F,"),$I(pO)!=a.a&&(e+="Cl,"),$I(sO)!=a.a&&(e+="Br,"),$I(tO)!=a.a&&(e+="I,"),
tC(e,sa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=nc:c?e=lb:(Z(lO,(pw(),yw)),e=qa)));b=l;d&&$I(uO)!=a.a&&(b+=";a");d&&$I(vO)!=a.a&&(b+=";A");$I(BO)!=a.a&&(b+=";R");$I(CO)!=a.a&&(b+=";!R");$I(lO)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=DO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=EO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);$I(FO)!=a.a&&(e="~");$I(GO)!=a.a&&(e=ab);$I(HO)!=a.a&&(e=kb);$I(IO)!=a.a&&(e="!@");TJ(a.e,e)}
function JO(a){KO(a);LO(a);var b=DO.mc.a;aO(b,0);b.ob.options[0].selected=!0;b=EO.mc.a;aO(b,0);b.ob.options[0].selected=!0;Z(uO,a.a);Z(vO,a.a);Z(BO,a.a);Z(CO,a.a);Z(DO,a.a);Z(EO,a.a);MO(a)}function KO(a){Z(wO,a.a);Z(xO,a.a);Z(yO,a.a);Z(zO,a.a);Z(AO,a.a);Z(oO,a.a);Z(pO,a.a);Z(sO,a.a);Z(tO,a.a)}function LO(a){Z(lO,a.a);Z(mO,a.a);Z(nO,a.a)}function MO(a){Z(FO,a.a);Z(GO,a.a);Z(HO,a.a);Z(IO,a.a);a.b=!1}
function iO(a){HJ.call(this,"Atom/Bond Query");this.i=new AJ(this.dg());iw(this.q,new oK(this));this.a=(xy(),zy);this.c=a;this.d||(a=uv(a),this.d=new SJ(a),kK(this.d,-150,10));this.j=this.d;Tv(this,new gO);Z(this,this.a);a=new Yv;Tv(a,new Pw(0,3,1));$(a,new hO("Atom type :"),null);lO=new AJ(SN);mO=new AJ("Any except C");nO=new AJ("Halogen");$(a,lO,null);$(a,mO,null);$(a,nO,null);$(this,a,null);a=new Yv;Tv(a,new Pw(0,3,1));$(a,new QJ("Or select one or more from the list :",0),null);$(this,a,null);
a=new Yv;Tv(a,new Pw(0,3,1));wO=new AJ(qb);xO=new AJ(Kb);yO=new AJ(Ob);zO=new AJ(Xb);AO=new AJ(Pb);oO=new AJ(yb);pO=new AJ(tb);sO=new AJ(pb);tO=new AJ(Db);$(a,wO,null);$(a,xO,null);$(a,yO,null);$(a,zO,null);$(a,AO,null);$(a,oO,null);$(a,pO,null);$(a,sO,null);$(a,tO,null);$(this,a,null);a=new Yv;Tv(a,new Pw(0,3,1));DO=new eO;dO(DO,SN);dO(DO,Wa);dO(DO,Ya);dO(DO,$a);dO(DO,RN);$(a,new hO("Number of hydrogens :  "),null);$(a,DO,null);$(this,a,null);a=new Yv;Tv(a,new Pw(0,3,1));EO=new eO;dO(EO,SN);dO(EO,
Wa);dO(EO,Ya);dO(EO,$a);dO(EO,RN);dO(EO,"4");dO(EO,"5");dO(EO,"6");$(a,new QJ("Number of connections :",0),null);$(a,EO,null);$(a,new QJ(" (H's don't count.)",0),null);$(this,a,null);a=new Yv;Tv(a,new Pw(0,3,1));$(a,new hO("Atom is :"),null);uO=new AJ(TN);$(a,uO,null);vO=new AJ("Nonaromatic");$(a,vO,null);BO=new AJ(WN);$(a,BO,null);CO=new AJ(UN);$(a,CO,null);$(this,a,null);a=new Yv;Z(a,Fw($I(this)));Tv(a,new Pw(0,3,1));$(a,new hO("Bond is :"),null);FO=new AJ(SN);$(a,FO,null);GO=new AJ(TN);$(a,GO,
null);HO=new AJ(WN);$(a,HO,null);IO=new AJ(UN);$(a,IO,null);$(this,a,null);a=new Yv;Tv(a,new Pw(1,3,1));this.e=new ux(qa,20);$(a,this.e,null);$(a,new AJ(VN),null);$(a,this.i,null);$(this,a,null);this.mc&&JJ(this.mc.c,!1);GJ(this,!1);KO(this);LO(this);MO(this);Z(uO,this.a);Z(vO,this.a);Z(BO,this.a);Z(CO,this.a);Z(DO,this.a);Z(EO,this.a);jO(this,lO);FJ(this);a=this.j;mK(this.mc.c,a.a,a.b);!tv(this)&&iJ(this);dJ(this)}r(559,541,CF,iO);
_.eg=function(a,b){var c;H(b,VN)?(JO(this),jO(this,lO),kO(this)):E(a.f,88)?(MO(this),rq(a.f)===rq(lO)?(KO(this),LO(this)):rq(a.f)===rq(mO)?(KO(this),LO(this)):rq(a.f)===rq(nO)?(KO(this),LO(this)):rq(a.f)===rq(BO)?Z(CO,this.a):rq(a.f)===rq(CO)?(Z(BO,this.a),Z(uO,this.a)):rq(a.f)===rq(uO)?(Z(vO,this.a),Z(CO,this.a)):rq(a.f)===rq(vO)?Z(uO,this.a):rq(a.f)===rq(FO)||rq(a.f)===rq(GO)||rq(a.f)===rq(HO)||rq(a.f)===rq(IO)?(JO(this),this.b=!0):LO(this),jO(this,a.f),kO(this)):E(a.f,89)&&(MO(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(pw(),yw)),kO(this));107!=this.c.e&&(this.c.e=107,cw(this.c));return!0};_.fg=function(){return Am(this.e.mc.a.ob,xg)};_.gg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var lO=_.e=null,FO=null,mO=null,uO=null,GO=null,sO=null,wO=null,EO=null,DO=null,pO=null,oO=null,nO=null,tO=null,xO=null,vO=null,CO=null,IO=null,yO=null,AO=null,BO=null,HO=null,zO=null;function fO(a){FE();HE.call(this);this.a=new bO;os(this.a,new NO(this,a),(XN(),XN(),YN))}r(604,602,{},fO);_.Fe=function(){return this.a};
_.a=null;function NO(a,b){this.a=a;this.b=b}r(605,1,{},NO);_.a=null;_.b=null;Y(559);Y(405);Y(604);Y(605);Y(338);Y(192);y(vF)(3);