var DZ=" (H's don't count.)",EZ="!#6",FZ="!@",GZ="#15,",HZ="#16,",IZ="#6,",JZ="#7,",KZ="#8,",LZ="3",MZ="4",NZ="5",OZ="6",PZ=";!R",QZ=";A",RZ=";D",SZ=";H",TZ=";R",UZ=";a",VZ="<SELECT>",WZ="Any",XZ="Any except C",YZ="Aromatic",ZZ="Atom is :",$Z="Atom type :",a_="Atom/Bond Query",b_="Bond is :",c_="Br,",d_="C,",e_="Cl,",f_="F,",g_="F,Cl,Br,I",h_="Halogen",i_="I,",j_="Missing message: awt.103",k_="N,",l_="Nonaromatic",m_="Nonring",n_="Number of connections :",o_="Number of hydrogens :  ",p_="O,",q_="Or select one or more from the list :",
r_="P,",s_="Reset",t_="Ring",u_="S,",v_="bidiwrapped",w_="c,",x_="gwt-ListBox",y_="n,",z_="o,",A_="p,",B_="s,",C_="~";function D_(){D_=s;E_=new Hx(qj,new F_)}function F_(){}r(193,190,{},F_);_.Pc=function(a){cF();aW(this,a.b,G_(a.a.a,a.a.a.ob.selectedIndex))};_.Sc=function(){return E_};var E_;function H_(a,b){if(0>b||b>=a.ob.options.length)throw new hC;}function G_(a,b){H_(a,b);return a.ob.options[b].value}function I_(){var a;this.ob=(a=VZ,$doc.createElement(a));this.ob[vj]=x_}r(341,319,hr,I_);
function J_(){J_=s}function K_(a,b){if(null==b)throw new hz(j_);var c=-1,d,e,f;f=a.mc.a.ob;e=H(Hn);e.text=b;e.removeAttribute(v_);e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e):(c=f.options[c])?f.add(e,c.index):f.add(e)}function L_(){J_();bF.call(this);new Yr;this.mc=new M_((cF(),this))}r(410,397,{89:1,91:1,98:1,110:1,116:1},L_);_.ae=function(){return gF(this.mc,this)};
_.pe=function(){return(null==this.jc&&(this.jc=OE(this)),this.jc)+ib+this.uc+ib+this.vc+ib+this.rc+qq+this.hc+(this.qc?l:",hidden")+",current="+G_(this.mc.a,this.mc.a.ob.selectedIndex)};function N_(){zV.call(this,7)}r(423,1,dr,N_);function O_(a){BV.call(this,a,0)}r(428,397,Cr,O_);r(554,552,tr);_.Lc=function(){!this.a.Ib?this.a.Ib=new P_(this.a):this.a.Ib.mc.c.gb?PW(this.a.Ib.mc.c):WV(this.a.Ib)};function Q_(a,b){LU(b)==a.a?Z(b,(MF(),VF)):Z(b,a.a)}
function R_(a){var b,c,d,e;e=l;d=!1;LU(S_)!=a.a?(e=gb,d=!0):LU(T_)!=a.a?(e=EZ,d=!0):LU(U_)!=a.a?(Z(V_,(MF(),VF)),Z(W_,VF),Z(X_,VF),Z(Y_,VF),e=g_):(b=LU(Z_)!=a.a,c=LU($_)!=a.a,LU(a0)!=a.a&&(b?e+=w_:c?e+=d_:e+=IZ),LU(b0)!=a.a&&(b?e+=y_:c?e+=k_:e+=JZ),LU(c0)!=a.a&&(b?e+=z_:c?e+=p_:e+=KZ),LU(d0)!=a.a&&(b?e+=B_:c?e+=u_:e+=HZ),LU(e0)!=a.a&&(b?e+=A_:c?e+=r_:e+=GZ),LU(V_)!=a.a&&(e+=f_),LU(W_)!=a.a&&(e+=e_),LU(X_)!=a.a&&(e+=c_),LU(Y_)!=a.a&&(e+=i_),$L(e,ib)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&
(b?e=ti:c?e=Oc:(Z(S_,(MF(),VF)),e=gb)));b=l;d&&LU(Z_)!=a.a&&(b+=UZ);d&&LU($_)!=a.a&&(b+=QZ);LU(f0)!=a.a&&(b+=TZ);LU(g0)!=a.a&&(b+=PZ);LU(S_)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=h0.mc.a.ob.selectedIndex;0<d&&(--d,e+=SZ+d);d=i0.mc.a.ob.selectedIndex;0<d&&(--d,e+=RZ+d);LU(j0)!=a.a&&(e=C_);LU(k0)!=a.a&&(e=oc);LU(l0)!=a.a&&(e=Gc);LU(m0)!=a.a&&(e=FZ);SG(a.e.mc,e)}
function n0(a){o0(a);p0(a);var b=h0.mc.a;H_(b,0);b.ob.options[0].selected=!0;b=i0.mc.a;H_(b,0);b.ob.options[0].selected=!0;Z(Z_,a.a);Z($_,a.a);Z(f0,a.a);Z(g0,a.a);Z(h0,a.a);Z(i0,a.a);q0(a)}function o0(a){Z(a0,a.a);Z(b0,a.a);Z(c0,a.a);Z(d0,a.a);Z(e0,a.a);Z(V_,a.a);Z(W_,a.a);Z(X_,a.a);Z(Y_,a.a)}function p0(a){Z(S_,a.a);Z(T_,a.a);Z(U_,a.a)}function q0(a){Z(j0,a.a);Z(k0,a.a);Z(l0,a.a);Z(m0,a.a);a.b=!1}
function P_(a){sV.call(this,a_);this.i=new lV(this.hg());FF(this.q,new ZV(this));this.a=(dI(),fI);this.c=a;this.d||(a=RE(a),this.d=new DV(a),VV(this.d,-150,10));this.j=this.d;oF(this,new N_);Z(this,this.a);a=new tF;oF(a,new lG(0,3,1));$(a,new O_($Z),null);S_=new lV(WZ);T_=new lV(XZ);U_=new lV(h_);$(a,S_,null);$(a,T_,null);$(a,U_,null);$(this,a,null);a=new tF;oF(a,new lG(0,3,1));$(a,new BV(q_,0),null);$(this,a,null);a=new tF;oF(a,new lG(0,3,1));a0=new lV(gd);b0=new lV(sf);c0=new lV(Kf);d0=new lV(Zf);
e0=new lV(Mf);V_=new lV(he);W_=new lV(Ad);X_=new lV(fd);Y_=new lV(se);$(a,a0,null);$(a,b0,null);$(a,c0,null);$(a,d0,null);$(a,e0,null);$(a,V_,null);$(a,W_,null);$(a,X_,null);$(a,Y_,null);$(this,a,null);a=new tF;oF(a,new lG(0,3,1));h0=new L_;K_(h0,WZ);K_(h0,$b);K_(h0,cc);K_(h0,hc);K_(h0,LZ);$(a,new O_(o_),null);$(a,h0,null);$(this,a,null);a=new tF;oF(a,new lG(0,3,1));i0=new L_;K_(i0,WZ);K_(i0,$b);K_(i0,cc);K_(i0,hc);K_(i0,LZ);K_(i0,MZ);K_(i0,NZ);K_(i0,OZ);$(a,new BV(n_,0),null);$(a,i0,null);$(a,new BV(DZ,
0),null);$(this,a,null);a=new tF;oF(a,new lG(0,3,1));$(a,new O_(ZZ),null);Z_=new lV(YZ);$(a,Z_,null);$_=new lV(l_);$(a,$_,null);f0=new lV(t_);$(a,f0,null);g0=new lV(m_);$(a,g0,null);$(this,a,null);a=new tF;Z(a,bG(LU(this)));oF(a,new lG(0,3,1));$(a,new O_(b_),null);j0=new lV(WZ);$(a,j0,null);k0=new lV(YZ);$(a,k0,null);l0=new lV(t_);$(a,l0,null);m0=new lV(m_);$(a,m0,null);$(this,a,null);a=new tF;oF(a,new lG(1,3,1));this.e=new RG(gb,20);$(a,this.e,null);$(a,new lV(s_),null);$(a,this.i,null);$(this,a,
null);this.mc&&uV(this.mc.c,!1);rV(this,!1);o0(this);p0(this);q0(this);Z(Z_,this.a);Z($_,this.a);Z(f0,this.a);Z(g0,this.a);Z(h0,this.a);Z(i0,this.a);Q_(this,S_);qV(this);a=this.j;XV(this.mc.c,a.a,a.b);!QE(this)&&UU(this);PU(this)}r(564,546,jP,P_);
_.ig=function(a,b){var c;M(b,s_)?(n0(this),Q_(this,S_),R_(this)):E(a.f,88)?(q0(this),Pz(a.f)===Pz(S_)?(o0(this),p0(this)):Pz(a.f)===Pz(T_)?(o0(this),p0(this)):Pz(a.f)===Pz(U_)?(o0(this),p0(this)):Pz(a.f)===Pz(f0)?Z(g0,this.a):Pz(a.f)===Pz(g0)?(Z(f0,this.a),Z(Z_,this.a)):Pz(a.f)===Pz(Z_)?(Z($_,this.a),Z(g0,this.a)):Pz(a.f)===Pz($_)?Z(Z_,this.a):Pz(a.f)===Pz(j0)||Pz(a.f)===Pz(k0)||Pz(a.f)===Pz(l0)||Pz(a.f)===Pz(m0)?(n0(this),this.b=!0):p0(this),Q_(this,a.f),R_(this)):E(a.f,89)&&(q0(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(MF(),VF)),R_(this));107!=this.c.e&&(this.c.e=107,yF(this.c));return!0};_.jg=function(){return hw(this.e.mc.a.ob,dq)};_.kg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var S_=_.e=null,j0=null,T_=null,Z_=null,k0=null,X_=null,a0=null,i0=null,h0=null,W_=null,V_=null,U_=null,Y_=null,b0=null,$_=null,g0=null,m0=null,c0=null,e0=null,f0=null,l0=null,d0=null;function M_(a){mO();oO.call(this);this.a=new I_;PB(this.a,new r0(this,a),(D_(),D_(),E_))}r(609,607,{},M_);_.Je=function(){return this.a};
_.a=null;function r0(a,b){this.a=a;this.b=b}r(610,1,{},r0);_.a=null;_.b=null;Y(564);Y(410);Y(609);Y(610);Y(341);Y(193);y(cP)(3);