var IN="3",JN="Any",KN="Aromatic",LN="Nonring",MN="Reset",NN="Ring";function ON(){ON=s;PN=new fo(Vc,new QN)}function QN(){}r(191,188,{},QN);_.Pc=function(a){Dv();hK(this,a.b,RN(a.a.a,a.a.a.ob.selectedIndex))};_.Sc=function(){return PN};var PN;function SN(a,b){if(0>b||b>=a.ob.options.length)throw new Fs;}function RN(a,b){SN(a,b);return a.ob.options[b].value}function TN(){this.ob=$doc.createElement("select");this.ob[Xc]="gwt-ListBox"}r(336,314,uh,TN);function UN(){UN=s}
function VN(a,b){if(null==b)throw new Gp("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(lf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function WN(){UN();Cv.call(this);new ri;this.mc=new XN((Dv(),this))}r(401,388,{89:1,91:1,98:1,110:1,116:1},WN);_.Yd=function(){return Hv(this.mc,this)};
_.le=function(){return(null==this.jc&&(this.jc=ov(this)),this.jc)+va+this.uc+va+this.vc+va+this.rc+Gg+this.hc+(this.qc?l:",hidden")+",current="+RN(this.mc.a,this.mc.a.ob.selectedIndex)};function YN(){FJ.call(this,7)}r(414,1,qh,YN);function ZN(a){HJ.call(this,a,0)}r(419,388,Wh,ZN);r(545,543,Gh);_.Lc=function(){!this.a.Ib?this.a.Ib=new $N(this.a):this.a.Ib.mc.c.gb?WK(this.a.Ib.mc.c):cK(this.a.Ib)};function aO(a,b){RI(b)==a.a?Z(b,(mw(),vw)):Z(b,a.a)}
function bO(a){var b,c,d,e;e=l;d=!1;RI(cO)!=a.a?(e=ta,d=!0):RI(dO)!=a.a?(e="!#6",d=!0):RI(eO)!=a.a?(Z(fO,(mw(),vw)),Z(nO,vw),Z(oO,vw),Z(pO,vw),e="F,Cl,Br,I"):(b=RI(qO)!=a.a,c=RI(rO)!=a.a,RI(sO)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),RI(tO)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),RI(uO)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),RI(vO)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),RI(wO)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),RI(fO)!=a.a&&(e+="F,"),RI(nO)!=a.a&&(e+="Cl,"),RI(oO)!=a.a&&(e+="Br,"),RI(pO)!=a.a&&(e+="I,"),
oC(e,va)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=nc:c?e=nb:(Z(cO,(mw(),vw)),e=ta)));b=l;d&&RI(qO)!=a.a&&(b+=";a");d&&RI(rO)!=a.a&&(b+=";A");RI(xO)!=a.a&&(b+=";R");RI(yO)!=a.a&&(b+=";!R");RI(cO)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=zO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=AO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);RI(BO)!=a.a&&(e="~");RI(CO)!=a.a&&(e=db);RI(DO)!=a.a&&(e=mb);RI(EO)!=a.a&&(e="!@");KJ(a.e,e)}
function FO(a){GO(a);HO(a);var b=zO.mc.a;SN(b,0);b.ob.options[0].selected=!0;b=AO.mc.a;SN(b,0);b.ob.options[0].selected=!0;Z(qO,a.a);Z(rO,a.a);Z(xO,a.a);Z(yO,a.a);Z(zO,a.a);Z(AO,a.a);IO(a)}function GO(a){Z(sO,a.a);Z(tO,a.a);Z(uO,a.a);Z(vO,a.a);Z(wO,a.a);Z(fO,a.a);Z(nO,a.a);Z(oO,a.a);Z(pO,a.a)}function HO(a){Z(cO,a.a);Z(dO,a.a);Z(eO,a.a)}function IO(a){Z(BO,a.a);Z(CO,a.a);Z(DO,a.a);Z(EO,a.a);a.b=!1}
function $N(a){yJ.call(this,"Atom/Bond Query");this.i=new rJ(this.dg());fw(this.q,new fK(this));this.a=(uy(),wy);this.c=a;this.d||(a=rv(a),this.d=new JJ(a),bK(this.d,-150,10));this.j=this.d;Qv(this,new YN);Z(this,this.a);a=new Vv;Qv(a,new Mw(0,3,1));$(a,new ZN("Atom type :"),null);cO=new rJ(JN);dO=new rJ("Any except C");eO=new rJ("Halogen");$(a,cO,null);$(a,dO,null);$(a,eO,null);$(this,a,null);a=new Vv;Qv(a,new Mw(0,3,1));$(a,new HJ("Or select one or more from the list :",0),null);$(this,a,null);
a=new Vv;Qv(a,new Mw(0,3,1));sO=new rJ(qb);tO=new rJ(Lb);uO=new rJ(Rb);vO=new rJ(Yb);wO=new rJ(Sb);fO=new rJ(yb);nO=new rJ(tb);oO=new rJ(pb);pO=new rJ(Gb);$(a,sO,null);$(a,tO,null);$(a,uO,null);$(a,vO,null);$(a,wO,null);$(a,fO,null);$(a,nO,null);$(a,oO,null);$(a,pO,null);$(this,a,null);a=new Vv;Qv(a,new Mw(0,3,1));zO=new WN;VN(zO,JN);VN(zO,Ya);VN(zO,$a);VN(zO,cb);VN(zO,IN);$(a,new ZN("Number of hydrogens :  "),null);$(a,zO,null);$(this,a,null);a=new Vv;Qv(a,new Mw(0,3,1));AO=new WN;VN(AO,JN);VN(AO,
Ya);VN(AO,$a);VN(AO,cb);VN(AO,IN);VN(AO,"4");VN(AO,"5");VN(AO,"6");$(a,new HJ("Number of connections :",0),null);$(a,AO,null);$(a,new HJ(" (H's don't count.)",0),null);$(this,a,null);a=new Vv;Qv(a,new Mw(0,3,1));$(a,new ZN("Atom is :"),null);qO=new rJ(KN);$(a,qO,null);rO=new rJ("Nonaromatic");$(a,rO,null);xO=new rJ(NN);$(a,xO,null);yO=new rJ(LN);$(a,yO,null);$(this,a,null);a=new Vv;Z(a,Cw(RI(this)));Qv(a,new Mw(0,3,1));$(a,new ZN("Bond is :"),null);BO=new rJ(JN);$(a,BO,null);CO=new rJ(KN);$(a,CO,
null);DO=new rJ(NN);$(a,DO,null);EO=new rJ(LN);$(a,EO,null);$(this,a,null);a=new Vv;Qv(a,new Mw(1,3,1));this.e=new rx(ta,20);$(a,this.e,null);$(a,new rJ(MN),null);$(a,this.i,null);$(this,a,null);this.mc&&AJ(this.mc.c,!1);xJ(this,!1);GO(this);HO(this);IO(this);Z(qO,this.a);Z(rO,this.a);Z(xO,this.a);Z(yO,this.a);Z(zO,this.a);Z(AO,this.a);aO(this,cO);wJ(this);a=this.j;dK(this.mc.c,a.a,a.b);!qv(this)&&$I(this);VI(this)}r(555,537,uF,$N);
_.eg=function(a,b){var c;H(b,MN)?(FO(this),aO(this,cO),bO(this)):E(a.f,88)?(IO(this),nq(a.f)===nq(cO)?(GO(this),HO(this)):nq(a.f)===nq(dO)?(GO(this),HO(this)):nq(a.f)===nq(eO)?(GO(this),HO(this)):nq(a.f)===nq(xO)?Z(yO,this.a):nq(a.f)===nq(yO)?(Z(xO,this.a),Z(qO,this.a)):nq(a.f)===nq(qO)?(Z(rO,this.a),Z(yO,this.a)):nq(a.f)===nq(rO)?Z(qO,this.a):nq(a.f)===nq(BO)||nq(a.f)===nq(CO)||nq(a.f)===nq(DO)||nq(a.f)===nq(EO)?(FO(this),this.b=!0):HO(this),aO(this,a.f),bO(this)):E(a.f,89)&&(IO(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(mw(),vw)),bO(this));107!=this.c.e&&(this.c.e=107,$v(this.c));return!0};_.fg=function(){return Bm(this.e.mc.a.ob,xg)};_.gg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var cO=_.e=null,BO=null,dO=null,qO=null,CO=null,oO=null,sO=null,AO=null,zO=null,nO=null,fO=null,eO=null,pO=null,tO=null,rO=null,yO=null,EO=null,uO=null,wO=null,xO=null,DO=null,vO=null;function XN(a){xE();zE.call(this);this.a=new TN;ms(this.a,new JO(this,a),(ON(),ON(),PN))}r(601,599,{},XN);_.Fe=function(){return this.a};
_.a=null;function JO(a,b){this.a=a;this.b=b}r(602,1,{},JO);_.a=null;_.b=null;Y(555);Y(401);Y(601);Y(602);Y(336);Y(191);y(nF)(3);