var IP="3",JP="Any",KP="Aromatic",LP="Nonring",MP="Reset",NP="Ring";function VP(){VP=r;WP=new kp(Yc,new XP)}function XP(){}q(215,212,{},XP);_.Tc=function(a){Nx();hM(this,a.b,YP(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return WP};var WP;function ZP(a,b){if(0>b||b>=a.ob.options.length)throw new Eu;}function YP(a,b){ZP(a,b);return a.ob.options[b].value}function $P(){wv();this.ob=$doc.createElement("select");this.ob[gd]="gwt-ListBox"}q(361,339,bi,$P);function aQ(){aQ=r}
function bQ(a,b){if(null==b)throw new cr("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(sf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function cQ(){aQ();Mx.call(this);new Di;this.mc=new dQ((Nx(),this))}q(428,415,{90:1,92:1,99:1,111:1,117:1},cQ);_.fe=function(){return Rx(this.mc,this)};
_.ue=function(){return(null==this.jc&&(this.jc=yx(this)),this.jc)+xa+this.uc+xa+this.vc+xa+this.rc+Sg+this.hc+(this.qc?l:",hidden")+",current="+YP(this.mc.a,this.mc.a.ob.selectedIndex)};function eQ(){FL.call(this,7)}q(441,1,ai,eQ);function fQ(a){HL.call(this,a,0)}q(446,415,Dh,fQ);q(583,581,ci);_.Pc=function(){!this.a.Ib?this.a.Ib=new gQ(this.a):this.a.Ib.mc.c.gb?WM(this.a.Ib.mc.c):cM(this.a.Ib)};function hQ(a,b){RK(b)==a.a?Z(b,(xy(),Gy)):Z(b,a.a)}
function iQ(a){var b,c,d,e;e=l;d=!1;RK(jQ)!=a.a?(e=va,d=!0):RK(kQ)!=a.a?(e="!#6",d=!0):RK(lQ)!=a.a?(Z(mQ,(xy(),Gy)),Z(nQ,Gy),Z(oQ,Gy),Z(pQ,Gy),e="F,Cl,Br,I"):(b=RK(qQ)!=a.a,c=RK(rQ)!=a.a,RK(sQ)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),RK(tQ)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),RK(uQ)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),RK(vQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),RK(wQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),RK(mQ)!=a.a&&(e+="F,"),RK(nQ)!=a.a&&(e+="Cl,"),RK(oQ)!=a.a&&(e+="Br,"),RK(pQ)!=a.a&&(e+="I,"),
OE(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=oc:c?e=qb:(Z(jQ,(xy(),Gy)),e=va)));b=l;d&&RK(qQ)!=a.a&&(b+=";a");d&&RK(rQ)!=a.a&&(b+=";A");RK(xQ)!=a.a&&(b+=";R");RK(yQ)!=a.a&&(b+=";!R");RK(jQ)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=zQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=AQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);RK(BQ)!=a.a&&(e="~");RK(CQ)!=a.a&&(e=gb);RK(DQ)!=a.a&&(e=pb);RK(EQ)!=a.a&&(e="!@");KL(a.e,e)}
function FQ(a){GQ(a);HQ(a);var b=zQ.mc.a;ZP(b,0);b.ob.options[0].selected=!0;b=AQ.mc.a;ZP(b,0);b.ob.options[0].selected=!0;Z(qQ,a.a);Z(rQ,a.a);Z(xQ,a.a);Z(yQ,a.a);Z(zQ,a.a);Z(AQ,a.a);IQ(a)}function GQ(a){Z(sQ,a.a);Z(tQ,a.a);Z(uQ,a.a);Z(vQ,a.a);Z(wQ,a.a);Z(mQ,a.a);Z(nQ,a.a);Z(oQ,a.a);Z(pQ,a.a)}function HQ(a){Z(jQ,a.a);Z(kQ,a.a);Z(lQ,a.a)}function IQ(a){Z(BQ,a.a);Z(CQ,a.a);Z(DQ,a.a);Z(EQ,a.a);a.b=!1}
function gQ(a){yL.call(this,"Atom/Bond Query");this.i=new rL(this.og());qy(this.q,new fM(this));this.a=(SA(),UA);this.c=a;this.d||(a=Bx(a),this.d=new JL(a),bM(this.d,-150,10));this.j=this.d;$x(this,new eQ);Z(this,this.a);a=new ey;$x(a,new Xy(0,3,1));$(a,new fQ("Atom type :"),null);jQ=new rL(JP);kQ=new rL("Any except C");lQ=new rL("Halogen");$(a,jQ,null);$(a,kQ,null);$(a,lQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));$(a,new HL("Or select one or more from the list :",0),null);$(this,a,null);
a=new ey;$x(a,new Xy(0,3,1));sQ=new rL(ub);tQ=new rL(Rb);uQ=new rL(Vb);vQ=new rL(cc);wQ=new rL(Wb);mQ=new rL(Cb);nQ=new rL(yb);oQ=new rL(tb);pQ=new rL(Kb);$(a,sQ,null);$(a,tQ,null);$(a,uQ,null);$(a,vQ,null);$(a,wQ,null);$(a,mQ,null);$(a,nQ,null);$(a,oQ,null);$(a,pQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));zQ=new cQ;bQ(zQ,JP);bQ(zQ,$a);bQ(zQ,cb);bQ(zQ,fb);bQ(zQ,IP);$(a,new fQ("Number of hydrogens :  "),null);$(a,zQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));AQ=new cQ;bQ(AQ,JP);bQ(AQ,
$a);bQ(AQ,cb);bQ(AQ,fb);bQ(AQ,IP);bQ(AQ,"4");bQ(AQ,"5");bQ(AQ,"6");$(a,new HL("Number of connections :",0),null);$(a,AQ,null);$(a,new HL(" (H's don't count.)",0),null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));$(a,new fQ("Atom is :"),null);qQ=new rL(KP);$(a,qQ,null);rQ=new rL("Nonaromatic");$(a,rQ,null);xQ=new rL(NP);$(a,xQ,null);yQ=new rL(LP);$(a,yQ,null);$(this,a,null);a=new ey;Z(a,Ny(RK(this)));$x(a,new Xy(0,3,1));$(a,new fQ("Bond is :"),null);BQ=new rL(JP);$(a,BQ,null);CQ=new rL(KP);$(a,CQ,
null);DQ=new rL(NP);$(a,DQ,null);EQ=new rL(LP);$(a,EQ,null);$(this,a,null);a=new ey;$x(a,new Xy(1,3,1));this.e=new Bz(va,20);$(a,this.e,null);$(a,new rL(MP),null);$(a,this.i,null);$(this,a,null);this.mc&&AL(this.mc.c,!1);xL(this,!1);GQ(this);HQ(this);IQ(this);Z(qQ,this.a);Z(rQ,this.a);Z(xQ,this.a);Z(yQ,this.a);Z(zQ,this.a);Z(AQ,this.a);hQ(this,jQ);wL(this);a=this.j;dM(this.mc.c,a.a,a.b);!Ax(this)&&$K(this);VK(this)}q(593,575,SH,gQ);
_.pg=function(a,b){var c;H(b,MP)?(FQ(this),hQ(this,jQ),iQ(this)):D(a.f,89)?(IQ(this),Kr(a.f)===Kr(jQ)?(GQ(this),HQ(this)):Kr(a.f)===Kr(kQ)?(GQ(this),HQ(this)):Kr(a.f)===Kr(lQ)?(GQ(this),HQ(this)):Kr(a.f)===Kr(xQ)?Z(yQ,this.a):Kr(a.f)===Kr(yQ)?(Z(xQ,this.a),Z(qQ,this.a)):Kr(a.f)===Kr(qQ)?(Z(rQ,this.a),Z(yQ,this.a)):Kr(a.f)===Kr(rQ)?Z(qQ,this.a):Kr(a.f)===Kr(BQ)||Kr(a.f)===Kr(CQ)||Kr(a.f)===Kr(DQ)||Kr(a.f)===Kr(EQ)?(FQ(this),this.b=!0):HQ(this),hQ(this,a.f),iQ(this)):D(a.f,90)&&(IQ(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(xy(),Gy)),iQ(this));107!=this.c.e&&(this.c.e=107,jy(this.c));return!0};_.qg=function(){return Tm(this.e.mc.a.ob,Mg)};_.rg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var jQ=_.e=null,BQ=null,kQ=null,qQ=null,CQ=null,oQ=null,sQ=null,AQ=null,zQ=null,nQ=null,mQ=null,lQ=null,pQ=null,tQ=null,rQ=null,yQ=null,EQ=null,uQ=null,wQ=null,xQ=null,DQ=null,vQ=null;function dQ(a){XG();ZG.call(this);this.a=new $P;lu(this.a,new JQ(this,a),(VP(),VP(),WP))}q(639,637,{},dQ);_.Oe=function(){return this.a};
_.a=null;function JQ(a,b){this.a=a;this.b=b}q(640,1,{},JQ);_.a=null;_.b=null;W(593);W(428);W(639);W(640);W(361);W(215);x(OH)(3);