var HN="3",IN="Any",JN="Aromatic",KN="Nonring",LN="Reset",MN="Ring";function NN(){NN=s;ON=new $n(Rc,new PN)}function PN(){}r(194,191,{},PN);_.Pc=function(a){Dv();gK(this,a.b,QN(a.a.a,a.a.a.ob.selectedIndex))};_.Sc=function(){return ON};var ON;function RN(a,b){if(0>b||b>=a.ob.options.length)throw new Es;}function QN(a,b){RN(a,b);return a.ob.options[b].value}function SN(){this.ob=$doc.createElement("select");this.ob[Tc]="gwt-ListBox"}r(342,320,rh,SN);function TN(){TN=s}
function UN(a,b){if(null==b)throw new Bp("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(gf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function VN(){TN();Cv.call(this);new ni;this.mc=new WN((Dv(),this))}r(408,395,{89:1,91:1,98:1,110:1,116:1},VN);_.Yd=function(){return Hv(this.mc,this)};
_.le=function(){return(null==this.jc&&(this.jc=ov(this)),this.jc)+va+this.uc+va+this.vc+va+this.rc+Dg+this.hc+(this.qc?l:",hidden")+",current="+QN(this.mc.a,this.mc.a.ob.selectedIndex)};function XN(){EJ.call(this,7)}r(421,1,nh,XN);function YN(a){GJ.call(this,a,0)}r(426,395,Sh,YN);r(552,550,Dh);_.Lc=function(){!this.a.Ib?this.a.Ib=new ZN(this.a):this.a.Ib.mc.c.gb?VK(this.a.Ib.mc.c):bK(this.a.Ib)};function $N(a,b){QI(b)==a.a?Z(b,(mw(),vw)):Z(b,a.a)}
function aO(a){var b,c,d,e;e=l;d=!1;QI(bO)!=a.a?(e=ta,d=!0):QI(cO)!=a.a?(e="!#6",d=!0):QI(dO)!=a.a?(Z(eO,(mw(),vw)),Z(hO,vw),Z(iO,vw),Z(jO,vw),e="F,Cl,Br,I"):(b=QI(kO)!=a.a,c=QI(lO)!=a.a,QI(mO)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),QI(nO)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),QI(oO)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),QI(pO)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),QI(qO)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),QI(eO)!=a.a&&(e+="F,"),QI(hO)!=a.a&&(e+="Cl,"),QI(iO)!=a.a&&(e+="Br,"),QI(jO)!=a.a&&(e+="I,"),
pC(e,va)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=lc:c?e=ob:(Z(bO,(mw(),vw)),e=ta)));b=l;d&&QI(kO)!=a.a&&(b+=";a");d&&QI(lO)!=a.a&&(b+=";A");QI(rO)!=a.a&&(b+=";R");QI(sO)!=a.a&&(b+=";!R");QI(bO)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=tO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=uO.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);QI(vO)!=a.a&&(e="~");QI(wO)!=a.a&&(e=db);QI(xO)!=a.a&&(e=lb);QI(yO)!=a.a&&(e="!@");JJ(a.e,e)}
function zO(a){AO(a);BO(a);var b=tO.mc.a;RN(b,0);b.ob.options[0].selected=!0;b=uO.mc.a;RN(b,0);b.ob.options[0].selected=!0;Z(kO,a.a);Z(lO,a.a);Z(rO,a.a);Z(sO,a.a);Z(tO,a.a);Z(uO,a.a);CO(a)}function AO(a){Z(mO,a.a);Z(nO,a.a);Z(oO,a.a);Z(pO,a.a);Z(qO,a.a);Z(eO,a.a);Z(hO,a.a);Z(iO,a.a);Z(jO,a.a)}function BO(a){Z(bO,a.a);Z(cO,a.a);Z(dO,a.a)}function CO(a){Z(vO,a.a);Z(wO,a.a);Z(xO,a.a);Z(yO,a.a);a.b=!1}
function ZN(a){xJ.call(this,"Atom/Bond Query");this.i=new qJ(this.dg());fw(this.q,new eK(this));this.a=(ty(),vy);this.c=a;this.d||(a=rv(a),this.d=new IJ(a),aK(this.d,-150,10));this.j=this.d;Qv(this,new XN);Z(this,this.a);a=new Vv;Qv(a,new Mw(0,3,1));$(a,new YN("Atom type :"),null);bO=new qJ(IN);cO=new qJ("Any except C");dO=new qJ("Halogen");$(a,bO,null);$(a,cO,null);$(a,dO,null);$(this,a,null);a=new Vv;Qv(a,new Mw(0,3,1));$(a,new GJ("Or select one or more from the list :",0),null);$(this,a,null);
a=new Vv;Qv(a,new Mw(0,3,1));mO=new qJ(rb);nO=new qJ(Lb);oO=new qJ(Rb);pO=new qJ(Yb);qO=new qJ(Sb);eO=new qJ(Ab);hO=new qJ(vb);iO=new qJ(qb);jO=new qJ(Eb);$(a,mO,null);$(a,nO,null);$(a,oO,null);$(a,pO,null);$(a,qO,null);$(a,eO,null);$(a,hO,null);$(a,iO,null);$(a,jO,null);$(this,a,null);a=new Vv;Qv(a,new Mw(0,3,1));tO=new VN;UN(tO,IN);UN(tO,Ya);UN(tO,$a);UN(tO,cb);UN(tO,HN);$(a,new YN("Number of hydrogens :  "),null);$(a,tO,null);$(this,a,null);a=new Vv;Qv(a,new Mw(0,3,1));uO=new VN;UN(uO,IN);UN(uO,
Ya);UN(uO,$a);UN(uO,cb);UN(uO,HN);UN(uO,"4");UN(uO,"5");UN(uO,"6");$(a,new GJ("Number of connections :",0),null);$(a,uO,null);$(a,new GJ(" (H's don't count.)",0),null);$(this,a,null);a=new Vv;Qv(a,new Mw(0,3,1));$(a,new YN("Atom is :"),null);kO=new qJ(JN);$(a,kO,null);lO=new qJ("Nonaromatic");$(a,lO,null);rO=new qJ(MN);$(a,rO,null);sO=new qJ(KN);$(a,sO,null);$(this,a,null);a=new Vv;Z(a,Cw(QI(this)));Qv(a,new Mw(0,3,1));$(a,new YN("Bond is :"),null);vO=new qJ(IN);$(a,vO,null);wO=new qJ(JN);$(a,wO,
null);xO=new qJ(MN);$(a,xO,null);yO=new qJ(KN);$(a,yO,null);$(this,a,null);a=new Vv;Qv(a,new Mw(1,3,1));this.e=new qx(ta,20);$(a,this.e,null);$(a,new qJ(LN),null);$(a,this.i,null);$(this,a,null);this.mc&&zJ(this.mc.c,!1);wJ(this,!1);AO(this);BO(this);CO(this);Z(kO,this.a);Z(lO,this.a);Z(rO,this.a);Z(sO,this.a);Z(tO,this.a);Z(uO,this.a);$N(this,bO);vJ(this);a=this.j;cK(this.mc.c,a.a,a.b);!qv(this)&&ZI(this);UI(this)}r(562,544,vF,ZN);
_.eg=function(a,b){var c;H(b,LN)?(zO(this),$N(this,bO),aO(this)):E(a.f,88)?(CO(this),iq(a.f)===iq(bO)?(AO(this),BO(this)):iq(a.f)===iq(cO)?(AO(this),BO(this)):iq(a.f)===iq(dO)?(AO(this),BO(this)):iq(a.f)===iq(rO)?Z(sO,this.a):iq(a.f)===iq(sO)?(Z(rO,this.a),Z(kO,this.a)):iq(a.f)===iq(kO)?(Z(lO,this.a),Z(sO,this.a)):iq(a.f)===iq(lO)?Z(kO,this.a):iq(a.f)===iq(vO)||iq(a.f)===iq(wO)||iq(a.f)===iq(xO)||iq(a.f)===iq(yO)?(zO(this),this.b=!0):BO(this),$N(this,a.f),aO(this)):E(a.f,89)&&(CO(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(mw(),vw)),aO(this));107!=this.c.e&&(this.c.e=107,$v(this.c));return!0};_.fg=function(){return wm(this.e.mc.a.ob,ug)};_.gg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var bO=_.e=null,vO=null,cO=null,kO=null,wO=null,iO=null,mO=null,uO=null,tO=null,hO=null,eO=null,dO=null,jO=null,nO=null,lO=null,sO=null,yO=null,oO=null,qO=null,rO=null,xO=null,pO=null;function WN(a){yE();AE.call(this);this.a=new SN;ls(this.a,new DO(this,a),(NN(),NN(),ON))}r(608,606,{},WN);_.Fe=function(){return this.a};
_.a=null;function DO(a,b){this.a=a;this.b=b}r(609,1,{},DO);_.a=null;_.b=null;Y(562);Y(408);Y(608);Y(609);Y(342);Y(194);y(oF)(3);