var aQ="3",bQ="Any",cQ="Aromatic",dQ="Nonring",eQ="Reset",mQ="Ring";function nQ(){nQ=r;oQ=new Ep(Xc,new pQ)}function pQ(){}q(217,214,{},pQ);_.Tc=function(a){cy();BM(this,a.b,qQ(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return oQ};var oQ;function rQ(a,b){if(0>b||b>=a.ob.options.length)throw new Yu;}function qQ(a,b){rQ(a,b);return a.ob.options[b].value}function sQ(){this.ob=$doc.createElement("select");this.ob[Zc]="gwt-ListBox"}q(364,342,bi,sQ);function tQ(){tQ=r}
function uQ(a,b){if(null==b)throw new vr("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(sf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function vQ(){tQ();by.call(this);new Fi;this.mc=new wQ((cy(),this))}q(432,419,{91:1,93:1,100:1,112:1,118:1},vQ);_.ee=function(){return gy(this.mc,this)};
_.te=function(){return(null==this.jc&&(this.jc=Ox(this)),this.jc)+xa+this.uc+xa+this.vc+xa+this.rc+Rg+this.hc+(this.qc?l:",hidden")+",current="+qQ(this.mc.a,this.mc.a.ob.selectedIndex)};function xQ(){ZL.call(this,7)}q(445,1,mi,xQ);function yQ(a){aM.call(this,a,0)}q(450,419,Sh,yQ);q(587,585,Gh);_.Pc=function(){!this.a.Ib?this.a.Ib=new zQ(this.a):this.a.Ib.mc.c.gb?pN(this.a.Ib.mc.c):wM(this.a.Ib)};function AQ(a,b){kL(b)==a.a?Z(b,(Ny(),Wy)):Z(b,a.a)}
function BQ(a){var b,c,d,e;e=l;d=!1;kL(CQ)!=a.a?(e=va,d=!0):kL(DQ)!=a.a?(e="!#6",d=!0):kL(EQ)!=a.a?(Z(FQ,(Ny(),Wy)),Z(GQ,Wy),Z(HQ,Wy),Z(IQ,Wy),e="F,Cl,Br,I"):(b=kL(JQ)!=a.a,c=kL(KQ)!=a.a,kL(LQ)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),kL(MQ)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),kL(NQ)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),kL(OQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),kL(PQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),kL(FQ)!=a.a&&(e+="F,"),kL(GQ)!=a.a&&(e+="Cl,"),kL(HQ)!=a.a&&(e+="Br,"),kL(IQ)!=a.a&&(e+="I,"),
eF(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=pc:c?e=qb:(Z(CQ,(Ny(),Wy)),e=va)));b=l;d&&kL(JQ)!=a.a&&(b+=";a");d&&kL(KQ)!=a.a&&(b+=";A");kL(QQ)!=a.a&&(b+=";R");kL(RQ)!=a.a&&(b+=";!R");kL(CQ)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=SQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=TQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);kL(UQ)!=a.a&&(e="~");kL(VQ)!=a.a&&(e=gb);kL(WQ)!=a.a&&(e=pb);kL(XQ)!=a.a&&(e="!@");dM(a.e,e)}
function YQ(a){ZQ(a);$Q(a);var b=SQ.mc.a;rQ(b,0);b.ob.options[0].selected=!0;b=TQ.mc.a;rQ(b,0);b.ob.options[0].selected=!0;Z(JQ,a.a);Z(KQ,a.a);Z(QQ,a.a);Z(RQ,a.a);Z(SQ,a.a);Z(TQ,a.a);aR(a)}function ZQ(a){Z(LQ,a.a);Z(MQ,a.a);Z(NQ,a.a);Z(OQ,a.a);Z(PQ,a.a);Z(FQ,a.a);Z(GQ,a.a);Z(HQ,a.a);Z(IQ,a.a)}function $Q(a){Z(CQ,a.a);Z(DQ,a.a);Z(EQ,a.a)}function aR(a){Z(UQ,a.a);Z(VQ,a.a);Z(WQ,a.a);Z(XQ,a.a);a.b=!1}
function zQ(a){SL.call(this,"Atom/Bond Query");this.i=new LL(this.ng());Gy(this.q,new zM(this));this.a=(kB(),mB);this.c=a;this.d||(a=Rx(a),this.d=new cM(a),vM(this.d,-150,10));this.j=this.d;py(this,new xQ);Z(this,this.a);a=new uy;py(a,new mz(0,3,1));$(a,new yQ("Atom type :"),null);CQ=new LL(bQ);DQ=new LL("Any except C");EQ=new LL("Halogen");$(a,CQ,null);$(a,DQ,null);$(a,EQ,null);$(this,a,null);a=new uy;py(a,new mz(0,3,1));$(a,new aM("Or select one or more from the list :",0),null);$(this,a,null);
a=new uy;py(a,new mz(0,3,1));LQ=new LL(tb);MQ=new LL(Rb);NQ=new LL(Vb);OQ=new LL(cc);PQ=new LL(Wb);FQ=new LL(Cb);GQ=new LL(xb);HQ=new LL(sb);IQ=new LL(Kb);$(a,LQ,null);$(a,MQ,null);$(a,NQ,null);$(a,OQ,null);$(a,PQ,null);$(a,FQ,null);$(a,GQ,null);$(a,HQ,null);$(a,IQ,null);$(this,a,null);a=new uy;py(a,new mz(0,3,1));SQ=new vQ;uQ(SQ,bQ);uQ(SQ,$a);uQ(SQ,bb);uQ(SQ,fb);uQ(SQ,aQ);$(a,new yQ("Number of hydrogens :  "),null);$(a,SQ,null);$(this,a,null);a=new uy;py(a,new mz(0,3,1));TQ=new vQ;uQ(TQ,bQ);uQ(TQ,
$a);uQ(TQ,bb);uQ(TQ,fb);uQ(TQ,aQ);uQ(TQ,"4");uQ(TQ,"5");uQ(TQ,"6");$(a,new aM("Number of connections :",0),null);$(a,TQ,null);$(a,new aM(" (H's don't count.)",0),null);$(this,a,null);a=new uy;py(a,new mz(0,3,1));$(a,new yQ("Atom is :"),null);JQ=new LL(cQ);$(a,JQ,null);KQ=new LL("Nonaromatic");$(a,KQ,null);QQ=new LL(mQ);$(a,QQ,null);RQ=new LL(dQ);$(a,RQ,null);$(this,a,null);a=new uy;Z(a,cz(kL(this)));py(a,new mz(0,3,1));$(a,new yQ("Bond is :"),null);UQ=new LL(bQ);$(a,UQ,null);VQ=new LL(cQ);$(a,VQ,
null);WQ=new LL(mQ);$(a,WQ,null);XQ=new LL(dQ);$(a,XQ,null);$(this,a,null);a=new uy;py(a,new mz(1,3,1));this.e=new Sz(va,20);$(a,this.e,null);$(a,new LL(eQ),null);$(a,this.i,null);$(this,a,null);this.mc&&UL(this.mc.c,!1);RL(this,!1);ZQ(this);$Q(this);aR(this);Z(JQ,this.a);Z(KQ,this.a);Z(QQ,this.a);Z(RQ,this.a);Z(SQ,this.a);Z(TQ,this.a);AQ(this,CQ);QL(this);a=this.j;xM(this.mc.c,a.a,a.b);!Qx(this)&&tL(this);oL(this)}q(597,579,hI,zQ);
_.og=function(a,b){var c;H(b,eQ)?(YQ(this),AQ(this,CQ),BQ(this)):D(a.f,90)?(aR(this),cs(a.f)===cs(CQ)?(ZQ(this),$Q(this)):cs(a.f)===cs(DQ)?(ZQ(this),$Q(this)):cs(a.f)===cs(EQ)?(ZQ(this),$Q(this)):cs(a.f)===cs(QQ)?Z(RQ,this.a):cs(a.f)===cs(RQ)?(Z(QQ,this.a),Z(JQ,this.a)):cs(a.f)===cs(JQ)?(Z(KQ,this.a),Z(RQ,this.a)):cs(a.f)===cs(KQ)?Z(JQ,this.a):cs(a.f)===cs(UQ)||cs(a.f)===cs(VQ)||cs(a.f)===cs(WQ)||cs(a.f)===cs(XQ)?(YQ(this),this.b=!0):$Q(this),AQ(this,a.f),BQ(this)):D(a.f,91)&&(aR(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(Ny(),Wy)),BQ(this));107!=this.c.e&&(this.c.e=107,zy(this.c));return!0};_.pg=function(){return Ym(this.e.mc.a.ob,Lg)};_.qg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var CQ=_.e=null,UQ=null,DQ=null,JQ=null,VQ=null,HQ=null,LQ=null,TQ=null,SQ=null,GQ=null,FQ=null,EQ=null,IQ=null,MQ=null,KQ=null,RQ=null,XQ=null,NQ=null,PQ=null,QQ=null,WQ=null,OQ=null;function wQ(a){mH();oH.call(this);this.a=new sQ;Fu(this.a,new bR(this,a),(nQ(),nQ(),oQ))}q(643,641,{},wQ);_.Ne=function(){return this.a};
_.a=null;function bR(a,b){this.a=a;this.b=b}q(644,1,{},bR);_.a=null;_.b=null;W(597);W(432);W(643);W(644);W(364);W(217);x(eI)(3);