var JP="3",KP="Any",LP="Aromatic",MP="Nonring",NP="Reset",OP="Ring";function WP(){WP=r;XP=new lp(Zc,new YP)}function YP(){}q(215,212,{},YP);_.Tc=function(a){Nx();iM(this,a.b,ZP(a.a.a,a.a.a.ob.selectedIndex))};_.Wc=function(){return XP};var XP;function $P(a,b){if(0>b||b>=a.ob.options.length)throw new Eu;}function ZP(a,b){$P(a,b);return a.ob.options[b].value}function aQ(){wv();this.ob=$doc.createElement("select");this.ob[hd]="gwt-ListBox"}q(361,339,ci,aQ);function bQ(){bQ=r}
function cQ(a,b){if(null==b)throw new cr("Missing message: awt.103");var c=-1,d,e,f;f=a.mc.a.ob;e=$doc.createElement(tf);e.text=b;e.removeAttribute("bidiwrapped");e.value=b;d=f.options.length;(0>c||c>d)&&(c=d);c==d?f.add(e,null):(c=f.options[c],f.add(e,c))}function dQ(){bQ();Mx.call(this);new Ei;this.mc=new eQ((Nx(),this))}q(428,415,{90:1,92:1,99:1,111:1,117:1},dQ);_.fe=function(){return Rx(this.mc,this)};
_.ue=function(){return(null==this.jc&&(this.jc=yx(this)),this.jc)+xa+this.uc+xa+this.vc+xa+this.rc+Tg+this.hc+(this.qc?l:",hidden")+",current="+ZP(this.mc.a,this.mc.a.ob.selectedIndex)};function fQ(){GL.call(this,7)}q(441,1,bi,fQ);function gQ(a){IL.call(this,a,0)}q(446,415,Eh,gQ);q(583,581,di);_.Pc=function(){!this.a.Ib?this.a.Ib=new hQ(this.a):this.a.Ib.mc.c.gb?XM(this.a.Ib.mc.c):dM(this.a.Ib)};function iQ(a,b){SK(b)==a.a?Z(b,(xy(),Gy)):Z(b,a.a)}
function jQ(a){var b,c,d,e;e=l;d=!1;SK(kQ)!=a.a?(e=va,d=!0):SK(lQ)!=a.a?(e="!#6",d=!0):SK(mQ)!=a.a?(Z(nQ,(xy(),Gy)),Z(oQ,Gy),Z(pQ,Gy),Z(qQ,Gy),e="F,Cl,Br,I"):(b=SK(rQ)!=a.a,c=SK(sQ)!=a.a,SK(tQ)!=a.a&&(b?e+="c,":c?e+="C,":e+="#6,"),SK(uQ)!=a.a&&(b?e+="n,":c?e+="N,":e+="#7,"),SK(vQ)!=a.a&&(b?e+="o,":c?e+="O,":e+="#8,"),SK(wQ)!=a.a&&(b?e+="s,":c?e+="S,":e+="#16,"),SK(xQ)!=a.a&&(b?e+="p,":c?e+="P,":e+="#15,"),SK(nQ)!=a.a&&(e+="F,"),SK(oQ)!=a.a&&(e+="Cl,"),SK(pQ)!=a.a&&(e+="Br,"),SK(qQ)!=a.a&&(e+="I,"),
QE(e,xa)&&(e=e.substr(0,e.length-1-0)),1>e.length&&!a.b&&(b?e=pc:c?e=qb:(Z(kQ,(xy(),Gy)),e=va)));b=l;d&&SK(rQ)!=a.a&&(b+=";a");d&&SK(sQ)!=a.a&&(b+=";A");SK(yQ)!=a.a&&(b+=";R");SK(zQ)!=a.a&&(b+=";!R");SK(kQ)!=a.a&&0<b.length?e=b.substr(1,b.length-1):e+=b;d=AQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";H"+d);d=BQ.mc.a.ob.selectedIndex;0<d&&(--d,e+=";D"+d);SK(CQ)!=a.a&&(e="~");SK(DQ)!=a.a&&(e=gb);SK(EQ)!=a.a&&(e=pb);SK(FQ)!=a.a&&(e="!@");LL(a.e,e)}
function GQ(a){HQ(a);IQ(a);var b=AQ.mc.a;$P(b,0);b.ob.options[0].selected=!0;b=BQ.mc.a;$P(b,0);b.ob.options[0].selected=!0;Z(rQ,a.a);Z(sQ,a.a);Z(yQ,a.a);Z(zQ,a.a);Z(AQ,a.a);Z(BQ,a.a);JQ(a)}function HQ(a){Z(tQ,a.a);Z(uQ,a.a);Z(vQ,a.a);Z(wQ,a.a);Z(xQ,a.a);Z(nQ,a.a);Z(oQ,a.a);Z(pQ,a.a);Z(qQ,a.a)}function IQ(a){Z(kQ,a.a);Z(lQ,a.a);Z(mQ,a.a)}function JQ(a){Z(CQ,a.a);Z(DQ,a.a);Z(EQ,a.a);Z(FQ,a.a);a.b=!1}
function hQ(a){zL.call(this,"Atom/Bond Query");this.i=new sL(this.og());qy(this.q,new gM(this));this.a=(UA(),WA);this.c=a;this.d||(a=Bx(a),this.d=new KL(a),cM(this.d,-150,10));this.j=this.d;$x(this,new fQ);Z(this,this.a);a=new ey;$x(a,new Xy(0,3,1));$(a,new gQ("Atom type :"),null);kQ=new sL(KP);lQ=new sL("Any except C");mQ=new sL("Halogen");$(a,kQ,null);$(a,lQ,null);$(a,mQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));$(a,new IL("Or select one or more from the list :",0),null);$(this,a,null);
a=new ey;$x(a,new Xy(0,3,1));tQ=new sL(ub);uQ=new sL(Rb);vQ=new sL(Vb);wQ=new sL(cc);xQ=new sL(Wb);nQ=new sL(Gb);oQ=new sL(yb);pQ=new sL(tb);qQ=new sL(Kb);$(a,tQ,null);$(a,uQ,null);$(a,vQ,null);$(a,wQ,null);$(a,xQ,null);$(a,nQ,null);$(a,oQ,null);$(a,pQ,null);$(a,qQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));AQ=new dQ;cQ(AQ,KP);cQ(AQ,$a);cQ(AQ,cb);cQ(AQ,fb);cQ(AQ,JP);$(a,new gQ("Number of hydrogens :  "),null);$(a,AQ,null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));BQ=new dQ;cQ(BQ,KP);cQ(BQ,
$a);cQ(BQ,cb);cQ(BQ,fb);cQ(BQ,JP);cQ(BQ,"4");cQ(BQ,"5");cQ(BQ,"6");$(a,new IL("Number of connections :",0),null);$(a,BQ,null);$(a,new IL(" (H's don't count.)",0),null);$(this,a,null);a=new ey;$x(a,new Xy(0,3,1));$(a,new gQ("Atom is :"),null);rQ=new sL(LP);$(a,rQ,null);sQ=new sL("Nonaromatic");$(a,sQ,null);yQ=new sL(OP);$(a,yQ,null);zQ=new sL(MP);$(a,zQ,null);$(this,a,null);a=new ey;Z(a,Ny(SK(this)));$x(a,new Xy(0,3,1));$(a,new gQ("Bond is :"),null);CQ=new sL(KP);$(a,CQ,null);DQ=new sL(LP);$(a,DQ,
null);EQ=new sL(OP);$(a,EQ,null);FQ=new sL(MP);$(a,FQ,null);$(this,a,null);a=new ey;$x(a,new Xy(1,3,1));this.e=new Bz(va,20);$(a,this.e,null);$(a,new sL(NP),null);$(a,this.i,null);$(this,a,null);this.mc&&BL(this.mc.c,!1);yL(this,!1);HQ(this);IQ(this);JQ(this);Z(rQ,this.a);Z(sQ,this.a);Z(yQ,this.a);Z(zQ,this.a);Z(AQ,this.a);Z(BQ,this.a);iQ(this,kQ);xL(this);a=this.j;eM(this.mc.c,a.a,a.b);!Ax(this)&&aL(this);WK(this)}q(593,575,TH,hQ);
_.pg=function(a,b){var c;H(b,NP)?(GQ(this),iQ(this,kQ),jQ(this)):D(a.f,89)?(JQ(this),Kr(a.f)===Kr(kQ)?(HQ(this),IQ(this)):Kr(a.f)===Kr(lQ)?(HQ(this),IQ(this)):Kr(a.f)===Kr(mQ)?(HQ(this),IQ(this)):Kr(a.f)===Kr(yQ)?Z(zQ,this.a):Kr(a.f)===Kr(zQ)?(Z(yQ,this.a),Z(rQ,this.a)):Kr(a.f)===Kr(rQ)?(Z(sQ,this.a),Z(zQ,this.a)):Kr(a.f)===Kr(sQ)?Z(rQ,this.a):Kr(a.f)===Kr(CQ)||Kr(a.f)===Kr(DQ)||Kr(a.f)===Kr(EQ)||Kr(a.f)===Kr(FQ)?(GQ(this),this.b=!0):IQ(this),iQ(this,a.f),jQ(this)):D(a.f,90)&&(JQ(this),c=a.f,0==c.mc.a.ob.selectedIndex?
Z(c,this.a):Z(c,(xy(),Gy)),jQ(this));107!=this.c.e&&(this.c.e=107,jy(this.c));return!0};_.qg=function(){return Um(this.e.mc.a.ob,Ng)};_.rg=function(){return this.b};_.b=!1;_.c=null;_.d=null;var kQ=_.e=null,CQ=null,lQ=null,rQ=null,DQ=null,pQ=null,tQ=null,BQ=null,AQ=null,oQ=null,nQ=null,mQ=null,qQ=null,uQ=null,sQ=null,zQ=null,FQ=null,vQ=null,xQ=null,yQ=null,EQ=null,wQ=null;function eQ(a){YG();$G.call(this);this.a=new aQ;lu(this.a,new KQ(this,a),(WP(),WP(),XP))}q(639,637,{},eQ);_.Oe=function(){return this.a};
_.a=null;function KQ(a,b){this.a=a;this.b=b}q(640,1,{},KQ);_.a=null;_.b=null;W(593);W(428);W(639);W(640);W(361);W(215);x(PH)(3);